### ISSUE TITLE
Add support for editing and retaining local options for form fields

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#100]
The Name of Supervisor and Name of Spray Operator are two fields in the IRS event form. These fields change everyday and are dependent on the team deployed on that day.

### End User Feature Request
- Allow supervisors to define a list of supervisor names available for a particular day to be collected in that form. If there is only one supervisor on assignment that supervisor is the default.
- Allow the user to define a list of spray operators who are working that day so they don't have to type the name in every time. (Usually 3 spray operators)
- Have the ability to make these changes offline

### Technical Implementation Discussion
We could deliver this in a few ways depending on Android client vs Server side implementation

Android client only - We would probably want to figure out how to sync this
1. Add the ability to the native form library to support editing option sets. A user would be able to add or remove option values in the Android client so the fields are available.
2. Add an "Other" Question type to the native form that allows any "Other" attribute to be added to the list of available options. So, in the first form, they type the name in "Other" and it adds it to the main question. (We would also need a way of syncing or removing that when the list becomes too long).
3. Add a way for a user to make changes to their local list sets in the Android client. So, if we create a list of "supervisors", the user would have a UI to add members to this list set and choose which of the values to display in the form today.

Server Side - We need more details from Akros on this

**Comment by anniecmartin** [comment]
In the current mSpray workflow, Supervisor is linked to the district level, so any given form, a user is able to select which supervisor they are currently working with based on their previous selection as to which district they are working in. 
From a reporting perspective, this attribute is needed to aggregate data by it.
