### ISSUE TITLE
Remove Type from the Sort By Drop Down on Namibia APK

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1004]
- [ ] We removed the type category from the Namibia filters. However Type still appears under the sort by Menu. See screenshot below.
![image](https://user-images.githubusercontent.com/5908630/92466047-2db09a80-f1d8-11ea-9820-1d026f4b64b7.png)

**Comment by Rkareko** [comment]
Resolved by https://github.com/OpenSRP/opensrp-client-reveal/pull/1002

**Comment by samkanga** [comment]
Closing this ticket as it is a duplicate.
