### ISSUE TITLE
RVL-1143 - Plans created in operational areas that have structures do not have those structures with tasks available

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1005]
1. Create a plan in an existing operation area that has structures (eg BVBD test site 2)
2. Select the plan in the Android hamburger menu
3. A pop-up is displayed : 'THere are no structures mapped to this operation area' 
4. Expected berahviour: Existing structures are shown with a yellow dot (task in 'ready' state)

**Comment by craigappl** [comment]
We couldn't reproduce this and need Pierre to confirm this is still the case.

**Comment by Rkareko** [comment]
Issue marked ad `DONE` on [jira](https://smartregister.atlassian.net/browse/RVL-1143)
