### ISSUE TITLE
RVl-1142- Case-triggered plan does not include the 'Detect Case' task on Android

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1006]
- [ ] Case-triggered plans need to have a task to identify the Index Case, and there should be a 'Detect Case' button available on the list view of the Android UI.

**Comment by Rkareko** [comment]
Resolved by https://github.com/onaio/canopy/issues/1468

**Comment by samkanga** [comment]
@Rkareko @Wambere I will re-open this ticket since we are still having challenges with the case confirmation tasks. A case in point is for the plan [here](https://web.reveal-th-preview.smartregister.org/plans/update/0ce7fb86-8eae-48b7-9696-8edb4c36060e) where:

- [ ] The classification details on the list view return an error. i.e when a use clicks on the view button. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/93472084-e3789900-f8fc-11ea-9cc9-ca24eb470825.png)
 The expectation is that clicking the view should load the Case Classification Details page as shown on the screenshot below:
