### ISSUE TITLE
RVl-1148 - Some pre-dropped structures have "failed to get family details" error message

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1009]
**Operational Area**: Thailand test site BVBD 2
**Plan**: Dynamic-FI-2020-09-08_TASKS

1. Select operational area (refer above)
2. Select plan (refer above)
3. Wait for structures to load
4. Click on a pink structure

User is met with an error message, "**failed to get family details**"

**Comment by Rkareko** [comment]
@Naima-Bashir Please verify this is fixed

**Comment by Naima-Bashir** [comment]
This has passed QA. Closing this
