### ISSUE TITLE
THAI-The app crashes when one tries to login RVL-1155

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1013]
5.2.7
Thaiuser3/Amani123
Login to the app
Observe the error that is shown: "Youve been logged as you account has been removed from the accounts manager"
Try to login again and observe the app crash
NOTE: Even if the account has been removed; it should not crash the app. Rather inform the user of the status and ask them to login with another account
![image](https://user-images.githubusercontent.com/61143692/93001717-d3963900-f539-11ea-8b4d-8e13bfba3e1d.png)

**Comment by samkanga** [comment]
This is resolved.
