### ISSUE TITLE
Flaky sync - when adding a structure to an offline map RVL-1166

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1015]
When trying to sync a new structure added to an offline map, the sync fails.
Steps to recreate:
1. Download an offline map
2. Turn Wi-Fi off
3. Add a structure to the map
4. Register Head of Household details
5. Complete the testing task for Head of Household (outcome positive diagnosis)
6. Turn Wi-Fi on
7. Open hamburger menu from map view
8. Try and sync
Toast message that Sync Complete but in the hamburger menu "Device data not synced" is displayed

**Comment by Naima-Bashir** [comment]
cc @Rkareko @samkanga

**Comment by Naima-Bashir** [comment]
I've tested this. I am stuck at the sync section.
It's been syncing for a while now.
cc @Rkareko @samkanga

**Comment by Naima-Bashir** [comment]
sync is complete. It said sync complete but the red shows device data not synced.
![image](https://user-images.githubusercontent.com/61143692/93380127-7e269880-f867-11ea-9636-cd8f6e29bd50.png)

**Comment by samkanga** [comment]
This is resolved.
