### ISSUE TITLE
THAI-  The drill down on the plan moves from the hamburger menu to the map section(floating over the map)

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1017]
Login to 5.2.8 using bvbd_mhealth/Test123
Wait for the OA to sync then select a plan eg Thailand test site BVBD 1 as the OA and Dynamic FI-2020-09-14-VR-test 2
Observe how you are no longer on the hambruger menu page while drilling down to select this plan.
See image below.
![image](https://user-images.githubusercontent.com/61143692/93104813-00bc2600-f6b7-11ea-8956-697b6216f973.png)
![image](https://user-images.githubusercontent.com/61143692/93104872-10d40580-f6b7-11ea-8cb8-bb7608e1e079.png)

**Comment by samkanga** [comment]
@Naima-Bashir I will close this ticket for now and we can re-open it in the event we are able to replicate it.
