### ISSUE TITLE
One cannot download a plan for Test Village 1

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1020]
this was raised by matt. I will try to replicate it as well.
@samkanga @Rkareko

**Comment by samkanga** [comment]
@Naima-Bashir I have confirmed this is now working. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/93854094-cd345980-fcbd-11ea-912c-25e670ccd05e.png)

I will go ahead and close it.
