### ISSUE TITLE
App crashes when one tries to login

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1022]
I tried to login using 5.2.9
Thaiuser3/Amani123
the app crashed immediately both times  tried to login
cc @samkanga @Rkareko

**Comment by Naima-Bashir** [comment]
Cleared my cache and was able to login. The app should not crash either way.

**Comment by samkanga** [comment]
@Naima-Bashir please share a status update on this issue.
