### ISSUE TITLE
Newly created plans are not saved

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-reveal#1024]
**Expected Behavior**

When a user creates a new action plan and saves it, the plan should be added to the list of plans under `Manage action plans` and/or `Patient investigation and source of infection activity`.

**Actual Behavior**
Currently, newly created plans are not being saved.

**Comment by ciremusyoka** [comment]
@moshthepitt @Rkareko the filter plans by user endpoint is not retrieving newly created plans. If you try to get the [superset-user](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/user/superset-user) plans no plans are retrived.

**Comment by ciremusyoka** [comment]
> @moshthepitt @Rkareko the filter plans by user endpoint is not retrieving newly created plans. If you try to get the [superset-user](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/user/superset-user) plans no plans are retrived.

Was wrong on this. The filter is for plans assigned to a user and not for the plans created by a particular user.

**Comment by moshthepitt** [comment]
@faith-mutua @ciremusyoka we had implemented a feature where plans are auto-filtered by the currently logged in user.  If you remove the user filter, are you able to see the "missing" plans?

**Comment by ciremusyoka** [comment]
> @faith-mutua @ciremusyoka we had implemented a feature where plans are auto-filtered by the currently logged in user. If you remove the user filter, are you able to see the "missing" plans?

Yes on removing the filter all plans are available.
