### ISSUE TITLE
RVL-1161 - New Plans showing up with grey structures

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1029]
- [ ] When a new plan is created, all structures (households, PAOT, Larval Sites, Mosquito sites) should have associated tasks and should be coloured, unless they have been explicitly deleted. Presently new plans are showing up with grey structures and no tasks for the above named list.

**Expected behaviour**: They should be allocated new tasks in 'Ready' state (yellow)

**Comment by craigappl** [comment]
Larval dipping sites, POAT etc are not coming through with tasks. It appears that these types of structures are being ignored.
