### ISSUE TITLE
RVL-1188 After logging in, or changing user, app suddenly changes from Thai to English version

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#1035]
Steps to reproduce    
  

1.  Install Thai Version
2.     Login with bvbd_test
3.     Log out.
4.     Log in with thaiuser1
5.     Accept the prompt to clear data
6.     App suddenly changes to English

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/94436271-ea2cc900-01a4-11eb-9361-ae56776d436f.png)
![image](https://user-images.githubusercontent.com/61143692/94436282-edc05000-01a4-11eb-866e-720b02f461e2.png)
@Rkareko @samkanga i've retested this. And i am stuck here. 
Atleast it doesn not change languages. Te second screenshot is from the english apk.

**Comment by Naima-Bashir** [comment]
retested this using bvbd_test. It works as expected. Apaart from the clear cache section: that is still in English
