### ISSUE TITLE
Thai APK not Loading plans for some of the Jurisdictions

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1041]
- Login to the Thai APK with BVBD_test
- Wait for the App to complete sync
- Navigate to the Thailand BVBD 2 Site
- Attempt to select the plan. The App gives a pop up as shown on the screenshot below and does not load the plan

![image](https://user-images.githubusercontent.com/5908630/93763379-04512f00-fc1a-11ea-8888-5197cf3312d4.png)

**Comment by Rkareko** [comment]
@samkanga the description talks about login using `bvbd_test` but the screenshot show the logged in user is `thaiuser3`. Please verify which user to use.

**Comment by samkanga** [comment]
I encountered the user with thaiuser 3 while testing the login with different accounts issue. Let me log in with bvbd_test and determine if the issue is still there.

**Comment by samkanga** [comment]
@Rkareko  its working with BVBD_test account. It could be a team assignment issue since BVBD_test is automatically done and Thaiuser 3 was a manual plan assignment which no longer exists. I will go ahead and close the ticket.
