### ISSUE TITLE
Editing Spray form from the form-filter window results in a duplicate Record  in 'Filled Forms'

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1055]
Steps to reproduce
- Log into the android apk.
- Add a structure and complete a HH spray form
- Go to the Forms Filled menu on the hamburger menu
- Filter by HH Form
- Select the spray form completed and edit any of the non Mop details on the form
- Save the form.

This results in creation of an additional HH Spray form on the Form Filled view. See sample screenshot below:

![image](https://user-images.githubusercontent.com/5908630/94652002-04c88480-0302-11eb-95e7-97f36a3a57a4.png)

**Comment by githengi** [comment]
Blocked, waiting for this feedback https://docs.google.com/spreadsheets/d/1AWJffkCrXdNCakMXLMJbyo45r3S3VeDcZWMa-vhgiJE/edit?disco=AAAAKRsUOrw

**Comment by samkanga** [comment]
@githengi the details for this ticket on the issue tracker sheet have changed and I have updated the ticket above accordingly. Please have a look.

**Comment by samkanga** [comment]
I will go ahead and close this ticket following the confirmation that is is resolved in version 5.3.3
