### ISSUE TITLE
Unable to Add structure outside of Operational Area

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1061]
Samsung Galaxy Tab A 2017, 
Android 9
Plan: Dynamic-IRS 2020-09-26UAT2
User: uat1/test

- Login
- select operation area ksh_44(2020) under Kabuku Zone
- tap on add structure,
-  pan to an area outside that operation area and not any of the other operation areas
- tap on save.

**Notification error:**
Operation areas called "other" for this HFCA doe not exist.............
Pressing okay does not allow saving of the structure.

**Current Behavior:**
Not able to add a structure outside any of the mapped operation areas.

Expected behavior:
Be able to add structure outside operation areas, its posible structures could be have been missed and not operation area (spray area) created around them.

**Comment by githengi** [comment]
This is because the Other OA was not defined the Zone as shown on the below screenshot

![image (4)](https://user-images.githubusercontent.com/25123762/94442431-a047e100-01ac-11eb-8851-1b1ec1943cff.png)

**Comment by samkanga** [comment]
Akros need to add the "Other" location. I will close this ticket.
