### ISSUE TITLE
Missing validation on Total Population Field under Verification Form

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1064]
Samsung Galaxy S 10+ 
Android 10
Plan: Dynamic-IRS 2020-09-26UAT2
User: uat1/test

- Open hamburger menu
- Select Other Forms
- Select "Enter Verification Form"
- Fill in the form; Make sure the total population is less than the 
- total number of pregnant woman, total number of children
- under 5 years, and total number of nets in use.
(Should not be able to save. An error message should display) 

![image](https://user-images.githubusercontent.com/5908630/94443390-c9b53c80-01ad-11eb-9e8a-d622ee5a9ce3.png)

**Comment by craigappl** [comment]
We need to change the order of the total population in order for this calculation logic to be fired correctly. So, we will be moving the total population question below the question about Total number of pregnant women and children under 5.

**Comment by Naima-Bashir** [comment]
this has passed qa. cc @samkanga
