### ISSUE TITLE
RVL-1227 Different views when opening a structure from map view

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1080]
We have a case on the Thailand apk, when a yellow structure is selected from the Map, it provides an option to register a household. However, when it is opened from the list view, it comes with household members.

OA: Thailand test site BVBD 3
Plan: A1- Thailand test site BVBD 3 - Pedro Test - 2020-09-29 - Site
Android version: 5.3.2

1. Search for "แจ็คทดสอบ" family in Map view
2. Click the yellow structure (family registration form appears with Household name pre-filled)
3. Exit structure and Map view
4. Open list view
5. Search for "แจ็คทดสอบ" and click the view tasks in yellow (family registration details appear)

Please refer to video [here](https://smartregister.atlassian.net/browse/RVL-1227) that illustrates the steps above.
For other structures this doesn't seem to be a problem so might be something weird with the enrollment for this particular structure?

**Comment by Rkareko** [comment]
@samkanga @craigappl 
1. This structure has a `RACD Register Family` task with `READY` status for the plan `A1- Thailand test site BVBD 3 - Pedro Test - 2020-09-29 - Site` plan
2. This structure also has a family registered under `Test Start Date` plan

How should this scenario be handled, do we allow registration of a new family on the strcuture under the 'A1- Thailand test site BVBD 3 - Pedro Test - 2020-09-29 - Site' plan

**Comment by samkanga** [comment]
@Rkareko not sure if this is a case that would be resolved through entity persistence as it seems the family registration task is completed in one plan and not in another. For purposes of resolution, I would propose we maintain the event that first completed the family registration task. @craigappl what are your thoughts here?

**Comment by craigappl** [comment]
This is a tough decision. I recommend that we allow the user to register a new family against that structure.

Here's my thinking:
1. We don't know when the family was registered under Test Start Date plan
2. The user could have archived the family in the A1- Thailand test site BVBD 3 plan. In that case, the old registration would be good for the old plan, but the new registration would need to be able to accommodate registering a new family.
3. The server side processes will create the correct task type for the structure based on the state of the server and at the time it was generated. There may be local changes that were not available in the server when the plan was generated. In this case, we would want the local changes to be persisted. If the user syncs, the Entity persistence work in the OpenSRP server should update the task.
4. I don't think the entity persistence work in the OpenSRP server accounts for archived families. That would be something we need to consider in the future.
