### ISSUE TITLE
Users on Namibia Production APK unable to login 

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1082]
- [ ] New users created for Namibia cannot log in. This includes the old user names e.g. **user1_nam** and the new accounts created e.g. **abet.nandirokwe** The accounts however were tested yesterday by the client and found to be working.

The account: user1_nam gives the error below:
![image](https://user-images.githubusercontent.com/5908630/95066221-c6203900-070a-11eb-9a59-0e01c40b6dc8.png)
 
abet.nandirokwe gives the error below:
![image](https://user-images.githubusercontent.com/5908630/95066391-01bb0300-070b-11eb-99d0-4d7c2cfc3189.png)

**Comment by Naima-Bashir** [comment]
Login to the namibia production : 

opensrp-reveal-5.3.4-rc2.apk
Login using:
user1_nam/Test123
or 
Petrina.Kawedha
Saveria.Kasamane
Eliaser.Enkali
Erastus.Amunime

Password Nambia1
Observe the login error
![image](https://user-images.githubusercontent.com/61143692/95079050-c3c7da00-071e-11eb-948d-4148caad25e6.png)
