### ISSUE TITLE
Random Behaviour on the color coding for the "Not Visited" Task 

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1097]
Log into the Thailand Local Production APK
User: bvbd_test
Location: Thailand Test site BVBD 2
Plan: A1 - Thailand test site BVBD 1 - Blair Waldorf - 2020-10-09 - Site

**Current Behaviour**
1. Go the task list and click on a "Not Visited"  task e.g. for HH House. The task appears in yellow.
![image](https://user-images.githubusercontent.com/5908630/95672190-6fea4480-0ba7-11eb-8276-83c5b7dd1eab.png)
2. Due to the bug on #1096 the blood screening window will open. Close the window and re-evaluate the task that was clicked.
3. There are moments when the "Not Visited" label changes from yellow to pink.
![image](https://user-images.githubusercontent.com/5908630/95672210-9314f400-0ba7-11eb-8d26-37a7c965d83b.png)
4. However, when one click away to other tasks and goes back to the task list, the pink goes back to yellow.

**Comment by samkanga** [comment]
@Rkareko this issue has been confirmed with a separate location and should be worked on. See additional details on the ticket [here](https://smartregister.atlassian.net/browse/RVL-1264). However, the linked ticket points to a plan in the production locations and should be investigated cautiously.

**Comment by Rkareko** [comment]
Linked to #https://github.com/onaio/canopy/issues/1566
