### ISSUE TITLE
No Data Transferred When OA selected during P2P Syn

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1099]
- [ ] On the Zambia APK version 5.3.4 when doing a P2P sync, the app provides an option to select the OA from which data is to be transferred between the syncing devices. However, the syn process is marked as successful but hsows that zero(0) files were transferred. A check on the receiving phone shows that no data s transferred. The expected behaviour is that data should be transferred based on the selected OA. It was however noted that when the parent of the OA is selected during the P2P sync, data is successfully transferred.

Related to https://github.com/OpenSRP/opensrp-client-core/issues/674

**Comment by Naima-Bashir** [comment]
Tested this on 5.3.8
using rk12 and mc12.
I was able to add structures on one device and successfully do the p2p sync
It showed that it transferred 167 records
cc @hmakandi @Rkareko
