### ISSUE TITLE
HH IRS records of structures transferred over P2P does not show in filled form view 

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1100]
- [ ] On the Zambia APK vesion 5.3.4, whereas data transfer between devices is successful when the parent OA is selected during the P2P sync, the completed HH Spray form does not reflect on the Forms Filled view of the receiving device. The structure against which the form was completed however shows up on the receiving device.

**Comment by Rkareko** [comment]
@samkanga @Naima-Bashir Could you confirm whether this is happening on the latest release https://github.com/OpenSRP/opensrp-client-reveal/releases/tag/v5.3.9-zambia . Note that by default only forms filled by the logged in user are displayed, to view forms for other users you need to allow viewing all events in the filter screen.
