### ISSUE TITLE
Red sync dot displayed even when sync completes after marking a new structure inactive while offline

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#1108]
An issue has been reported in Namibia where adding a new structure then subsequently marking it as inactive while offline leaves the task in an un-syncable state.

Steps to reproduce

1. Log into app and complete sync. Make sure that the sync status dot is green.
2. Turn off wifi or cellular network to ensure app is in offline mode
3. Add a new structure. 
4. Long press on the new structure and follow the process of marking a structure as inactive.
5. Turn on wifi/cellular and initiate sync.
6. After sync completes notice that the sync dot remains red and sync progress label indicates `Device data not synced`

**Comment by Naima-Bashir** [comment]
Tested this on: opensrp-reveal-5.3.7-rc1.apk
user1_nam
Followed the steps 
The red dot turned green after it finished synching
This has passed QA
cc @samkanga @Rkareko 
![image](https://user-images.githubusercontent.com/61143692/96228127-d1daed80-0f9d-11eb-9e6c-0d79ca3fe703.png)
![image](https://user-images.githubusercontent.com/61143692/96228144-d7d0ce80-0f9d-11eb-9e92-93293e20f497.png)
