### ISSUE TITLE
RVL-1281 Processing of records transferred over P2P taking to long to process

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-reveal#1124]
Samsung Galaxy Tab A Lite 2017 Android 9 -> Oppo A9 2020 Android 10 
Reveal: 5.3.7
Server: Stage

login to one device with one user and another with the other
capture some data on one ( I captured 4 structures on the Galaxy tab )
sync to the other tablet
the receiving device keeps flickering and processing 

**Current behavior:**
Received data processing is taking too long, for the Oppo A9, the screen was constantly flashing while this was happening ( 20 minutes ). Had to log out then back in for it to stop.
Then when i transferred from the A9 to the galaxy tap, and let it process without login out, the tablet has been processing for over 3hrs now.

**Comment by Naima-Bashir** [comment]
related to https://github.com/OpenSRP/opensrp-client-reveal/releases/download/v5.3.4-zambia/opensrp-reveal-release-5.3.4-zm-stage.apk

**Comment by Naima-Bashir** [comment]
Tested this on 5.3.8 
using rk12 and mc12. 
I was able to add structures on one device and successfully do the p2p sync
The structures are seen on the second deveice 
cc @hmakandi  @Rkareko
