### ISSUE TITLE
MACEPA Daily Summary Form and Team Leader DOS Form don't populate Zone

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#1139]
The Vectorlink implementation added Zones this year, but Macepa didn't. The Daily Summary form has a field called "Zones" which is populated based on the user's team assignment, looking at the zone level. Macepa doesn't have a zone level. As a result, the first field of the "Daily Summary Form" and "Team Leader DOS Form" ask for the user's zone, which is a dropdown with field label "Name of location". This is populated for VectorLink, but we don't have zones in Macepa. Right now, this field is not populated for the IRS or IRS Lite APKs.

IRS and IRS Lite APK versions 5.3.4

We need to make the following changes to the IRS and IRS Lite APKs:
- [ ] If we are within the MACEPA areas, populate the 'zone' field with the name of the 'district' (https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/java/org/smartregister/reveal/util/RevealJsonFormUtils.java#L525 and https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/java/org/smartregister/reveal/util/RevealJsonFormUtils.java#L541)
- [ ] That should then show up on the Daily Summary Form (https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/zambia_daily_summary.json#L55)
- [ ] That should then show up on the Team Leader DOS Form (https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/zambia_team_leader_dos.json#L55)

**Comment by craigappl** [comment]
Note that I am purposefully recommending that we populate the "zone" field differently for each implementation in the Android client so we don't have to change anything downstream in the ETL for the performance dashboards. I hope this is a good call.

**Comment by Rkareko** [comment]
@craigappl @samkanga For the full IRS should we be populating the `zone` field with `district` or the `rural health facility` names?

**Comment by craigappl** [comment]
The one above OA should be done for both.
Full IRS = Rural Health Facility
IRS Lite = District

**Comment by Naima-Bashir** [comment]
on opensrp-reveal-5.3.10-rc2-irs-stage.apk   this has passed QA 
It has also passed QA on opensrp-reveal-5.3.10-rc1-irs-lite-stage.apk
