### ISSUE TITLE
RVL-1280 - Include operational area code on IRS Lite

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1142]
Login to reveal's IRS Lite android App
Select a location and plan

**Current Behavior:**
No operational area codes showing on map view. See sample screen shot below:
![image](https://user-images.githubusercontent.com/5908630/97981227-01358b00-1de3-11eb-8346-b6a4f90fbdc4.png)

**Comment by Naima-Bashir** [comment]
on IRS LITE: cc @samkanga @Rkareko 
This has failed QA 
https://github.com/OpenSRP/opensrp-client-reveal/issues/1142
Because it shows hundred of OA codes. 
See image below
![image](https://user-images.githubusercontent.com/61143692/98338880-ec900780-201b-11eb-8a35-a1050ef6585c.png)

**Comment by Naima-Bashir** [comment]
opensrp-reveal-5.3.10-rc1-irs-lite-stage.apk
