### ISSUE TITLE
IRS Lite: Verification form - If structure was not visited, spray status question should be hiden

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1145]
How to reproduce on IRS Lite

1. Login to reveal
2. Select other forms, enter verifications form
3. Select no on Was this structure visited question.

**Current behavior:**
The questions on spray status, date of spray are still  present. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/98105401-00ffc300-1ea9-11eb-9410-929e1ac12702.png)

**Comment by Naima-Bashir** [comment]
This has passed QA.

**Comment by Naima-Bashir** [comment]
opensrp-reveal-5.3.10-rc1-irs-lite-stage.apk
This has also passed QA
