### ISSUE TITLE
IRS Lite: Verification form - remove second "Not sprayed" and "Not visited yet" responses on spray status question

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1146]
How to reproduce on IRS Lite

1. Login to reveal
2. Select other forms, enter verifications form
3. On the Spray status,  remove second "Not sprayed" and, the "Not visited yet" responses

**Current behavior:**
The questions on spray status, date of spray are still  present. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/98105720-6489f080-1ea9-11eb-88ee-3950720fd679.png)

**Comment by Naima-Bashir** [comment]
opensrp-reveal-5.3.10-rc1-irs-lite-stage.apk
This has passed QA
