### ISSUE TITLE
Zambia Full APK - Remove "Not Visited Yet" from Spray Status

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1147]
How to reproduce on IRS Lite

Login to reveal
Select other forms, enter verification form
On the Spray status, remove second "Not sprayed" and, the "Not visited yet" responses

Current behavior:
The option on spray status, reading "Not Visited Yet" should be removed.

**Comment by Naima-Bashir** [comment]
TESTED ON opensrp-reveal-5.3.10-rc2-irs-stage.apk
