### ISSUE TITLE
Update on Macepa  IRS HH Form

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1151]
For the Macepa IRS HH Form, the drop down in the questions below, should have an `other` option that should open a field with the label reading `Specify other health facility:` for both of the question below.

1. When you or someone in your household is ill with a fever, which facility do you seek care from?
2. In which health facility catchment area do you reside?

**Comment by Rkareko** [comment]
@samkanga this is because the list of <Health Facilities> does not have `other` specified in the server settings.
The fix is to add the following to the list of health facilities per district 
`{
      "code": "Other",
      "name": "Other"
      }`

**Comment by samkanga** [comment]
@Rkareko What does the addition of `other` impact? If its safe to make the addition, we can go ahead and include it.
