### ISSUE TITLE
Implement Mosquito Collection point Cardview

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#116]
- [x] Implement Mosquito Collection point Cardview when a mosquito collection point is clicked whose task business status is not `'Not Visited'`

![image](https://user-images.githubusercontent.com/25123762/53864206-f1a5e380-3ffc-11e9-9d81-7df96f3afd22.png)

- [ ] The card view at the top has a component to collapse the cardview
- [x] The card view title is ` Mosquito collection point` and has icon at the left  
- [x] There is a horizontal line separator below the title
- [x] The card view displays Status, Setup date and follow up date
- [x] The card view at the bottom has a button `Record Mosquito collection` that when clicked opens the Mosquito collection point form

**Comment by rowo** [comment]
![mosquito-collection](https://user-images.githubusercontent.com/1584163/54209862-dfbcb880-44b4-11e9-8dbf-33e21e5c7478.png)
