### ISSUE TITLE
RVL-1340 - Missing Tasks for some Locations on Production IRS Lite

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1163]
- [ ] Some of the locations under the IRS Lite production app are not returning tasks. An example of an affected user is klm1. See details below. Additional users are accessible [here](https://smartregister.atlassian.net/browse/RVL-1340).

**Zambia Production server
Andriod version 9.0.0
Reveal version 5.3.9**

**Steps to reproduce**

1. Login to Reveal App
2. Tap on Hamburger menu
3. Select OA - Mawaya RHC
4. Select plan - MACEPA IRS LITE Southern Live Plan
5. Tap on map

Outcome:
There are locations on the map that have a grey boundary showing they are no tasks generated for these. See sample screenshot below:
![image](https://user-images.githubusercontent.com/5908630/99379544-e4687f80-28d9-11eb-897c-4647fef0f1ec.png)

**Comment by Rkareko** [comment]
@samkanga the 3 areas missing tasks `mawa_2_st`, `mawa_1_st`, `mawa_20_st` were created on `2020-11-13` while the rest were created on `2020-11-06`.  If the plan was created before `2020-11-13`, this would explain why they are missing tasks

**Comment by samkanga** [comment]
@Rkareko I see. Is this because the tasks generation is triggered by the plan creation(activation)? In which case, if an area is added after a plan is created, then tasks for such an area will not be generated. However, if a new plan is created, then the area will have tasks.
