### ISSUE TITLE
Update SOP cascade for new users in Gwembe

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1164]
Linked to https://smartregister.atlassian.net/browse/RVL-1344

- Update user cascade for gwembe district.
- Previous users the cascade was assigned to are not working after testing, and they have been replaced after the SOP drop down was already made.
- Update the SOPs cascade for the users highlighted cyan/blue on the sheet [here](https://docs.google.com/spreadsheets/d/1IObUolyxKHgP8T_eBh7NGmqaPDItN_fJ1hMQCLDEQx8/edit?ts=5f8d7719&pli=1#gid=886024292).
- The ones highlighted blue under gwembe, and everything for Nkeyema, Kaoma, Luampa, Mulobezi district which is row 126 going down
- The Siavonga cascade has completely changed, hence will need to be updated/re created

**Comment by Rkareko** [comment]
@samkanga This has been done.

**Comment by samkanga** [comment]
@Rkareko thank you.
