### ISSUE TITLE
RVL-1287 Create Senegal forms

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#1169]
Jira ticket https://smartregister.atlassian.net/browse/RVL-1287

**Description**

Create Senegal forms using the Senegal IRS Forms 2020 sheet

The forms should be based of the Zambia IRS forms as indicated here with  changes below.

IRS HH FORM

Structure type & eligibility: 

For the question “Why is this Non-Residential structure eligible?”, choices should only have "Boarding school", "Ward Clinic", "Lodge", "Toilet with roof", "Other".

Under structure details add these questions:

    Is this the structure in which the head of the compound lives?  Must have “yes” and “no”. if yes, show question 2 below. If No skip to question 3.

    Please enter the name of the head of the compound.

    If the head of the compound does not live in this structure, who is the head of this structure? 

 

DAILY SUMMARY FORM

Under  summaryDetails include the date question below. Which should not allow picking of future dates.

    What is the date that this data collection happened?

**Comment by Naima-Bashir** [comment]
@Rkareko @samkanga 
Tested this on version: opensrp-reveal-5.3.12-rc1-sen.apk
1. The following have passed QA: 
a) Why is this Non-Residential structure eligible?”, choices should only have "Boarding school", "Ward Clinic", "Lodge", "Toilet with roof", "Other". **PASSED QA**
![image](https://user-images.githubusercontent.com/61143692/100273491-eda6bb80-2f6d-11eb-9ae9-3e66c11539e1.png)

b) Is this the structure in which the head of the compound lives?  Must have “yes” and “no”. if yes, show question 2 below. If No skip to question 3.

Please enter the name of the head of the compound.  **PASSED QA**
![image](https://user-images.githubusercontent.com/61143692/100273607-16c74c00-2f6e-11eb-99b1-6a78664f5892.png)

c) If the head of the compound does not live in this structure, who is the head of this structure?    **PASSED QA**
![image](https://user-images.githubusercontent.com/61143692/100273674-31012a00-2f6e-11eb-9627-acd43ba5a01b.png)


d) DAILY SUMMARY FORM  --What is the date that this data collection happened?   
This has passed QA, however using my Samsung A5, the words  "collection happened" have been cropped, see image below
![image](https://user-images.githubusercontent.com/61143692/100273777-60b03200-2f6e-11eb-88c0-45bb02844d97.png)
