### ISSUE TITLE
Implement Larval breeding point Cardview

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#117]
- [x] Implement larval dipping point Cardview when a larval dipping point is clicked whose task business status is not `'Not Visited'`

![image](https://user-images.githubusercontent.com/25123762/53864863-a55ba300-3ffe-11e9-886f-3c05280fb894.png)

- [x] The card view at the top has a component to collapse the cardview
- [x] The card view title is ` Mosquito bleeding point` and has icon at the left  
- [x] There is a horizontal line separator below the title
- [x] The card view displays identified date date and Larvacide up date
- [x] The card view at the bottom has a button `Record Larval dipping` that when clicked opens the Larval dipping  form

**Comment by rowo** [comment]
![breeding](https://user-images.githubusercontent.com/1584163/54209851-da5f6e00-44b4-11e9-9c4f-034af6954b96.png)
