### ISSUE TITLE
RVL - 1172 - Fixes on Family list view

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1173]
Edit the family list view as follows:

- [x] Enable edit for registration information that was previously captured
- [x] Add ability to archive a family member

Below is a screenshot of the list view:
![image](https://user-images.githubusercontent.com/5908630/100241433-bb349880-2f44-11eb-8bcd-1cdeb804b773.png)

**Comment by githengi** [comment]
@Kanga is all the information supposed to be updated  e.g Can the questions about eligibility be removed from edit form so that if this is not eligible one archives and the  registers again
