### ISSUE TITLE
RVL-1173 - Build two new forms for supervisors 

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1175]
Build two new forms for supervisors in the ‘Other Forms’ View as per the details provided on [this](https://smartregister.atlassian.net/browse/RVL-1173) jira ticket. The form names are:

- [ ] CDD Supervisor checklist
- [ ] HFW Supervisor checklist

**Comment by githengi** [comment]
Data dictionary on https://smartregister.atlassian.net/browse/RVL-1173
