### ISSUE TITLE
RVL-1360 - Senegal Form - Senegal form Changes

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1178]
**IRS HH FORM**

1. What type of non-residential structure is this? If the answer is “No structure here” or “Not “habitable” the form should end. No need to ask the structure eligibility question.
2. Is this the structure in which the head of the compound lives?  and the other subsequent questions should only be asked if the structure is eligible. (Relevance = eligibility = "Eligible") .
3. Remove the “Name of structure household head” field.
4. Change “IRS Number” to “Structure Identification Number”.
5. Change “Was this structure sprayed” to “Were any rooms in this structure sprayed”.
6. Add new field:  “Main reason why some ELIGIBLE rooms in this structure were not sprayed?” which these select options = "Refused", "Locked", "Sick", "Food Storage", "Didn't want to clear", "Other". Condition: Show If Number of ELIGIBLE rooms > Number of rooms sprayed in TOTAL 

**DAILY SUMMARY FORM**

Move the question What is the date that this data collection happened?  to the top above name of location. Its should be the first question on the daily summary form.

**Comment by Naima-Bashir** [comment]
@Rkareko @samkanga 
Add new field: “Main reason why some ELIGIBLE rooms in this structure were not sprayed?” which these select options = "Refused", "Locked", "Sick", "Food Storage", "Didn't want to clear", "Other". Condition: Show If Number of ELIGIBLE rooms > Number of rooms sprayed in TOTAL
1. The order is different 
2. These two are missing: Food storage  and  Didn't want to clear 
![image](https://user-images.githubusercontent.com/61143692/100466948-c8878980-30e2-11eb-8088-4228faadc66c.png)

**Comment by Naima-Bashir** [comment]
This has passed QA
