### ISSUE TITLE
RVL-1357 - Add ZM-KLM-SOP-1 Siakachoma Gildens to the list of SOPs for the user klm1 for Kalomo district Reveal Lite.

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1180]
Assign the user highlighted blue [here](https://docs.google.com/spreadsheets/d/1xmb9GmT48cylmlrHpbEKNjy-dbw6g9ltE_TIHkTFWlk/edit#gid=2089986059) on row 3 to the user klm1.
**SOP details**: ZM-KLM-SOP-1 Siakachoma Gildens
**User:** klm

Request:
Currently this user has two SOP as shown below. The request is to add the SOP above to the list of SOPs for this user.
![image](https://user-images.githubusercontent.com/5908630/100450137-2eb1e380-30c6-11eb-8420-811a174f7577.png)

**Comment by Rkareko** [comment]
@samkanga The server settings have been updated
