### ISSUE TITLE
Implement the Add Point Form

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#12]
When a user touches the + button in the bottom left corner, they need to be directed to the Add Structure Form.

![irs - add form](https://user-images.githubusercontent.com/6067053/48239139-9c293500-e382-11e8-8523-7288d71129fb.png)

### Immediately Upon opening this screen:

- [x] The location services are checked to see if they are enabled.
- [x] If they are enabled, the map fragment zooms to the user's current location (Zoom level to be determined)
- [x] If not enabled, the user is prompted to enable location services
- [x] If they choose to enable location services, the map automatically scrolls to their location
- [ ] ERROR Case: If they tried to enable the location services, but they were not responsive within a certain period of time, the user should be able to scroll to a point to drop a pin.
- [x] If users choose not to enable location services, they need  the ability to pinch and zoom to an appropriate location to add the point. When they save the form, the point gets added.

### Structure of this page:
Top Bar:
- [x] The top bar displays the title "Register New Structure"
- [x] The top bar displays an X in the top left corner to cancel the operation
- [x] The top bar displays the word "SAVE" in the top right corner to save the event
GeoWidget Fragment:

Map:
- [x] The map should display in a fragment and the user should be able to interact with it so that they can pinch and zoom around. (See functionality above)
- [x] The coordinates need to be stored from the map (latitude, longitude, altitude)
- [x] The accuracy should be recorded based on the GPS location services or the zoom level on the map.

Form:

- [x] The form includes both required structure data and business data
- [x] The form as you see in the screenshot is not accurate. Please refer to the [data dictionary](https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=0)

After SAVE Activities:
- [x] The location is added to the location table
- [x] A task is created based on the campaign template
- [ ] The user is redirected to the form to complete the task

**Comment by githengi** [comment]
- [ ] update from @craigappl  the map should be opened with bounds on the current operational area loaded, and should not focus on the user location

**Comment by craigappl** [comment]
@githengi I think the map should be opened to the current bounding box that's displayed when they hit the add point button. This will allow consistency for the user as they cross views.
