### ISSUE TITLE
Syncing snack bar prevents users from clicking any buttons underneath it

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1231]
https://smartregister.atlassian.net/browse/RVL-1449

**Problem**
The Syncing message is a snackbar and stays on the screen until sync is successful or sync fails
The snackbar (located at the bottom of the screen) hides any buttons underneath it and users are unable to click these hidden buttons. See sample screenshot below.
![image](https://user-images.githubusercontent.com/5908630/106996679-6e660d00-6792-11eb-8460-8cf444b54947.png)

**Potential solution**
Change the sync UI to be a toast message 

**Considerations**
- What are other potential solutions
- Could we reduce the snack bar and center it as has been done on other OpenSRP Apps. See sample below:
![image](https://user-images.githubusercontent.com/5908630/106998004-e6353700-6794-11eb-9a2b-fd270af99c8f.png)

**Comment by rowo** [comment]
Reading about snackbars on [materio.io](https://material.io/archive/guidelines/components/snackbars-toasts.html#) and [Android dev](https://developer.android.com/training/snackbar/showing) — the user should be able to swipe away the snackbars. Also, ideally the snackbar would push non scrollable elements like the one on the map the arrow points to.

A short term or easy solution might be making the button smaller — that seems okay. But I don't know if it will work on all devices like smaller screens.

**Comment by samkanga** [comment]
Thank you @rowo I will check with the client to determine their preference  on the different options.
'

**Comment by faidvd** [comment]
hey @samkanga. have we finalized the implementation for this?

**Comment by Rkareko** [comment]
@rowo cc @Naima-Bashir 
1. When we have the snackbar push up the items on the map the buttons at the top get cut off as shown on this image 
![map_moved_up](https://user-images.githubusercontent.com/47570855/107925169-2068ba80-6f85-11eb-80a4-077fa019928d.png)

2. We can have the contents on the bottom of the screen (button on the left and card views) be the only one moving up. However we are not able to do this for the `My Location` button (on the botom right section)  since this is part of the map view itself 

![my_location_hidden](https://user-images.githubusercontent.com/47570855/107925975-31fe9200-6f86-11eb-999e-b704e46bc19e.png)

3. We could have the sync bar appear above the buttons and the card views. However not sure the appearance would be acceptable

![syncbar_floating_above](https://user-images.githubusercontent.com/47570855/107926238-80ac2c00-6f86-11eb-9359-571932c989a3.png)
![snackbar_above_add_button](https://user-images.githubusercontent.com/47570855/107926241-8275ef80-6f86-11eb-85d4-233045f4a056.png)
 
Please advice on the way forward

**Comment by Naima-Bashir** [comment]
@rowo could you assist with providing some input on this. Thanks

**Comment by rowo** [comment]
Couple of findings with Richard:
- currently the snackbar is not user dismissible
- currently the syncing bar persists for the entire time the app is syncing
- currently, there is a sync progress bar in the drawer menu
  ![sync_progress](https://user-images.githubusercontent.com/1584163/108156496-c95f0480-70ae-11eb-8379-2fad1be5854d.png)
- adding a "dismiss" button to the snackbar to make it dismissible would be easy to do

**Comment by Rkareko** [comment]
@rowo  Yes, the syncing snackbar appears any time syncing is in progress, whether or the sync is manually triggered or not.

**Comment by rowo** [comment]
@Rkareko ok thanks. So definitely should be dismissible and doesn't need to be any more persistent than a regular Material snack bar IMO. Any feedback on the changes I'm suggesting?

**Comment by Rkareko** [comment]
@rowo cc @Naima-Bashir 
1. Yes we can add a "Dismiss" button to the snackbar and make it dismissible by any other action on the screen
2. Yes we can push the `add point` button and the card views above the snackbar. It's not possible to have the snackbar be covered by the card views
3. We can add a snackbar for showing that syncing is complete

**Comment by rowo** [comment]
@Rkareko thanks. That seems good then. Number 2 really doesn't even feel completely necessary if it takes too much time to figure out — if number 1 is done. Number 3 should be have the same — just a quick notice that can get dismissed quickly/easily. The actual "Dismiss" button is just to remind people it's easy to remove in case we've done snackbars that don't behave like this elsewhere in the app.

![image](https://user-images.githubusercontent.com/1584163/108890295-648a3980-75db-11eb-87cb-dd25762d46dd.png)

**Comment by Naima-Bashir** [comment]
Just an update on this issue. I has been blocked. Please don't spend anymore time on it until Varshana gets updates from her side.

**Comment by Naima-Bashir** [comment]
FEEDBACK FROM VARHSANA: cc @Rkareko @rowo 

I think we would actually prefer the number 2 option as it means that anything currently hidden by the snack bar is pushed up. This will not be a change from the current UX and users are able to continue with their work

With number 1, I think there’s the risk that a user will think clicking “dismiss“ means that they are cancelling the sync thats in progress when all it does is it hides the message. Also we’ll need to train and update users on how to use it.

For number 3, don’t we already have a toast message for sync complete? What will the difference be here?

We’ll check with Pedro and the other teams using Reveal (e.g. Namibia) and get back to you by EOD but here’s some initial thoughts

**Comment by rowo** [comment]
@Naima-Bashir We can reword the "dismiss" label, but it's not maintainable product-wise to have a persistent snack bar appear whenever the app is syncing that pushes certain items up and not others throughout wherever the user navigates. No matter what, this snackbar needs to be dismissible — whether the label says "Dismiss" or not, or whether there is no button at all. This aspect is not debatable and not up to the client.

**Comment by rowo** [comment]
@Naima-Bashir Do you need any follow up? We can use the word "Hide" perhaps.

**Comment by Naima-Bashir** [comment]
@samkanga cc

**Comment by samkanga** [comment]
@Rkareko @faidvd the client has resolved to work with the toast messages in place of the snack bar. In addition the client want the automatic sync to run once every 12 hours. The following are the requirements in more details:
- [ ] Syncing started…: Triggered when either the user taps sync or automatic sync
- [ ] Sync complete: If sync is successfully completed (and the sync dot turns green)
- [ ] Sync failed: If sync is unsuccessful (and the sync dot remains red)
- [ ] Sync failed. Check your internet connection: When there is no internet connection
- [ ] Can change automatic sync to try every 12 hours

**Comment by rowo** [comment]
@samkanga so does this mean it's going to be quick toasts just at key events (and the message won't appear for the entire time of sync?)

**Comment by samkanga** [comment]
@rowo that is correct.

**Comment by samkanga** [comment]
@rowo @mberg from a product perspective, should we have this update on all the reveal apks or just maintain it to Thailand? This more to do with consistency and the ease of maintenance to the code.

**Comment by rowo** [comment]
@samkanga Can you share a screen capture or screen grab of what was implemented?

**Comment by rowo** [comment]
@samkanga From the look of the video it looks like the sync message appears the entire time the syncing occurs... it might just get reset over and over again. Is that correct? From [the comment](https://github.com/OpenSRP/opensrp-client-reveal/issues/1231#issuecomment-809162679) it seemed more like the toast told you events like "Syncing started" and "Syncing complete". It would never show you "Syncing..."

https://user-images.githubusercontent.com/1584163/114124677-f7004700-98c2-11eb-8814-b33f37b7f55f.mp4

**Comment by samkanga** [comment]
@rowo you are right that the implementation on the video missed some of the requirements set [here](https://github.com/OpenSRP/opensrp-client-reveal/issues/1231#issuecomment-809162679).  We shall review this and revert. The bit on the 12 hourly sync was specific to Thailand and not to other implementations. Other implementations will maintain the 15min sync interval when online. cc: @Rkareko, @faidvd, @Naima-Bashir

**Comment by Rkareko** [comment]
> @Rkareko @faidvd the client has resolved to work with the toast messages in place of the snack bar. In addition the client want the automatic sync to run once every 12 hours. The following are the requirements in more details:
> 
> * [ ]  Syncing started…: Triggered when either the user taps sync or automatic sync
> * [ ]  Sync complete: If sync is successfully completed (and the sync dot turns green)
> * [ ]  Sync failed: If sync is unsuccessful (and the sync dot remains red)
> * [ ]  Sync failed. Check your internet connection: When there is no internet connection
> * [ ]  Can change automatic sync to try every 12 hours

@faidvd could you have a look at this comment.

**Comment by faidvd** [comment]
@rowo @samkanga @Rkareko updated the implementation to incorporate the above comments. Does this look okay?

https://user-images.githubusercontent.com/69460329/114369648-08ce3c80-9b98-11eb-9860-0961c5bd901e.mp4

**Comment by samkanga** [comment]
Thank you @faidvd. Has the status `Sync failed. Check your internet connection` been implemented and are you able to show a sample of how this would look like on the toast?

**Comment by faidvd** [comment]
Sure @samkanga
![image](https://user-images.githubusercontent.com/69460329/114376465-15a25e80-9b9f-11eb-8113-3b1a41719efb.png)

**Comment by samkanga** [comment]
@rowo please share your thoughts on the updated sync statuses.

**Comment by rowo** [comment]
@samkanga @faidvd looks good thanks. 

@samkanga For the user-initiated one we're looking at it definitely is okay. However, I wonder about showing this every 15 minutes no matter where you are in the app. I don't think it's best practice to show async/background style refresh updates — they usually are integrated into actions like navigating to new sections, though it is a special case here because it might take a while. Question — if there is no connectivity, will the app try to do a sync?

**Comment by samkanga** [comment]
@rowo the App checks for a connection before it attempts an automatic sync. When if finds no connection, it does not initiate the automated sync. cc: @Rkareko

**Comment by rowo** [comment]
So some conclusions from a slack chat cc: @samkanga 
- This is good to go from the perspective of an issue about changing from a snack bar to a 2 to 3 second toast prompted by key events and not showing up for the entire syncing duration
- On the question of a product across OpenSRP or even across Reveal implementations:
  - this is also an okay approach if happens during auto and manual syncs and the auto syncs occur 3-5 times a day. However, if auto sync happens more often, for example at least 2-3 times every time a user opens the app, then it seems like no toast is necessary and it can just happen in the background. The manual sync should still have the toast in this case. 
  - If I were forced to pick one way to implement this across Reveal, I guess I'd say we should show it.

**Comment by Naima-Bashir** [comment]
QA updates: 
1. The sync failed at the bottom is shown when I turn off my internet. It does not indicate that I should check my connection
2. After I turn on my internet again, it shows that the Device Data synched (even though it wasn't complete as I had turned off my internet)
3. Sync started is shown- PASSED QA
4. Sync complete is shown- PASSED QA

**Comment by Naima-Bashir** [comment]
The Thai apk has english and thai in the messages.  For example, it starts with Sync started in english. 
When I turn of my internet, the sync failed is in Thai
@faidvd

**Comment by Rkareko** [comment]
> The Thai apk has english and thai in the messages. For example, it starts with Sync started in english.
> When I turn of my internet, the sync failed is in Thai
> The sync complete is also in Thai
> @faidvd

@Naima-Bashir `Sync started` is a new string that does not have translations yet. This will be updated when the translation is available

**Comment by faidvd** [comment]
> QA updates:
> 
>     1. The sync failed at the bottom is shown when I turn off my internet. It does not indicate that I should check my connection
> 
>     2. After I turn on my internet again, it shows that the Device Data synched (even though it wasn't complete as I had turned off my internet)
> 
>     3. Sync started is shown- PASSED QA
> 
>     4. Sync complete is shown- PASSED QA
>        @faidvd @Rkareko
@Naima-Bashir 
Regarding 2: Was there any unsynced data on device before you pressed synced? And how long did you wait before turning off the internet?
If the call to push unsynced data is succeeded before you disconnected internet it will show "Device Data synched".
As "Device Data Synced" indicates there is no unsynced record in local db. So it is possible to have this, even if overall sync fails
