### ISSUE TITLE
Inform users if their offline map download was incomplete or successful- 1453

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1232]
Corresponding JIRA ticket is https://smartregister.atlassian.net/browse/RVL-1453

**Problem**
Users are unable to tell if their downloaded map is the complete map or partial map. 

**Suggested solution**
- Users are shown if the map has successfully downloaded or not
- Users are able to retry download for incomplete maps
- Users are not confused on how to retry the download for incomplete maps

In the attached document, options 1 or 3 might be more favourable. Option 2 seems quite confusing with the actions in different places.

Below are proposed options building from the current feature.
![image](https://user-images.githubusercontent.com/5908630/106994605-30ff8080-678e-11eb-8538-2ad9a2c37a15.png)

**Option 1:**
![image](https://user-images.githubusercontent.com/5908630/106994872-b4b96d00-678e-11eb-836e-5d095664c652.png)

**Option 2**
![image](https://user-images.githubusercontent.com/5908630/106995027-09f57e80-678f-11eb-8dbd-d6a84de19280.png)

**Option 3**
![image](https://user-images.githubusercontent.com/5908630/106995210-77a1aa80-678f-11eb-99c0-b2b8e8facadd.png)

**Considerations**
How difficult is each option technically?

**Comment by rowo** [comment]
@samkanga So are you saying incomplete maps are kept and also usable — with the constrain that areas of the map are blacked out? During the download process, is there some notification that something wasn't fully downloaded?

Also, how do maps work again in terms of selecting them to use? 

Otherwise, Option 1 looks good.

**Comment by Rkareko** [comment]
@rowo @samkanga Yes incomplete maps are kept and are also usable with the parts that have not yet been downloaded appearing as black patches.

In case there was an error in the download process an error message is displayed using a toast

Maps are downloaded for each OA (operational area) the user has access to. So to choose which map to use the user just selects which OA they want to view on the Map View from the Operational Area selector on the drawer menu

**Comment by Naima-Bashir** [comment]
Updates from Varshana: no further blockers I think we are ready for dev on this ticket. Will move to selected for development.

**Comment by Naima-Bashir** [comment]
@Rkareko could you update on this? If it can be worked on or if it still needs more info

**Comment by Naima-Bashir** [comment]
Debug apk will be made for the QA

**Comment by Naima-Bashir** [comment]
Naima is currently testing it. cc @samkanga

**Comment by Naima-Bashir** [comment]
This has passed QA. 
![image](https://user-images.githubusercontent.com/61143692/109612630-15935580-7b41-11eb-93bc-452063b31949.png)  
![image](https://user-images.githubusercontent.com/61143692/109612672-2348db00-7b41-11eb-8020-d84fa5f84d02.png)
