### ISSUE TITLE
END FUND Kenya - Create CDD Supervisor Daily Summary form

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1242]
Jira ticket: https://smartregister.atlassian.net/browse/RVL-1431 

The apk should have the ability to select locations at levels higher than the structure level e.g. at ward level

- This form should be accessed by tapping on the ward boundary ( something similar to how the IRS lite works).
- A user should be able to enter multiple form instances by tapping on the same ward. So the user should be able to tap on the ward and capture data for a CDD for a specific date and save, then tab on the same ward again to enter data for the same CDD for a different date or for another CDD for a specific date.

The form fields and logic can be accessed [here](https://docs.google.com/spreadsheets/d/1J5IsHWSznKEdT82bxGY6Yzfwi43su34mkX0w8bkAeRU/edit#gid=1800425965).

- [x] Create form
- [x] Wire it up to be accessible when a ward is clicked

**Comment by Naima-Bashir** [comment]
This has failed QA:
Do not show "treated_male_1-4" and "treated_female_1-4" if "ntd_treated" = SCH.
If SCH is selcted, It shows  male 1-4  and female 1-4  
![image](https://user-images.githubusercontent.com/61143692/109826448-da317d80-7c4b-11eb-8563-4d9b5a568ccb.png)
