### ISSUE TITLE
End Fund Kenya - Create Tablet Accountability form for MDA

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1244]
JIRA LINK: https://smartregister.atlassian.net/browse/RVL-1417 
This form should be accessed from the Other forms view.

The form fields and logic are on the tablet accountability form sheet on the data dictionary [here](https://docs.google.com/spreadsheets/d/1J5IsHWSznKEdT82bxGY6Yzfwi43su34mkX0w8bkAeRU/edit#gid=1083089419).

- [x] Create Form
- [x] Wire it up to Other forms section

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/109817805-625f5500-7c43-11eb-817e-2b20bcb6e625.png)



CDD name is missing @Rkareko
