### ISSUE TITLE
End Fund Kenya- Create Dynamic MDA Lite plan type

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1248]
Link to jira: https://smartregister.atlassian.net/browse/RVL-1458

As a program manager, I would like to create MDA lite plans via the web UI.

**Comment by Rkareko** [comment]
Here is a sample plan. @githengi Please verify the validity of the sample.
@Naima-Bashir please verify the text used for the plan title, name intervention type, task code, action, goal etc

`{
    "identifier": "6b485d4b-1043-40ed-ab8a-c64d24045ada",
    "version": "1",
    "name": "MDA-Lite-Test-1-2021-02-18",
    "title": "MDA-Lite  Test 1 2021-02-18",
    "status": "active",
    "date": "2021-02-18",
    "effectivePeriod": {
      "start": "2021-02-18",
      "end": "2021-04-18"
    },
    "useContext": [
      {
        "code": "interventionType",
        "valueCodableConcept": "MDA-Lite"
      },
      {
        "code": "taskGenerationStatus",
        "valueCodableConcept": "internal"
      }
    ],
    "jurisdiction": [
      {
        "code": "ce13e7f4-6926-4be0-9117-519bd1cc4bb2"
      }
      ],
    "serverVersion": 1600361461193,
    "goal": [
      {
        "id": "CDD_Supervision",
        "description": "Submit one CDD Supervisor Daily Summary form per operational area per day",
        "priority": "medium-priority",
        "target": [
          {
            "measure": "Percent of forms submitted",
            "detail": {
              "detailQuantity": {
                "value": 100,
                "comparator": ">=",
                "unit": "Percent"
              }
            },
            "due": "2021-04-18"
          }
        ]
      }
    ],
    "action": [
      {
        "identifier": "3ef7e2b8-1a11-4a5f-8454-93babb0ae641",
        "prefix": 1,
        "title": "Submit CDD Supervisor Daily Summary form",
        "description": "Visit each operational area and submit one CDD Supervisor Daily Summary form",
        "code": "CDD Supervision",
        "timingPeriod": {
          "start": "2021-02-18",
          "end": "2021-04-18"
        },
        "reason": "Routine",
        "goalId": "CDD_Supervision",
        "subjectCodableConcept": {
          "text": "Location"
        },
        "trigger": [
          {
            "type": "named-event",
            "name": "plan-activation"
          }
        ],
        "condition": [
          {
            "kind": "applicability",
            "expression": {
              "description": "Structure type does not exist",
              "expression": "$this.is(FHIR.QuestionnaireResponse) or $this.type.where(id='locationType').exists().not()"
            }
          }
        ],
        "definitionUri": "cdd_Supervision_form.json",
        "type": "create"
      }
    ],
    "experimental": false
  }`

**Comment by lindagcaba** [comment]
"definitionUri": "community_drug_distributor_supervisor_daily_summary_form.json"

**Comment by Naima-Bashir** [comment]
to test this please create a new user and a new plan (use the template on the ticket but generate a new identifier)
This will test whether task generation is working

**Comment by Naima-Bashir** [comment]
1. Created plan through Postman: bbaf9674-e381-45f1-94d1-23bd373bc88e
2. MDA-Lite-Test-QA-1-2021-03-03 
3.
