### ISSUE TITLE
Users must be able to enter data for the same location multiple times.

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#1251]
Related JIRA tickere https://smartregister.atlassian.net/browse/RVL-1420

**Description** 
As a data collector, I would like to be able to enter data multiple time for the same location. i.e. user taps on the the location, form pops up, enters data for one CDD for a specific date and saves. The user use can again tap on the same location, and enter data for another CDD for that specific date.

**Comment by Rkareko** [comment]
This ticket is related to https://github.com/OpenSRP/opensrp-client-reveal/issues/1242

**Comment by lindagcaba** [comment]
this has been implemented as part of #1242 and we can close it.
