### ISSUE TITLE
End Fund Kenya - Add dialog to change task complete status for CDD Supervisor Daily Summary form 

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#1261]
We need a dialog that will be used to change the `task_complete` status since this value is not editable in the filled forms view.
This dialog will be triggered via a long press on the ward

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/109816111-6d18ea80-7c41-11eb-9840-3a296ecb1a83.png)
![image](https://user-images.githubusercontent.com/61143692/109818648-44462480-7c44-11eb-955a-197aa88b703c.png)
