### ISSUE TITLE
Delete jurisdiction-metadata-structures settings entries where the key field is a higher level jurisdiction

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1263]
In regards to this issue: https://github.com/onaio/canopy/issues/1841 (Please read @moshthepitt comments) https://smartregister.atlassian.net/browse/RVL-1455

The next step would be to get an OpenSRP engineer to help delete jurisdiction-metadata-structures settings entries where the key field is a higher level jurisdiction i.e. not a leaf node i.e. a jurisdiction that has children

**Comment by Naima-Bashir** [comment]
@githengi Who should I assign this to cc @Rkareko

**Comment by Naima-Bashir** [comment]
7fcd3811-ef21-451e-b407-db635e976246  

https://web.reveal-zm.smartregister.org/intervention/irs-lite/report/19e55ac1-06c4-4c71-9e93-2905d54d093a/7fcd3811-ef21-451e-b407-db635e976246  
@Rkareko

**Comment by Naima-Bashir** [comment]
@Rkareko Any progress on this?

**Comment by Rkareko** [comment]
@moshthepitt  cc @Naima-Bashir are the jurisdictions on this page what you would define as leaf nodes and thus the corresponding jurisdiction-metadata-structures settings should not be deleted?

**Comment by moshthepitt** [comment]
@Rkareko yes.  Keep the counts for these ones and remove the ones for the parents and grandparents of the jurisdictions on that page.

**Comment by Rkareko** [comment]
@moshthepitt cc @Naima-Bashir @samkanga I have deleted the Jurisdiction Metadata for Zambia MACEPA 2020 id 7fcd3811-ef21-451e-b407-db635e976246

**Comment by Rkareko** [comment]
@samkanga Please verify completion of this ticket

**Comment by samkanga** [comment]
@Rkareko I confirm this is now completed. I will go ahead and close the ticket.
