### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1267]
Linked to: https://github.com/OpenSRP/opensrp-client-reveal/issues/1232
APK: opensrp-reveal-5.3.21-rc2-th-preview

![image](https://user-images.githubusercontent.com/61143692/109613458-3b6d2a00-7b42-11eb-89a2-86966af17bba.png)

**Comment by faidvd** [comment]
@Naima-Bashir the translations for these are not available

**Comment by samkanga** [comment]
@faidvd here you go `downloading` = กำลังดาวน์โหลด
