### ISSUE TITLE
Sync failed issues

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#1270]
login to the End Fund app:  
opensrp-reveal-5.3.21-rc1-ke-stage.apk
use testona/testona

Wait for the sync to finish and observe the error showed below even after the green Data synced to device is shown 

![image](https://user-images.githubusercontent.com/61143692/109814956-24acfd00-7c40-11eb-8f2b-a682942133cf.png)

**Comment by faidvd** [comment]
@Naima-Bashir this was an issue with user roles, I have assigned the user the needed roles and it should be working now.
