### ISSUE TITLE
Add document config support for family register forms

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#1284]
Currently document configurability does not work for Family registration and Family member registration forms.

**Comment by Naima-Bashir** [comment]
Make some changes on the family register form and upload it.
Wait for android to sync and observe if the changes are shown?
Return the changes back to default

**Comment by Naima-Bashir** [comment]
Family register has passed QA for the english apk. The thai apk I am not sure since it's in thai.
