### ISSUE TITLE
child roster issues with upload and task creation [fire]

### ISSUE THREAD

**Issue by isabelcshaw** [opensrp/opensrp-client-reveal#1312]
**Uploaded child roster csv do not appear in list**
When a csv is uploaded, there is a success messages, but then the csv does not show in the list of uploaded files. Is it possible there is a limit to the number that can be shown? @ciremusyoka 
Video of interaction here: https://www.loom.com/share/ed8ea95643d147b7aafb12ecf908d383

**Children uploaded from roster do not have Record Dose task on mobile**
The children that show up in the app who were added via the roster upload do not have dispense tasks 
@rkodev it seems like it is possible that this may be due to the active plan - but we need to confirm that this isn't actually a bug. (CHAI does know to upload the csv before creating the plan) 
[Screenshot in tab "42" here](https://docs.google.com/spreadsheets/d/1faWPud-PXUtDnuMWgYbTQsRyfsXauMFSgVRvLNzctKw/edit?ts=5eecdaf9&pli=1#gid=1132492467) 

We need to share responses with the client on both of these items by EOD today (even if it is not conclusive) as they are blocking planned testing with the MoH

**Comment by rkodev** [comment]
@isabelcshaw  I've seen the upload attempt video but I cant seem to find anything on the server that records the uploaded file, or an attempted upload of a file by that name. I've been able to upload a new file with the same name without any issues. The only recorded error message for an upload attempt on the 19th was a failed upload attempt by an excel file.  
It would be helpful to get the exact file and retry the upload. But I 'm not able to reproduce this error after several attempts. @ciremusyoka  is it possible that the front end might be reporting a failed upload as successful erroneously?

**Comment by ciremusyoka** [comment]
@isabelcshaw please provide the file you were trying to update

**Comment by isabelcshaw** [comment]
Update: @rkodev attempted the upload and was successful. But now the web is not showing any updates later than March 23rd (the csv was shared with us first on the 24th). Here is the screenshot of the successful upload: 
![image (5)](https://user-images.githubusercontent.com/12836913/112839719-5a80ae00-9053-11eb-9f17-831384e246b1.png)

At least three people from CHAI have had the client upload issue. For one of them, this was the computer information shared: **Windows 10, Google Chrome, Version 89.0.4389.90**

**Comment by ciremusyoka** [comment]
@rkodev have tried uploading a file (Eswatini_Child_Roaster_win.csv) using Window OS and it is not showing up. A while back we had same problem with form config files uploaded using Window OS not being saved on the server. 
I think all the files not showing up were uploaded from a Windows OS machine.

**Comment by rkodev** [comment]
@ciremusyoka do you have any suggestions on how this was fixed?

**Comment by ciremusyoka** [comment]
> @ciremusyoka do you have any suggestions on how this was fixed?

@rkodev the fix was done on the server side, @Rkareko can give more information about it.

**Comment by Rkareko** [comment]
@rkodev cc @ciremusyoka This is the issue we had with the config files https://github.com/OpenSRP/opensrp-server-web/issues/688

**Comment by rkodev** [comment]
@isabelcshaw @samkanga This issue is a result of the windows OS, CSV file upload from windows OS is chanding the `text/csv` file type and replacing it with `application/vnd.ms-excel` i.e an Excel file type. We have added support to override this issue
