### ISSUE TITLE
Dynamic tasking: Include ability to have multiple tasks for any structure

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1315]
- [ ] Include ability to have multiple tasks for any structure (currently only residential structures can have multiple tasks).

More details on this ticket can be found [here](https://smartregister.atlassian.net/browse/RVL-1496).

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/114345268-166ccd80-9b6a-11eb-9c93-3e8547ccf4ba.png)
![image](https://user-images.githubusercontent.com/61143692/114345291-1c62ae80-9b6a-11eb-85ff-9beb4419366f.png)
![image](https://user-images.githubusercontent.com/61143692/114345314-25538000-9b6a-11eb-9488-d7e5e1cb0e44.png)

**Comment by Naima-Bashir** [comment]
HOW TO TEST: 
1. Generate a plan()
2. Register a new structure(residential, Mosquito, larval or PAOT)
2. After that, click on the new structure and observe if it has multiple tasks like residential structure has 


Part1: 
1. Create a residential structure and register the household
2. Click on the structure and test to see if Larval breeding site has been created. 
QA RESULTS: 
This part has passed QA. Larval breeding site is shown in the tasks for residential structure. 
See image below. 
![image](https://user-images.githubusercontent.com/61143692/117103152-7843e000-ad82-11eb-867c-cfb874577f14.png)


SOME QA FEEDBACK: 
I created 4 different types of structures using the plan Dynamic tasking HH 
Apart from mosquito collection Point, the other two(Larval Dipping and POAT) gave me an error that said "Loading failed, this structure does not have a task assigned to it for the plan Thailand test side BVBD2"
See image below.
![Uploading image.png…]()

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/117104134-46cc1400-ad84-11eb-887c-e163d0a3005b.png)

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/117104197-64997900-ad84-11eb-9267-b86c4973e42c.png)
For old larval dipping structures, (existing ones), it actually shows two asks, Household registration and Larval breeding site

**Comment by Naima-Bashir** [comment]
The new plan does not have actions for POAT and Larval Dipping. It doesn't create tasks against them

**Comment by Naima-Bashir** [comment]
When one clicks on some larval breeding sites in the list views:
One can see three tasks generated:
1. Larval breeding site
2. Distribute bednet
3. Household registration 
![image](https://user-images.githubusercontent.com/61143692/117105094-01104b00-ad86-11eb-97be-9cebe084fa13.png)

**Comment by Naima-Bashir** [comment]
Questions: 
1. Why some larval breeding structures have:
a) Newly created larval bredding site, give a loading failed error
b) Some existing larval breeding sites have two tasks showing(Register family and Record Dipping)
c) Some existing larval breeding sites have three tasks showing(Register family and Record Dipping and Record Distribution)

Answers: 

For 1a, it depends on the plan, does it have the larval dipping action? 

FOR B A and C
If the plan allows  for creation of family registration task in a larval dipping structure, that is why you have (1b)

And if the family is registered, then you get the record distribution (1c)

**Comment by Naima-Bashir** [comment]
QA UPDATES: 
TEST: To see if other structures besides residential can have multiple tasks. 
STEPS: 
1. Create a plan and add this to the specific structure required: `"expression": "$this.is(FHIR.Location) or (questionnaire = 'Register_Structure' and ($this.item.where(linkId='structureType').answer.value ='Mosquito Collection Point') or $this.item.where(linkId='structureType').answer.value ='Potential Area of Transmission'))"
}
https://reveal-stage.smartregister.org/opensrp/rest/plans/b72e33df-e608-59de-b9bd-d94366eae87c
2. After you make the changes and publish it(it should be on draft when making changes then active when setting it to PUT)
3. Login to android and select the plan
4. Create a structure eg PAOT. 
5. Wait for the sync to happen
6. Go to list view
7. Click on view tasks
8. Observe if the tasks included are the ones you had added eg Mosquito collection point. 

THIS HAS PASSED QA. 
![image](https://user-images.githubusercontent.com/61143692/117293094-a3f5c180-ae79-11eb-89d6-f1215b7ab267.png)
 cc @samkanga @Rkareko @faidvd
