### ISSUE TITLE
Update the Download Progress Behaviour for Incomplete Maps

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1319]
When the download of an offline Map is interrupted, the map shows under the `downloaded` tab as incomplete. The map provides an option to select it and progress the download through the green download button. The client desires that the progression of an incomplete offline plan to be displayed similar to the download process when the map is downloading for the first time. To achieve this we need:

- [ ] to remove the downloading label on the right 
- [ ] to remove the date below the OA name.
- [ ] to show the `downloading` progress under the OA name, similar to what shows when a map is downloading for the first time

**Comment by Naima-Bashir** [comment]
my QA findings 
![image](https://user-images.githubusercontent.com/61143692/114676008-87021e80-9d11-11eb-80ba-3bea9be02c33.png)
