### ISSUE TITLE
End Fund - Populate baseEntityValue for the Tablet accountability Form

### ISSUE THREAD

**Issue by lindagcaba** [OpenSRP/opensrp-client-reveal#1321]
Linked to https://smartregister.atlassian.net/browse/RVL-1502

The baseEntityId value on the Tablet accountability Form, should be populated using the identifier for the ward name in the Select the Location ( ward ) question whose value is found in the location obs field.

The question Select the Location ( ward ) should also be mandatory on the tablet accountability form.

**Comment by Naima-Bashir** [comment]
This is not a UI related @samkanga @lindagcaba 
To test this: 
1. Go to the backend and check that the entity id corresponds to the location id that was selected eg Luganga/ Vihiga.
