### ISSUE TITLE
Change Edit Date Format Under the Household Task Tab

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1349]
On the task tab in the household view in the Thailand APK, the task edit date format is given as mm/dd. The client would like this changed to the format dd/mm/yy. See sample present screenshot below.
![image](https://user-images.githubusercontent.com/5908630/114052538-cbfffe00-9896-11eb-8b4e-858c7a9aa4c5.png)

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/114678284-c5004200-9d13-11eb-8a2f-bfb1c1936943.png)
