### ISSUE TITLE
Thailand: Make Date Field on Mosquito Collection Form Mandatory

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1350]
**Current Behavior:**
When a user fills the mosquito collection point form, they are supposed to choose a status and fills in the date and then after save the form. a User is allowed to save the form with empty date (without filling in the collection date)

**Desired Behavior**
When a user fills the mosquito collection point form, they should not be allowed to save the form with empty date. The date field on the form should be mandatory.

Below is a screenshot of the form:
![image](https://user-images.githubusercontent.com/5908630/114131425-44a0a200-990b-11eb-9e88-ce0dbcd0de74.png)

**Comment by LZRS** [comment]
Editing the mosquito collection form field `trap_start` to have 

> "v_required": {
            "value": true,
             "err": "Please specify the last updated date"
        }
would fix this

**Comment by Rkareko** [comment]
This can be done using form configurability
