### ISSUE TITLE
Thailand: Ensure only Whole Numbers are captured in Net Distribution Form

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1353]
The Mosquito Net Distribution form on the Thailand APK presently allows for Decimals to be captured. See screenshot below. Update the form to only accept whole numbers for all fields.
![image](https://user-images.githubusercontent.com/5908630/114158782-c43f6880-992d-11eb-838b-756c6bb9015a.png)

**Comment by Rkareko** [comment]
@faidvd Check whether this can be done using the Form Configuration functionality. 
This would be done by confirming that the fix for this issue can be made by updating the bednet distribution form and that no code changes are required.

**Comment by faidvd** [comment]
@samkanga @Rkareko Checked this, this can be done using Form Configuration.
I have made the changes needed in the thailand forms.

**Comment by Rkareko** [comment]
This can be done using form configurability
