### ISSUE TITLE
Create Reveal 5.3.25 Release

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1386]
create a github release with apks for the following environment

- [x] Thailand preview both english and thai apks
- [x] Thailand production both english and thai apks
- [x] Zambia both stage and production apks
- [x] Namibia production apks
- [x] Namibia stage apks

For each apk test the following 

- [x] You are able to login
- [x] Sync completes succesfully
- [x] The map loads correctly
- [x] Do a high level testing of the tickets on that release
- [x] For the Thai apks make sure strings are translated

**Comment by LZRS** [comment]
Testing done using emulator for Pixel 2, android version 9

**Comment by LZRS** [comment]
https://github.com/OpenSRP/opensrp-client-reveal/releases/tag/v5.3.25
