### ISSUE TITLE
User logged off when waiting for entities from a previous plan to sync in their new plan

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1389]
RVL- https://smartregister.atlassian.net/browse/RVL-1578
Instance: staging

Bug:
1. Create a FI Plan A, for operational area test site 2 and activate plan
2. On the Android device 1 (whilst offline), register 1 structure, 1 head of household, 1 household member
3. Create a new FI Plan B for operational area test site 2 and activate plan
4. On a new device (Android device 2), log-in and select Plan B
5. On Android device 1, turn internet connectivity on for the Android device and sync data from plan A
6. On Android device 2, sync device
7. See error: Account disabled
![image](https://user-images.githubusercontent.com/61143692/116062502-a17eb500-a68c-11eb-863d-78a2c2636c77.png)

**Comment by Naima-Bashir** [comment]
Tested this on RC3- 6.0.0 
I used two devices and followed the steps. 
At first I logged in using naimatest- it gave the error
However when I used ams1, it did not give the error. 
Closing this bug, but i'll keep and eye out for it.
cc @Rkareko @LZRS @samkanga

**Comment by Naima-Bashir** [comment]
Both @madrinekariuki and I were testing the app, it closed once we saved a new residential structure. 
We were logged in using Ams1 @Rkareko 
When I logged back in again and clicked on the newly registered structure, I got a fetch family failed error

**Comment by madrinekariuki** [comment]
this has been tested with :
APK V6.0.0RC5
android devices 
device 1:  android 11
device 2:  6.0.1
user: ams1

 STEPS

Created a dynamic FI plan (Test A) for operational area test site 2 and activated plan
Downloaded offline maps and switched off data. for device 1
On the device 1  (whilst offline), registered 1 structure, 1 head of household, 1 household member
Created a new dynamic  FI Plan  (Test B) for operational area test site 2 and activate plan
On a new device (Android device 2), logged-in and selected Plan Test B
On Android device 1, turn internet connectivity on for the Android device and sync data from plan Test A
On Android device 2, sync device

observations:
i was able to create the plans successfully
both devices synced well
data was visible from both devices and could select the plan i wanted.
no error observed.
