### ISSUE TITLE
Support Thailand Location Hierachy

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#139]
Support Thailand Location hierarchy. 
The Hierarchy has Country-> Province -> District-> Canton-> Village -> Operational area

- [x] Display this hierarchy in the Operational area chooser

- [x] Display Village or Canton instead of Facility in the Hamburger menu.

@Craig please specify if Village or Canton should be displayed in the Hamburger menu where the facility was being displayed

![image](https://user-images.githubusercontent.com/25123762/55943014-61d40480-5c4e-11e9-820e-39456859a5e2.png)

**Comment by craigappl** [comment]
We should use canton, which is subdistrict and Village.
