### ISSUE TITLE
Tag new clients with location Id

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1399]
Currently when a client is registered, the record is not tagged with the location Id.

- [ ] When adding a client, tag it with the current Operational area as the location id

Part of the fix for https://github.com/opensrp/opensrp-server-web/issues/812

**Comment by LZRS** [comment]
use `https://reveal-th-preview.smartregister.org/opensrp/rest/client/search?name=mayo` replacing `name=mayo` with name of the family member added

**Comment by Naima-Bashir** [comment]
Just tested with the family i had added 
https://reveal-th-preview.smartregister.org/opensrp/rest/client/search?name=location 

},
"locationId": "333af57d-ad31-46d2-8d28-0c81dd306333",
"_id": "6640f6fd-64ad-4383-be1c-5b166ef1c7f9",
"_rev": "v1"  

The location id is present cc @Rkareko @LZRS @samkanga

**Comment by Naima-Bashir** [comment]
To test, add a new family member through the apk,
and then confirm through response from this endpoint the clients location_id field is set, and is not empty
https://reveal-th-preview.smartregister.org/opensrp/rest/client/searchByCriteria?orderByFieldName=date_edited&orderByType=desc&pageSize=10&clientType=clients&providerId=ams1
For the last part, in the url providerId=ams1 you can the ams1 part to the user you're using for testing

**Comment by madrinekariuki** [comment]
Tested this on:
V5.3.26 th-en local
 v5.3.26 thai-en preview 
v5.3.26 th-preview 
v5.3.26 th-local

results. 
For v5.3.26 th-en apk  local the location ID is not showing.

for the  v5.3.26 th-en preview apk  the location ID is showing.
for the  v5.3.26 th preview apk  the location ID is showing
for the  v5.3.26 th-local apk  the location ID is showing

Steps:
-Click on a registered family(use one that you registered yourself)
-add a new family member 
-sync the details.
-check on below urls to confirm if the location ID shows
for thai local APKs use:
      https://servermhealth.ddc.moph.go.th/opensrp/rest/client/search?name=mayo (change the last part "mayo" to the name of the family member).

for thai preview APKs use:
    https://reveal-th-preview.smartregister.org/opensrp/rest/client/search?name=ben((change the last part "ben" to the name of the family member).

screenshots.
thai local
![image](https://user-images.githubusercontent.com/84722169/124599587-812e5c00-de6e-11eb-8024-01fa75acc48c.png)

thai preview. and the other 3 apks that show the location ID
![image](https://user-images.githubusercontent.com/84722169/124599650-930fff00-de6e-11eb-9e54-f9deaeb9b68a.png)
