### ISSUE TITLE
Implement the card view when a point is touched

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#14]
When a single point is touched a single card is displayed if the structure has been visited.
![irs - sprayed point tapped](https://user-images.githubusercontent.com/6067053/48240540-faa4e200-e387-11e8-8268-700adc63c64e.png)

Function:
- [x] The Add Point button slides up to accommodate the card
- [x] The card includes a down arrow on the top of it that closes the card if tapped
- [ ] The layout and variables in the card needs to be defined in a template.
- [x] The blue text CHANGE SPRAY STATUS is defined by intervention type and kicks off a different workflows depending on the campaign that is defined. In the case of IRS, it will open an edit spray status form.
- [x] (Note this ticket is what changes the color of the tapped point https://github.com/onaio/kujaku/issues/189)

Business Logic:
- [x] The card view is displayed following the business logic defined in https://github.com/OpenSRP/opensrp-client-reveal/issues/13
- [x] The underlying properties (spray status, name, date, etc) are the result of a query from the OpenSRP application. They are passed into the GeoWidget when it's loaded.
- [x] A user can touch another point and it will display the properties related to that card. If the user touches a point that doesn't fit the displayCard business logic, it will close the card and run the new business logic. (i.e. if a user is looking at a green point and they touch a yellow point, it will close the card and open a spray form)

**Comment by craigappl** [comment]
Craig needs to talk with Derek P and Akros to identify exactly what information shows up in the card.

**Comment by githengi** [comment]
@craigappl what is meant by 

> The layout and variables in the card needs to be defined in a template.

**Comment by craigappl** [comment]
> @craigappl what is meant by
> 
> > The layout and variables in the card needs to be defined in a template.

We will push this to a future version of Reveal.

**Comment by craigappl** [comment]
@rowo , Sam and I have reviewed the fields in the spray card and realized we need to add a few fields to the card.
Remove: Craig Cranberry's House
Keep:
1) Spray Status:
Add:
2) Reason: (If Spray Status = "Not Sprayed" and display notSprayedReasonOther if notSprayedReason = Other)
3) Property Type: 
4) Date:
5) User:
6) Family Head Name:

We are thinking about reducing the text size to be able to display all 6 fields in a list. Is this alright, or should we make the card larger or add a vertical scroll bar?

**Comment by rowo** [comment]
Talked to Craig a bit on Slack. Seems like the goal is to just have this screen and no others which means we can't truncate the long free text fields like "not sprayed reason" and "family head name". Therefore, I propose we set a max card height to support two lines for the reason and one for the family head then switch to vertical scrolling. To aid with squeezing the content, we can also switch to an icon + field value relationship rather than field label/variable name + value. I will put a screen in the next day.

**Comment by githengi** [comment]
Thanks @rowo this looks good

**Comment by craigappl** [comment]
@vincent-karuri and FYI @rowo
Here's what we need in the card for the black "Not Sprayable" points
- Text color should be Black in the header Not Sprayable
- The structure icon should be populated from the properties.type
- The date should be the same as should the username who assessed the structure
