### ISSUE TITLE
Dynamic Tasking bug

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1404]
Relates to 
https://github.com/opensrp/opensrp-client-reveal/issues/1315
HOW TO TEST:

Generate a plan(https://web.reveal-stage.smartregister.org/plans/update/b72e33df-e608-59de-b9bd-d94366eae87c)
Register a new structure( PAOT)
After that, click on the new structure and observe if it has multiple tasks like residential structure has.

BUG:
The errors i'm getting are two:

1. On map view, when I click on a newly created POAT, it says Fetch family failed
2. On list view when I search for the plan and click on the NOT VISITED section, it shows Form not found.
![image](https://user-images.githubusercontent.com/61143692/117132729-e9e45400-adab-11eb-9f86-2cf16165c172.png)
![image](https://user-images.githubusercontent.com/61143692/117132740-ecdf4480-adab-11eb-9f0c-b2d4bf8c3b35.png)
The video is shared on the slack reveal frontend channel

**Comment by faidvd** [comment]
https://web.reveal-stage.smartregister.org/plans/update/b72e33df-e608-59de-b9bd-d94366eae87c
The plan has wrong form name for PAOT definition Uri
![image](https://user-images.githubusercontent.com/69460329/117142481-2f634a00-adc9-11eb-9c30-65cd62bcdc0b.png)
The definition Uri should be `paot.json`

**Comment by Naima-Bashir** [comment]
1. I edited the plan with the correct spelling-this means that the error about the PAOT form showing form not found is not there anymore(one can create a PAOT structure and fill in the details.) I will therefore close the bug about that.
2. However, the dynamic tasking test of creating a structure and seeing multiple tasks has still failed. This is because I created PAOT structures and filled in the status, it did not show the tasks- all it shows is the NOT VISITED task where one fills the status.
3. Therefore that has failed QA.
4. Let me know if you need help with this issue
