### ISSUE TITLE
NTD: Children added via CSV aren't showing on android

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1424]
I created a new user ntd11
Added a CSV plan with about 9 kids
Created anew plan - CSV https://web.reveal-stage.smartregister.org/plans/update/85460292-4f41-56bb-a61c-a4d7f7fbde7b
Logged into android
The list were not showing

**Comment by rkodev** [comment]
@Naima-Bashir This an error resulting from the users.

Schools must be paired with the correct location ID. Reference this issue for the correct school_id / location_id combination
https://github.com/OpenSRP/opensrp-client-reveal/issues/1271#issuecomment-789798803

The list of downloaded children from the web CSV selector only uses the school id to select the children.

The app syncs via location_id, i.e the parent location of the school, assigning the school the wrong location, therefore, impedes the app from downloading the children

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/119472920-558a6300-bd53-11eb-9990-239c47d03684.png)
Here it is: https://web.reveal-stage.smartregister.org/clients

**Comment by Naima-Bashir** [comment]
closing this
