### ISSUE TITLE
"Error Occurred" Message when saving "Edit MDA" 

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1425]
Children have `Record Dose` tasks associated with them. When a `Record Dose` task is saved, a user can edit the same from the child's profile by selecting the 3 dots to the right corner of the child's profile page on the android app. There is an option marked `Edit MDA`. Edits are taking place successfully. However, there is a toast message that is showing that reads `Error occurred` that is likely to alarm a user that needs to be corrected. A video on this has been provided [here](https://onaio.slack.com/archives/C022500UH6J/p1621932963010600).

**Comment by rkodev** [comment]
@samkanga Can we close this issue as it's associated with an older version of app

**Comment by samkanga** [comment]
Yes. I will go ahead and close it.
