### ISSUE TITLE
NTD: Task generation failing at first then working the second time

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1429]
1. Log-in to Reveal with ntd11/Amani123
2. Select Lomahasha
3. Add a new child
BUG: The task isn't generated for the new child 
![image](https://user-images.githubusercontent.com/61143692/119664393-f5232080-be3b-11eb-96aa-faf79d584e36.png)

**Comment by Rkareko** [comment]
@Naima-Bashir The task was not generated since the `Sync 75` is above 18 years

**Comment by Naima-Bashir** [comment]
Verify that a RECORD DOSE is generated for all children below 18
