### ISSUE TITLE
Evaluate Android 5.1.1 support for Reveal

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#145]
We need to identify a minimum supported version for Reveal. Currently, Namibia and Botswana use Android 5.1 (API 22). We need to figure out if Reveal should support that. If so, we need to test against that version.

**Comment by githengi** [comment]
This is a duplicate to the already opened core Issue [https://github.com/OpenSRP/opensrp-client-core/issues/201](https://github.com/OpenSRP/opensrp-client-core/issues/201)
