### ISSUE TITLE
Form configuration changes (relevance files) not picked up by the Android client

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1458]
Changes to relevance files for family registration form is not picked up by the Android client.

Next steps

Scope if other forms are affected 

Related to https://github.com/opensrp/opensrp-client-reveal/issues/1357

**Comment by LZRS** [comment]
Steps to test

- Make changes to either `family_register_relevance.yml` or `family_member_relevance.yml` as described [here](https://github.com/opensrp/opensrp-client-reveal/issues/1357#issuecomment-855810720)
- Upload to [web](https://web.reveal-th-preview.smartregister.org/manifest/releases)
- Check that the relevance changes show in the client app, and occupation field shows whenever `date of birth` is selected above 18

**Comment by madrinekariuki** [comment]
for a user above 18 years when you select from the calendar or input their age, we are able to see the occupation field.
I tested by inputting family registration relevance forms from a previous version that was not updated against the current updated family registration relevance form .
-After Syncing data, the occupation field was showing for the updated family registration relevance forms unlike in the previous one.
see below screenshot.
![image](https://user-images.githubusercontent.com/84722169/123650075-eeb90780-d832-11eb-9ce2-320f62ca8c43.png)

**Comment by samkanga** [comment]
@LZRS please check the issue raised above on the Thai Preview APK.

**Comment by madrinekariuki** [comment]
I have re-tested fixes using the 2 shared APKs
th-en preview v5.3.26
th preview v5.3.26

 and below are the findings.
**th-en preview v5.3.26**
DOB  unknown
  -shows occupation if over 18
  -no occupation if he is under 18
  
DOB known
   -no occupation for under 18
   -shows occupation if over 18

**th preview v5.3.26**
DOB unknown
  occupation shows if over 18
  occupation does not show is under 18
  
DOB known
 -occupation does not show if under 18
 -occupation shows if over 18

@LZRS please confirm once the fixes have been merged with the local APKs so I can retest

find screenshots below.
![image](https://user-images.githubusercontent.com/84722169/125571951-051e992d-4f2b-42f9-87ff-3a6e94f453e5.png)
![image](https://user-images.githubusercontent.com/84722169/125571995-927b27cb-0c07-44d2-a00f-d369f8c40124.png)
