### ISSUE TITLE
Sync displaying more than 100%

### ISSUE THREAD

**Issue by LZRS** [opensrp/opensrp-client-reveal#1463]
Logging in as user `raitest`

using the 5.3.26 th preview apk

![image](https://user-images.githubusercontent.com/12814349/123255690-d0809e00-d4f8-11eb-89a5-c5d9fe5d788e.png)

**Comment by samkanga** [comment]
@LZRS please share the status in this ticket.

**Comment by LZRS** [comment]
@samkanga it has been hard to replicate this issue, and therefore work on it..

**Comment by LZRS** [comment]
looking into a general way to improve the syncing process, but currently still haven't figured out what's leading to the above 100% error..
