### ISSUE TITLE
Fix crash for dynamic tasking when adding structure

### ISSUE THREAD

**Issue by LZRS** [opensrp/opensrp-client-reveal#1464]
When adding structure, in dynamic tasking, the app crashes with error

> `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ibm/fhir/model/type/Canonical;`

**Comment by madrinekariuki** [comment]
@LZRS Please confirm if this is the same issue i have shared a video with you.
-After you login to the app
-When adding a new structure
-and a prompt asking you to "Allow Reveal to manage and make phone calls"
-when you click Allow the app crashes and you have to click on it and login in again...

I am unable to upload a video here but i have share it on slack.
![image](https://user-images.githubusercontent.com/84722169/124482846-61d1f900-ddb2-11eb-9c35-e8e01079cc5a.png)

**Comment by madrinekariuki** [comment]
@LZRS please note that this issue is also appearing in the Nam prod apk V5.2.26
android version used is 11.

**Comment by LZRS** [comment]
@madrinekariuki do you mean v5.3.26?

**Comment by madrinekariuki** [comment]
> @madrinekariuki do you mean v5.3.26?

yes.. apologies.

**Comment by LZRS** [comment]
For Namibia, the issue was resolved here https://github.com/opensrp/opensrp-client-reveal/pull/1476

**Comment by madrinekariuki** [comment]
@LZRS please confirm if this fix was deployed to the dynamic tasking APK
cc @samkanga

**Comment by LZRS** [comment]
[The crashes](https://console.firebase.google.com/u/0/project/opensrp-production/crashlytics/app/android:org.smartregister.reveal/issues/fc343400f8f2e486915f46653680c778?time=last-seven-days&sessionEventKey=60E7BD2E012F0001441EFF8771BD1E9E_1561217137554192613) happening when one accepts 'Allow this App to make phone calls', is due to the app trying to use `TelephonyManager.getDeviceId` which as described [`here`](https://developer.android.com/reference/android/telephony/TelephonyManager#getDeviceId(int)) was deprecated from android 8 and since android 10, crashes with `SecurityException` and requires privileged permission `READ_PRIVILEGED_PHONE_STATE`.

@Rkareko I'm not sure of its use from [native forms](https://github.com/opensrp/opensrp-client-native-form/blob/989a241f0ac51cc3b73f850676b7bcc8981b290f/android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/PropertyManager.java#L90) 
cc @samkanga @madrinekariuki

**Comment by Rkareko** [comment]
Crashlytics logs found [here](https://console.firebase.google.com/u/0/project/opensrp-production/crashlytics/app/android:org.smartregister.reveal/issues/fc343400f8f2e486915f46653680c778?time=last-seven-days&sessionEventKey=61076FD4031C00015445B73A15CE05DE_1570127447058545915)

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=15143, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.smartregister.reveal/org.smartregister.reveal.activity.RevealJsonFormActivity}: java.lang.SecurityException: getDeviceId: The user 10265 does not meet the requirements to access device identifiers.
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5384)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5425)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
```

**Comment by LZRS** [comment]
#1503

**Comment by madrinekariuki** [comment]
This has been tested on 
v5.3.26-rc6 th-en preview
v5.3.26-rc6 th preview

the app is no longer crashing when adding a structure.
