### ISSUE TITLE
The sync data button disappearing on the app and reappearing after log out login (this is intermittent). Thai

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1466]
The sync data button disappearing on the app and reappearing after log out/ login (this is intermittent) on  Thai local android

details of the apk used:
version 5.3.25
user bvbd_test

steps:
-install Thai [local](https://github.com/opensrp/opensrp-client-reveal/releases/download/v5.3.25/opensrp-reveal-release-5.3.25-th-en-local.apk) 
-login using above user.
- click on sync
- observe how the sync button disappears.
- log out and login
- observe how sync button reappears and disappears when you click on it.

to note
- This issue is intermittent. also the sync button reappears once sync is complete.

find below screenshot
![image](https://user-images.githubusercontent.com/84722169/123955678-8a24b680-d9b2-11eb-9fa1-9e5e617b4a7a.png)

@Rkareko

**Comment by samkanga** [comment]
@madrinekariuki could you retest this with the versino 5.3.26 apk and see if the issue recurs?

**Comment by madrinekariuki** [comment]
testing this on the v5.3.26-rc3

observations:
The sync button is present and not disappearing intermittently as it was. however there is a issue where the sync button is unresponsive and you have to keep clicking on it.

steps:
install the app
login to the app
try to click on the sync data button.
observe how the sync button is unresponsive sometimes.
user has to keep click on the sync button.
this is intermitent

**Comment by samkanga** [comment]
I will go ahead and close this ticket. Let's reopen it if the issue recurs.
