### ISSUE TITLE
Create Reveal 5.3.26 Release 

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1467]
create a github release with apks for the following environment

- [x] Thailand preview both english and thai apks
- [x] Thailand production both english and thai apks
- [x] Namibia production & stage apks

For each apk test the following 

- [x] You are able to login
- [x] Sync completes succesfully
- [x] The map loads correctly
- [x] Do a high level testing of the tickets on that release
- [x] For the Thai apks make sure strings are translated

**Comment by samkanga** [comment]
Namibia work has been descoped since they are not using reveal this year.
