### ISSUE TITLE
Enforce Round Off of Percentage Figures with .5 or above decimal.

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1474]
Presently on the NTD in-app dashboard, the andoroid client is casting the percentage value to integer and in the process doing a round down. This is then conflicting with the values on the dashboards where anything above `.5` is rounded up. We need the android client to be updated so that for any figures with a `.5` decimal or higher, the value should be rounded up to the next whole number.

**Comment by madrinekariuki** [comment]
tested this fix on V5.3.30
user: test99
planID: 844c6ec9-a18e-50ea-adde-117855d73c27
URL: https://web.reveal-stage.smartregister.org/intervention/mda-point/report/844c6ec9-a18e-50ea-adde-117855d73c27/74accedf-acd5-44f6-9685-fb2c25d509ce


total SACs was 16 and MMA coverage was 7.. so the MMA% is coming to 43.75%
when you round this the value is 44%
This is what shows on the android and on the web.
screenshots below
![image](https://user-images.githubusercontent.com/84722169/125400857-14114e00-e3bb-11eb-8854-38a8ba74195b.png)
![image](https://user-images.githubusercontent.com/84722169/125400867-17a4d500-e3bb-11eb-82c9-e3f2801d9171.png)


this has passed QA.
