### ISSUE TITLE
In app dashboard calculations not factoring in kids who are 18 but below 19

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1479]
Related to issue [Ewatini NTD](https://docs.google.com/spreadsheets/d/1faWPud-PXUtDnuMWgYbTQsRyfsXauMFSgVRvLNzctKw/edit?ts=5eecdaf9&pli=1#gid=0) issue 87

All calculations concerning SACs for the in app dashboards should include kids less than 19 years

**Comment by madrinekariuki** [comment]
This has been tested using v5..3.30.rc2 apk
user test101
plan ID: 6f6c69b5-7db3-50cb-9feb-e9595e9428ab
plan: [here](https://web.reveal-stage.smartregister.org/intervention/mda-point/child-report/6f6c69b5-7db3-50cb-9feb-e9595e9428ab/4b32d48a-6f11-4419-87f3-7b778a08a438).

steps;
-Added 12 kids via web 
-range of kids was 10 kids were (5 - <19) years
                              2 kids were >19 years
-synced 
-tasks were generated for all the kids <19s
-SAC data calculation in the android and on the web matched. 
-kids above 19 years were not included in the calculations. and no tasks were generated. 
-see screenshots below.
![image](https://user-images.githubusercontent.com/84722169/126490514-12a8edbd-3ed7-4b2d-a20e-9a944dd957b5.png)
![image](https://user-images.githubusercontent.com/84722169/126493694-7aef0495-55df-4701-a027-01517a26f857.png)
