### ISSUE TITLE
Merge NTD school workflow 

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1481]
- [ ] Fix build and coverage for [Adds NTD School and Community to Reveal](https://github.com/opensrp/opensrp-client-reveal/pull/713) PR
- [ ] Fix build and coverage for [Upgrade nativeforms, refactor geowidget factory](https://github.com/opensrp/opensrp-client-reveal/pull/1295) PR so that we can use the latest native forms version
- [ ] Ensure [allow getting forms from db without appending locale](https://github.com/opensrp/opensrp-client-native-form/pull/586) PR 
- [ ] Create a thai (th-preview) and namibia (stage) apk for QA to ensure no regression bugs are introduced
- [ ] Ensure form configurability works

**Comment by samkanga** [comment]
Closing this ticket as it has been marked as out of scope. It can be opened when determined that it can be done.
