### ISSUE TITLE
Merge NTD Community workflow

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1482]
- [ ] [Merge NTD school workflow](https://github.com/opensrp/opensrp-client-reveal/issues/1481)
- [ ] Fix build, test coverage and codacy issues on [Combined NTD](https://github.com/opensrp/opensrp-client-reveal/pull/1277) PR

**Comment by samkanga** [comment]
Closing this as it has been determined as out of scope. This can be reopened when required.
