### ISSUE TITLE
Reduce the Lower Bound Age for Children Added through Android App to >=5years

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1483]
CHAI has requested that we reduce the lower bound age for children added through the android APK to 5 years from 6 years. This is to facilitate capture of kids aged 5 years who may be identified in the schools visit.

**Comment by madrinekariuki** [comment]
I have tested this change.
Please note that tasks are being generated for kids 
who are 5 years.
noted that one cant add kids <5years
-Noted that kids added via web are showing on web
-Noted that kids added Via app are still not showing on web

kids added via web 
Jumamosi Juma 27/07/2016
Jumapili Moja 25/07/2016

Kids added via app
Ijumaa moja 27/07/2016

see screenshots below with capturing both kids added on web and app

![image](https://user-images.githubusercontent.com/84722169/127123802-c2ec90b7-dfe6-4c4a-911d-31185176e5f3.png)
![image](https://user-images.githubusercontent.com/84722169/127124242-e4f3e565-52b6-460f-b8a5-b6996638107f.png)

screen shot showing the kids show on web and tasks recorded on the app also show
![image](https://user-images.githubusercontent.com/84722169/127125195-7d7c37bc-0382-4e7b-9479-98422292eec5.png)

screenshot showing the SACs and age category have also correctly updated
![image](https://user-images.githubusercontent.com/84722169/127125778-b7af3d04-de89-4f9d-b421-92e83e596885.png)
