### ISSUE TITLE
BCC Tasks Not showing for Routine Plans on Thailand Preview

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1487]
The BCC tasks are not showing up on the android client for routine plans. A confirmation was made that BCC was selected among the activities for the creation of the routine plan used to test this. The BCC tasks are however showing for case triggered plans.

**Comment by Rkareko** [comment]
The fix for this is to update the condition for the BCC action to the following

```
      "condition": [
        {
          "kind": "applicability",
          "expression": {
            "description": "Jurisdiction type location",
            "expression": "Location.physicalType.coding.exists(code='jdn')"
          }
        }
      ]
```

The specifica change is from `"expression": "Location.physicalType.text = 'jdn'"` to `"expression": "Location.physicalType.coding.exists(code='jdn')"`
