### ISSUE TITLE
Issue when downloading offline Maps for Namibia

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1489]
user: user1_nam
apk:V5.3.26

test case:
-Verify that one is able to Download the offline maps

steps:
-login to the app
click on offline maps
click download
check the time it starts
observe the progress.

Noted:
-the offline map start downloading well
-the % progress is indicated.
-the progress is however too SLOW
-started download at 925 am
-download got to 100% at 1126 am
note i was only downloading data for 1 OA  -TEST OA
-the download got stuck **at 100% and i cannot open the downloaded map.**

**Comment by Rkareko** [comment]
@madrinekariuki Does the app show the size of the Map?

**Comment by madrinekariuki** [comment]
No there is no size indicated.
this is noted updating the screenshot in a few.
