### ISSUE TITLE
Plans not syncing/Updating on Thai preview

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1493]
Thai preview is not updating plans

steps
logged to Thai webUI  Preview
went to create a new plan.
created a new plan.
Changed  the plan to "in progress" and moved the expiration date abit far
saved the plan
moved to the "manage plans" tab
searched for that plan
the plan is missing.

on looking at the last updated plan noticed it was july 6th.
![image](https://user-images.githubusercontent.com/84722169/128312810-58a8410f-911c-4c51-bd75-403be2e71258.png)

jira ticket [here](https://smartregister.atlassian.net/browse/RVL-1771)

**Comment by ciremusyoka** [comment]
tracked [here](https://github.com/onaio/reveal-frontend/issues/1647)
