### ISSUE TITLE
Error message when logging in using invalid credentials

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1494]
tested this using:
test user: Onatest
android version  11
APK :Reveal stage 6.0.0-RC5

steps
login into to the app using wrong credential
e.g username or password.

observed
-user cannot login  but the message displayed is invalid.
-it does not show incorrect credentials

see below displayed message

screenshot
![image](https://user-images.githubusercontent.com/84722169/128475012-a9cd87b9-a759-4507-bf15-5a87980147d2.png)

**Comment by samkanga** [comment]
Closing this as its out of scope
