### ISSUE TITLE
Disabled options  showing on the app but grayed out( spray operator code) and appearing twice

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1495]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5

steps:
login to the app
register a new structure
click on the structure to add a spray status
notice on the form some option are grayed out 
grayed out options are showing twice.

screenshot below:
![image](https://user-images.githubusercontent.com/84722169/128476269-f19a36cd-b8dc-4a12-b40c-bd9c8891e8fd.png)

**Comment by samkanga** [comment]
I will go ahead and close this as it is out of scope.
