### ISSUE TITLE
Error message while opening larval breeding point/mosquito col point and POAT Point

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1496]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5
Namibia work flow

steps:
-register a  a larval breeding point/mosquito col point/POAT Point 
-try to open the structure and observe the error that pops up

-when one clicks on a larval breeding point/mosquito col point/POAT Point an error pops up "a structure does not have a task assigned to it for this plan"

screenshot
![image](https://user-images.githubusercontent.com/84722169/128478199-f528e053-67f4-4844-a7fa-c705a0d8797b.png)

**Comment by samkanga** [comment]
@madrinekariuki please share the plan name and its ID used in testing this issue. The PAOT belongs to the Thailand workflow and not Namibia.

**Comment by samkanga** [comment]
I will close this issue since it has not recurred on Thailand Preview which is the main test environment for  Thailand.
