### ISSUE TITLE
Cursor disappearing when adding a new structure for Namibia work flow. (This is intermitent)

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1497]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5
Namibia work flow

-click on register a new structure
-select type of structure
-notice how sometimes the cursor to direct you to the point to add a structure on the map disappears and this affects the place where one adds a structure
-this issue is intermittent

screenshot
![image](https://user-images.githubusercontent.com/84722169/128479341-1b395422-a580-4b1b-921e-cdb6fc016e61.png)

**Comment by samkanga** [comment]
Closing this ticket as Namibia is not using the Reveal App this year.
