### ISSUE TITLE
Partially sprayed structures turning green instead of Orange

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1498]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5
Namibia work flow

Steps
- Tap on structure
-enter village/house name
- Enter household name
- Enter number of eligible structures
- Enter a lower number for Number of structures sprayed in total.
-enter details of the sprayed structures(structure type and sprayed with what)
-enter total no of people living in the household
-enter total no of people sleeping in sprayed rooms.
- Select reason why some eligible room were not sprayed.
- Select is this was mop-up or not.
- Save

observe how the structure turns green instead of orange 

see screenshots below.
before
![image](https://user-images.githubusercontent.com/84722169/128481037-10b33a65-17a6-4ad6-a2dd-cec91090c3ff.png)

after
![image](https://user-images.githubusercontent.com/84722169/128481394-01828180-14da-4595-86c0-a02e9667fa00.png)

**Comment by samkanga** [comment]
Closing this ticket as the Namibia work has been descoped as they are not using reveal this year.
