### ISSUE TITLE
Downloading offline maps is too slow

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1499]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5
Namibia work flow

Description.
sync device data
click on the offline maps to start downloading
check the time it takes to complete downloading offline maps.

Noted that maps that are 19 mbs are taking even 2 hours to download on a 5mbps speed.

**Comment by samkanga** [comment]
This is a mapbox issue that cannot be resolved in code. I will mark this issue as closed.
