### ISSUE TITLE
Implement the Spray Form

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#15]
When a user touches a yellow point on the map, they are automatically directed to a spray form. This ticket focuses on implementing the spray form and defining what happens after it's saved.

Step 1: User taps the yellow point (The GeoWidget passes in the appropriate GeoJSON properties)
Step 2: the form launches
Step 3: The user saves the form
Step 4: Subsequent items are updated based on the information in the form

The contents of the form in this screenshot are not accurate. Please visit [the data dictionary](https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=396087476) for the correct fields.
![irs - record spray status](https://user-images.githubusercontent.com/6067053/48241516-24600800-e38c-11e8-9af7-905b0c4122dc.png)

UI Elements:
Top Navigation:
- [x] The bar at the top displays an X in the top left corner. When the user touches it it cancels the form
- [x] The bar at the top displays the form name
- [x] The bar at the top displays the word SAVE which saves the form

Properties passed in from GeoJSON object:
- [x] task.identifier
- [x] task.businessStatus
- [x] task.status
- [x] location.id
- [x] location.properties.uid
- [x] location.peroperties.version
- [x] ocation.properties.type

Form Contents:
- The form contents are displayed in the remainder of the form as is defined in the dictionary.

Post SAVE Activities:
- [x] The form content that is identified by entity updates those entities.
- [x] The task is updated with the updated businessStatus and status ("Complete")
- [x] If the structure is non-residential, the location properties.type need to be updated to reflect that.
- [x] The user is redirected to the map view with the location clicked displaying the card.

**Comment by craigappl** [comment]
This has a question because I need to verify the contents of the business data in this form with Akros.

**Comment by githengi** [comment]
@craigappl is the verifaction complete

**Comment by githengi** [comment]
@craigappl are below fields applicable to the spray for

- familyHeadName
- familyHeadSex
- roomsFound
- sprayedRooms
- netsFound
- mopUp

**Comment by craigappl** [comment]
@githengi 
1) those fields are required for the spray forms. They were added this week after a review with Akros and VitalWave.
2) Yes, anyone on the team can complete the form.
