### ISSUE TITLE
In-App indicators not working

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1501]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5
Namibia work flow

added data is not showing on the in-app indicators.
they are all showing zero
see screenshot below.
![image](https://user-images.githubusercontent.com/84722169/128496346-a642ffbe-8272-4c34-94b7-53f7be407a9a.png)

**Comment by samkanga** [comment]
Closing this ticket as Namibia is not using the Reveal App this year.
