### ISSUE TITLE
Different workflow from the Prod version

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1502]
tested this using:
test user: Onatest
android version 11
APK :Reveal stage 6.0.0-RC5
Namibia work flow

noted that the flow is different from that of the production apk . 
for prod you can only register a village on this APK you can register a home, hut, church and space station and also  
you can also select "Type of structure".
we also have options for Mosquito collection point/larval breeding site and POAT that are missing on the prod APK

**Comment by samkanga** [comment]
Closing this ticket as Namibia is not using the Reveal App this year.
