### ISSUE TITLE
Sync Error message when internet is off

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1507]
Tested this on V.5.3.30-rc3
devices:Android 11/Android 6

steps

- install the APK
- login to the app and sync data
- switch off the internet
- try to sync the data again
- observe how the message 'Syncing ' shows even without internet.

expectations:
incase there is no internet the message should indicate 
sync failed due to lack of internet
![image](https://user-images.githubusercontent.com/84722169/129235704-7f480c76-b782-4434-b07a-e7e6bfbcaf98.png)

**Comment by samkanga** [comment]
Closing this as its an edge case.
