### ISSUE TITLE
Inability to See Household Lists

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1511]
On the Thailand Production Android Client, structures exist within plans. However, clicking on "LIST" in the upper right hand corner to lists the tasks results in a "Fetching Structure Details" error.

![image](https://user-images.githubusercontent.com/5908630/132205574-03d50d73-675a-4450-afd4-6dcdb23491d7.png)

User vbdc_3.2-1 reported the issue for the following plans IDs:
"5c5a8f39-6707-586b-8271-d4c5cdc82812", 
"dce78201-4ff6-5d9b-82d3-891bdbb188cc", 
"e48d349d-e249-54e7-8860-0fe4c0ad6ff2"

**Comment by Rkareko** [comment]
@samkanga cc @LZRS Appears one of the plans affected by this issue has the id `1c7414c1-a560-51c3-abd2-63f1e028b8d2`. @LZRS could you check whether the plan has tasks

**Comment by LZRS** [comment]
@Rkareko cc @samkanga I've confirmed, the plan with id `1c7414c1-a560-51c3-abd2-63f1e028b8d2` doesn't have any tasks

**Comment by Rkareko** [comment]
@samkanga This appears to be a task generation issue. Once tasks are generated could we carry out QA to confirm that the issue is fixed

**Comment by samkanga** [comment]
@Rkareko we got the tasks for the plan generated and the issue has resolved. Below is a screenshot of the task list view.
![image](https://user-images.githubusercontent.com/5908630/132328470-9fbce0cf-ea04-4549-a8f2-da01824bc463.png)
