### ISSUE TITLE
Failure to download offline maps

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1513]
Offline map download is failing. The error displayed is `HTTP status code 403`.

We are currently using Digital Globe in the [map download style](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/map-download-style.json) . Unfortunately the DG license has expired so we have to update this to use mapbox

**Comment by madrinekariuki** [comment]
Issue still present and the observations are:
- inconsistent % download progress e.g it started at 14.57% and the moved back to 1% and kept flactuating.
- theres a mapbox error. as seen on the screenshot below.
- After the error, the download progresses for a few more seconds and then stops.
- when you try to download another Map the app crashes. (error attached)

![image](https://user-images.githubusercontent.com/84722169/133281207-0ee75fcb-6d19-43ad-9edf-4883b9e84f9a.png)
![image](https://user-images.githubusercontent.com/84722169/133281273-a3163629-e0ef-46e7-a7af-2275ca8d2d93.png)

**Comment by samkanga** [comment]
I will go ahead and close this ticket.
