### ISSUE TITLE
NTD recorded Events not Showing on web UI 

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1516]
@baokiddy
web [Instance](https://web.reveal-sz.smartregister.org/intervention/mda-point/child-report/51d2fcbd-2064-5b6e-b94d-cf86be515114/f0de23e0-1e42-49e1-a60f-58d92040cccc)
apk version: v5.3.30.RC9
planID: 51d2fcbd-2064-5b6e-b94d-cf86be515114

Details:
On the Eswatini instance the details of children that have been recorded. on the android client are not showing on web.
sample kids whose detail have been recorded are:
```
Kariuki wanjiru
M sue
Ouma Steve
Kariuki Muthoni
```

![image](https://user-images.githubusercontent.com/84722169/133274163-188adddc-e58e-40cd-ade0-c18ff35f4837.png)

**Comment by samkanga** [comment]
I will go ahead and close this ticket as this is now resolved.
