### ISSUE TITLE
Users Unable to Login to NTD App when User Is Offline

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1519]
Users who get automatically logged out when online and try to login when offline are locked out of the APK. The client wants this to be factored to cover the possibility of a user being unable to work do to the above scenario.

**Comment by madrinekariuki** [comment]
@Rkareko 
Tested this on v5.3.31
user :eswatini10

steps  and observations:

Installed at 1020 am 
user was logged off at 1059 am
I switched off the internet and I tried logging to the app
I was able to login to the app and I can add a kid
But after switching on the internet the app logs one off (without the error )and I have to login again
