### ISSUE TITLE
Task Generation Issue on Thailand Preview APK

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1524]
There is inconsistent task generation (English APK version 5.3.26) when a plan has the Bednet Distribution Action and when it does not have the action. When the action is selected tasks appear for the different structures (See screenshot 1 below with pink structures) and when the action is removed, structures appear in grey and yellow colors. The latter suggests that there are tasks lost of structures not registering existence of household members. (See screenshot 2 below). This is based on the plans with ids `37379261-8b97-58eb-9cc5-22b0bc0a7c1d` without bednet action and `50c4504c-4877-5c3b-afac-3f10e66ac2f7` - With Bednet Action.

Screenshot 1:
![image](https://user-images.githubusercontent.com/5908630/134509907-3658d255-5018-4479-b971-dd57fb613e01.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/5908630/134509470-7c53acfe-46f5-45d1-ae5d-3a5f6e944ddf.png)

However, one cannot select the pink structures and it's returning the error `Failed to Fetch Family Details` See screen 3 below.
![image](https://user-images.githubusercontent.com/5908630/134510018-bff63102-941f-4d31-98fe-3f05e51ae91a.png)

**Comment by Rkareko** [comment]
From the db both plans appear to have similar numbers of `BCC`, `RACD Register Family` and `Blood Screening` tasks 

```
select count(*), code from core.task_metadata where plan_identifier = '37379261-8b97-58eb-9cc5-22b0bc0a7c1d' GROUP by 2 order by 1 ;
 count |         code         
-------+----------------------
     1 | BCC
    81 | RACD Register Family
  1051 | Blood Screening


select count(*), code from core.task_metadata where plan_identifier = '50c4504c-4877-5c3b-afac-3f10e66ac2f7' GROUP by 2 order by 1 ;
 count |         code         
-------+----------------------
     1 | BCC
    82 | RACD Register Family
   209 | Bednet Distribution
  1051 | Blood Screening
```

Next step is to investigate what is happening on the app

**Comment by samkanga** [comment]
This has been resolved.
