### ISSUE TITLE
RVL-1872 Unable to Maintaining Field Type 

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-client-reveal#1527]
Jira [link](https://smartregister.atlassian.net/browse/RVL-1872)

(1)
When we are registering a family member who is above 17, we should see the occupation field as a drop down menu with many options to choose from. After this member has been saved and we want to edit their occupation information, we find the occupation field to has changed to just a simple text filed 

Desired behavior is that when you come back to edit, the occupation field should still be a drop down menu. 

(2) 
When you are registering foamily members, and we use a date picker, sometimes the occupation filed doesn't show up.

**Comment by samkanga** [comment]
I will go ahead and close this ticket.
