### ISSUE TITLE
Case Confirmation tasks not showing for Index case plans on Thai-Preview

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1532]
issue description:
index cases that have been created do not have case confirmation tasks. This has been noted on below sample plan IDs on Thai Preview. 

We have noted a discrepancy on the case confirmation plan template:
where for earlier plans we had a trigger and a condition which is missing on the current template.

Earlier Action part on the template:
 ```
  {
                "identifier": "6b2a7118-c6c9-43b7-8227-5d3275878d97",
                "prefix": 1,
                "title": "การยืนยันบ้านผู้ป่วย",
                "description": "ยืนยันบ้านผู้ป่วย",
                "code": "Case Confirmation",
                "timingPeriod": {
                    "start": "2021-09-09",
                    "end": "2021-09-19"
                },
                "reason": "Investigation",
                "goalId": "Case_Confirmation",
                "subjectCodableConcept": {
                    "text": "QuestionnaireResponse"
                },
                "trigger": [
                    {
                        "type": "named-event",
                        "name": "plan-activation"
                    }
                ],
                "condition": [
                    {
                        "kind": "applicability",
                        "expression": {
                            "description": "Event is case details event",
                            "expression": "questionnaire = 'Case_Details'"
                        }
                    }
                ],
                "definitionUri": "case_confirmation.json",
                "type": "create"
            }

```

Current Action part on the template:
```
   {
                "identifier": "2ee5a878-69f0-4446-9b06-119d15c520e7",
                "prefix": 1,
                "title": "การยืนยันบ้านผู้ป่วย",
                "description": "ยืนยันบ้านผู้ป่วย",
                "code": "Case Confirmation",
                "timingPeriod": {
                    "start": "2021-10-16",
                    "end": "2021-10-26"
                },
                "reason": "Investigation",
                "goalId": "Case_Confirmation",
                "subjectCodableConcept": {
                    "text": "Operational_Area"
                },
                "taskTemplate": "Case_Confirmation",
                "type": "create"
            },

```

```
 Sample planIDs
a1fa4791-1555-451e-9725-018e621aeeb3
b323972d-1e1a-4d06-b338-940c63971194
7d4be8b3-c3e5-4e66-82aa-3431914b9ad8
```

steps:
-Create an index plan
-activate the plan and assign a team to it.
-login to the APK and sync the plan 
-open the list view and observe there are no Case confirmation tasks

![image](https://user-images.githubusercontent.com/84722169/137706314-dd67a394-49e9-49f2-a885-1e1c4297a0f2.png)

**Comment by lincmba** [comment]
Updated the following processors:
- https://nifimhealth.ddc.moph.go.th/nifi/?processGroupId=51043f76-3b76-1ea6-8f75-5cad2fddbcaf&componentIds=51043f87-3b76-1ea6-3554-4ce2211a5744
- https://nifimhealth.ddc.moph.go.th/nifi/?processGroupId=51043f76-3b76-1ea6-8f75-5cad2fddbcaf&componentIds=51043f80-3b76-1ea6-6d72-8d563bb1f201
- https://nifimhealth.ddc.moph.go.th/nifi/?processGroupId=51043f76-3b76-1ea6-8f75-5cad2fddbcaf&componentIds=51043f86-3b76-1ea6-f77b-b92c23463c20

**Comment by lincmba** [comment]
For this issue, we matched the production template to the preview template.

**Comment by samkanga** [comment]
I will go ahead and close this ticket.
