### ISSUE TITLE
Some structures on Thai-preview appearing in grey.

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1533]
we have structures for index case plans that are appearing in grey and when you click on the structure you get an error "Failed to get Family details ". Other structures in the plan have details and tasks. 

This has been observed  on this [plan](https://web.reveal-th-preview.smartregister.org/plans/update/14a0da09-3a1c-414a-a7cb-aa32e3e63afd)  

see screenshot below:
![image](https://user-images.githubusercontent.com/84722169/139252804-a34342cd-f623-4c22-83d0-fc9693de719a.png)

**Comment by madrinekariuki** [comment]
This is also affecting the prod instance. and it has been observed on below 2 plans  find details explained below.
 ```
plan name: A2 ยางขาว (7108020401) 2021-10-15
plan id: 7aa48cfe-e840-54a7-b8f9-87ac4b76a6a6
user: vbdu_5.1.8-1
```
This above plan has only one grey structure. and when you try clicking n the grey structure you get an error.


```
plan name: A2 บาตูตางอ (9607030803) 2021-10-18 (SCD 22-07-2021)
plan id: ad377dc8-09ff-500a-bfce-e2cb967c38db
user: vbdu_12.4.4-1
```
This one above  all the structures are all grey BUT you can click on them but they do not have tasks


see below screenshots:
![image](https://user-images.githubusercontent.com/84722169/139627277-891f1829-2b31-4080-8db1-f39d52105aa5.png)
![image](https://user-images.githubusercontent.com/84722169/139627285-61be8175-bf3b-4330-89a4-fc8a936159c4.png)

**Comment by madrinekariuki** [comment]
@Rkareko 
for new routine plans created all residential structures have tasks. and there is no grey structure.

using the shared example on an index case plan created on 28th october you see the grey structures. 
 for an index case plan ID : `14a0da09-3a1c-414a-a7cb-aa32e3e63afd`
structure on the map in the screenshow below
![image](https://user-images.githubusercontent.com/84722169/140268601-fdfb3fe6-3fac-4373-934c-2f5f6605faaa.png)

**Comment by Rkareko** [comment]
@madrinekariuki Could you re test this with a new case triggred plan

**Comment by madrinekariuki** [comment]
@Rkareko  
retests with a new case triggered plan on preview. ID: `7962f66b-7827-4bbe-89d4-1f8f5475099d`
Its noted that the structures that were grey in the previous case triggered plan are now pink , However when you click on them one is getting an error. "Failed to Fetch family details"

could be a sync issue as previously observed in other plans . Giving this some more time to confirm if the structures shall open. Also noted that After clearing data and syncing data, the structures that were previously grey. even on the new routine plan are not opening with the  same error

see screenshot below
![image](https://user-images.githubusercontent.com/84722169/140294656-29d421a6-9df3-4141-82cb-e9b55aa57379.png)

**Comment by samkanga** [comment]
Closing this in favor of [this](https://github.com/opensrp/opensrp-client-reveal/issues/1538).
