### ISSUE TITLE
Tasks not showing up on previously  Existing Structures

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1534]
After Migration of task generation to OpenSRP  on prod instance we note that on existing structures for routine plans, the task part only has the "Record Distribution task". 
Unless one adds a new family member that is when the "Record screening task" shows. 

This has been tested on `planID: cb640759-ab2f-548f-9566-620f19ca1684`

see screenshot below:
![image](https://user-images.githubusercontent.com/84722169/139667511-569c6ed1-7e81-4e87-8304-1af2046ff0d9.png)

**Comment by Rkareko** [comment]
@madrinekariuki 
1. Does this happen on all structures?
2. Were there any family members for those structures?

**Comment by madrinekariuki** [comment]
> @madrinekariuki
> 
> 1. Does this happen on all structures?
> 2. Were there any family members for those structures?

@Rkareko 
 1. Does this happen on all structures?
 Yes this is happening on all previously existing residential structures.
 
2. Were there any family members for those structures?
 Yes, we had family members in the structures. see screenshots below. for a sample family called "Teas Family"
 
 
![image](https://user-images.githubusercontent.com/84722169/139668866-a8722738-19dc-4eca-b98e-fe1eb7995564.png)
![image](https://user-images.githubusercontent.com/84722169/139669093-1a0a3515-df4e-4840-85ef-d22b60a79ffc.png)

**Comment by Rkareko** [comment]
Here is the distribution of tasks for plan with id `cb640759-ab2f-548f-9566-620f19ca1684`

> select count(*), code from core.task_metadata where plan_identifier = 'cb640759-ab2f-548f-9566-620f19ca1684' group by 2;
>  count |         code         
> -------+----------------------
>      7 | RACD Register Family
>      4 | Mosquito Collection
>      1 | BCC
>      1 | Larval Dipping
>      4 | Blood Screening
>     27 | Bednet Distribution
>

**Comment by samkanga** [comment]
@Rkareko does it mean tasks are being generated but not showing up on the android client?

**Comment by Rkareko** [comment]
@samkanga appears that there are 103 client records for the jurisdiction (with id `b8a404d0-5e4d-455f-8bc1-90f8005c3b0a`) that the plan is registered for i'e

```
select count(*),  json->>'gender' locationId from core.client where json->'attributes'->>'residence' IN (select geojson_id from core.structure_metadata where parent_id = 'b8a404d0-5e4d-455f-8bc1-90f8005c3b0a') group by 2;
 count | locationid 
-------+------------
    42 | Female
    61 | Male

```

We would expect there to be 103 blood screening tasks generated but we only have 4.

All the 103 client records have the correct location_id

```
select count(*),  json->>'locationId' locationId from core.client where json->'attributes'->>'residence' IN (select geojson_id from core.structure_metadata where parent_id = 'b8a404d0-5e4d-455f-8bc1-90f8005c3b0a') group by 2;
 count |              locationid              
-------+--------------------------------------
   103 | b8a404d0-5e4d-455f-8bc1-90f8005c3b0a
```

Still looking into how the rest of the clients don't have blood screening tasks

**Comment by Rkareko** [comment]
@samkanga slight correction seems there are `27 families` and `76 family members`

select count(*),  cm.client_type 
FROM core.client_metadata cm
JOIN core.client c on cm.client_id = c.id AND  c.json->'attributes'->>'residence' IN (select geojson_id from core.structure_metadata where parent_id = 'b8a404d0-5e4d-455f-8bc1-90f8005c3b0a') group by 2;
 count | client_type 
-------+-------------
    27 | Family
    76 | 
(2 rows)

**Comment by Rkareko** [comment]
@samkanga There seems to be a mismatch between the location Id data that is stored in the client json which returns `103` client records and the client metadata which returns `5` client records  i.e
```

select count(*),  json->>'locationId' locationId from core.client where json->'attributes'->>'residence' IN (select geojson_id from core.structure_metadata where parent_id = 'b8a404d0-5e4d-455f-8bc1-90f8005c3b0a') group by 2;
 count |              locationid              
-------+--------------------------------------
   103 | b8a404d0-5e4d-455f-8bc1-90f8005c3b0a
```

versus

```
select count(*) from core.client_metadata where location_id = 'b8a404d0-5e4d-455f-8bc1-90f8005c3b0a';
 count 
-------
     5

```

The task generation logic for fetching client records when generating blood screening tasks uses the 2nd approach

**Comment by Rkareko** [comment]
@samkanga Found the issue. Some of the location ids were wrapped in quotes i.e

```
select count(*), location_id from core.client_metadata where residence IN (select geojson_id from core.structure_metadata where parent_id = 'b8a404d0-5e4d-455f-8bc1-90f8005c3b0a') group by 2;
 count |              location_id               
-------+----------------------------------------
    98 | "b8a404d0-5e4d-455f-8bc1-90f8005c3b0a"
     5 | b8a404d0-5e4d-455f-8bc1-90f8005c3b0a
```

**Comment by madrinekariuki** [comment]
@Rkareko I have created a new plan` c9620a41-079a-54e2-833c-47dad9e2c866` in the same OA and  each residential  structure now has all the tasks generated.
 see screenshot below. 
![image](https://user-images.githubusercontent.com/84722169/139681800-6768ec19-005a-47ec-a855-029d7013a332.png)

However testing this on a plan created on a different OA I note that we have structures missing tasks. see sample on the screenshot below and on the plan IDs:
`ea22bd15-a608-5b82-9b7e-f9f452d58c0c`

![image](https://user-images.githubusercontent.com/84722169/139682481-264a5040-3b58-470a-a194-325d0f800656.png)

**Comment by madrinekariuki** [comment]
This has been retested with a new plan` 8578d0a2-76c7-5a62-81f4-89ec3a962e5a`
Tasks for all the family members are now visible

see screenshot below..
![image](https://user-images.githubusercontent.com/84722169/139687404-ef8f5af1-c91d-4706-b936-ae3a91bb6654.png)
