### ISSUE TITLE
Tasks being generated more than the number of Household members.

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1535]
On Thai Prod, for the planID : 13ab50ce-502c-4165-9936-8acaec92a525

Observation:
On some structures we have more tasks being generated than the number of family members in that household. Also in some instances we have the number of household members being more than the number of tasks generated. 

In the plan given this has been observed in the Family 
Tina family
Frazer family
Grixx family
Bont Family (more family members than tasks).

see screenshot below.

![image](https://user-images.githubusercontent.com/84722169/139706398-57f38898-0d52-4220-8b63-50105746d53e.png)
![image](https://user-images.githubusercontent.com/84722169/139706424-33e6f57f-9cd9-4d18-a557-5b69d8ef5d92.png)

**Comment by Rkareko** [comment]
@samkanga @madrinekariuki here are my findings so far
1. Molly Caron has not been archived and she was registered to family attached to this structure

select client_id, first_name, last_name,document_id, base_entity_id, residence, date_deleted from core.client_metadata where location_id  = 'a7baf57d-ad31-46d2-8d28-0c81dd306b09' and client_type is null and first_name in ('Molly','Tina');
 client_id | first_name | last_name |             document_id              |            base_entity_id            |              residence               | date_deleted 
-----------+------------+-----------+--------------------------------------+--------------------------------------+--------------------------------------+--------------
      8603 | Tina       | Family    | f96b0e03-9581-41c2-b4a2-40dc7da34440 | a77c41fe-7170-4c52-817f-afd93cd3bca6 | c9a86c87-dc45-428f-a98f-b08ad51e7541 | 
      8609 | Molly      | Caron     | 430cf869-6172-4752-943c-33ac1eda226d | c4d154f9-3889-4a7d-874d-7e9fc6cb2d1e | c9a86c87-dc45-428f-a98f-b08ad51e7541 | 
      8604 | Tina       | Broen     | 99f38a91-cce6-4480-8452-3c30c2e1f510 | a8dde3b3-44c8-4253-8739-6ee282d2cea6 | c9a86c87-dc45-428f-a98f-b08ad51e7541 | ``

2. Molly Caron is attached to adifferent family which was archived 

```
select client_id, first_name, last_name,document_id, base_entity_id, residence, date_deleted from core.client_metadata where base_entity_id = '7c5138de-b163-48bb-a676-75500473bfdd';
 client_id | first_name | last_name |             document_id              |            base_entity_id            |              residence               |      date_deleted       
-----------+------------+-----------+--------------------------------------+--------------------------------------+--------------------------------------+-------------------------
      8602 | Annie      | Family    | fdabbb22-d4b0-49ca-86f3-8ba4c5bac119 | 7c5138de-b163-48bb-a676-75500473bfdd | c9a86c87-dc45-428f-a98f-b08ad51e7541 | 2019-12-16 21:14:01.025
```

**NB** 
Archived clients (families, family members) have a value in the `date_deleted` field

**Comment by Rkareko** [comment]
@madrinekariuki could you carry out the following tests on Thailand Preview

**Scenario 1**
1. Add a structure on an existing plan
2. Register a family
3. Add some family members
4. Sync the data to the server
5. After the sync is complete Archive the family
6. Sync data to the server
7. Create a new plan for the OA and test whether there is a register family task for the structure
8. Register a family and check the number of blood screening tasks generated

`Scenario 2`
1. add a structrue in an existing plan
2. Register a family
3. Add some family members
4. Sync data to the server
5. After the sync is complete archive 2 of the family members
6. Sync data to the server
7. After sync is complete create a new plan for the OA
8. Check the number of blood screening tasks generated for the structure

**NB** Both scenarios can be tested concurrently using different structures

**Comment by madrinekariuki** [comment]
@Rkareko 

see below observations after testing the above scenarios.

Scenario one. 
old plan used ID: 0eee0a2f-0033-58bc-b7d7-673be9b923e1
New plan used ID: 08299398-1f65-597f-a370-86a89033a693

- family registered in the old plan is called Fridah.
- added 2 members:
Fridah K
Wanjiru K
- Archived the Household and synced data.
- after creating a new plan for the OA and I try to click on the household I got the error "Fetch Family details Failed"


Scenario 2:
old  plan used ID: 95cd3ea9-1293-5036-b08e-ebed0f4cad4b
New plan used ID: 33683368-ed43-579e-b30b-afb17d618d43

- created a family in the old plan called Nettah
- added 3 members.
 Nettah kamau
 edu kamau
 mumbi kamau
- synced data.
- Archived 2 members
 mumbi kamau
 edu kamau
- created a new plan in the OA and synced data and opened the Nettah family
- observed that the family has 1 member i.e Nettah Kamau. who has tasks Bednet distribution and blood screening task.

**Comment by madrinekariuki** [comment]
@Rkareko 

Did a scenario 3 on Thailand Preview.

Scenario 3 steps:

used plans:
old plan:08299398-1f65-597f-a370-86a89033a693
new plan:7ab52c71-0b5f-5078-9b25-df9a1563f4cf

- In the Old plan, create a new structure and add family members
-  sync the data
-  Archive the family and sync data.
- Register a new family in the same structure and add family members and sync the data.
- create a new plan in the Same OA and click on the structure to confirm the family members and tasks present. 


Observations.
- Family members registered lastly in the structure show even on the new plan in the same OA. 
- The number of blood screening tasks match the number of family members registered.

**Comment by madrinekariuki** [comment]
tested the Above 3 scenarios on the production instance. See below observations.

Scenario 1.
Old plan used ID: ca86f6b6-36bb-5078-876a-407821ce437e
New plan used ID: 630cd07a-934a-5d4e-830f-410be6263d39

After archiving the family when you try to open the family in the new plan you get the error "Failed to fetch family details"
in the old plan the Archived structure can be opened but it prompts you to register a new family.

Scenario 2.
Old plan used ID: c9620a41-079a-54e2-833c-47dad9e2c866
New plan used ID: 8608b9e5-1fcb-566c-bad9-383d8aebf2bf

Observation
After archiving some family members and syncing data, then creating a new plan n the OA , when you click on the structure, only the family member who was not archived shows. Also Tasks are only generated for that family member who has tasks: Bednet distribution and blood screening task.


Scenario 3.
Old plan used ID:  c9620a41-079a-54e2-833c-47dad9e2c866
New plan used ID: 862f7d9e-8c32-5623-a9a4-c1eb39f9eb51

Observation
when you archive the initial household and sync and then you add new family members and sync the data.
then you create a new plan in the same OA and sync data, you observe that:
Family members registered lastly in the structure show even on the new plan in the same OA.
The number of blood screening tasks match the number of family members registered.

**Comment by Rkareko** [comment]
@madrinekariuki cc @samkanga Could you test the following scenario on Thailand Preview

1. Register a new family member. Click on the `DOB Unknown` checkbox so that you enter the age manually. 
2. Register a new family member. Enter the DOB using the date picker.
3. Activate a new plan for that OA
4. Check whether a `blood screening` task was generated for the family member that was registered using the age.
5. Check whether a `blood screening` task was generated for that family member that was registered using the DOB.

**Comment by madrinekariuki** [comment]
@Rkareko cc @samkanga 
- I have added 2 family members in [this](https://web.reveal-th-preview.smartregister.org/plans/update/0eee0a2f-0033-58bc-b7d7-673be9b923e1) old plan on thai preview : `0eee0a2f-0033-58bc-b7d7-673be9b923e1
`
`Junipa Ola` (Ticked date unkown checkbox and used manual date insert)
`Grace Ola `(Used the date picker)
- synced the data and created a new [plan](https://web.reveal-th-preview.smartregister.org/plans/update/553d81c9-2471-5e0a-b263-cc11b0b1ee99) For the OA `553d81c9-2471-5e0a-b263-cc11b0b1ee99`
- synced data and opened the structure from the new plan.

Noted that both members have `blood screening tasks` generated. see screenshot below.
![image](https://user-images.githubusercontent.com/84722169/140017152-7649b53a-4b62-4ff1-a1f0-bbe312e5f3a9.png)
![image](https://user-images.githubusercontent.com/84722169/140017184-320a00d1-d8a5-4e0d-9a1e-b64540a48094.png)

**Comment by madrinekariuki** [comment]
New created plans have tasks matching the number of family members. 
this has been tested in structures in below plans 
```
6f4f2d26-1671-53e9-9593-b3b7e6e2c585
a01ee0b8-57a2-5304-9d0f-2284171d471c 
```

see sample family details below
![image](https://user-images.githubusercontent.com/84722169/140035904-eddfb045-d59b-41d4-b5c7-5eb09836e036.png)
