### ISSUE TITLE
Undo the Validation for Duplicate plans on Reveal Thailand OpenSRP

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1537]
We added a validation on the Thailand production OpenSRP instance to prevent duplicate plan from being created. One of the attributes used in the validation is the case number. CHAI however informed us that BVBD have cases where they delete inserted cases and re-instert them into the system. This means that in a case where NiFi had processed the index case and case numbers, plan are already created in OpenSRP. As a result the act of deletion of index cases and resuse of the index number is taken by OpenSRP to be duplication. As such, CHAI has asked us to undo the feature and use the checks on metabase to catch duplicates that will then be deleted manually from OpenSRP and Canopy DBs when they occur.

**Comment by Rkareko** [comment]
Issue tracked on server web repo [here](https://github.com/opensrp/opensrp-server-web/issues/985)
