### ISSUE TITLE
RACD plan generating only one plan even with p_site_id and a source_site_id present

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1540]
A case triggered plan that has both the` p_site_id `and `a source_site_id` should generate 2 plans a site and a source plans.
After the plan generation migration to openSRP, it has been noted that only a site plan is being generated. 

see below 2 examples eventID:
3540984f-e398-4fbe-8ce9-e80b5485efa1
fc504228-d178-4dd5-b501-882db925ae6f

2 plans Ought to have been generated because data that was inserted into the mhealth DB had both  `p_site_id `and a `source_site_id`

see below:
`INSERT INTO db_mhealth_preview.dbo.index_case (case_id,p_site_id,p_site_name,p_site_area,source_site_id,source_site_name,source_site_area,case_classification,household_id,blood_draw_date,investigtion_date,ep1_create_date,ep3_create_date,house_number,patient_name,patient_surname,patient_age,species,id) VALUES('2401224081140861232','1206030003','เมืองทอง(Site)-2','A1','1206030003','เมืองทอง(Site)-2','A2','Bz','','2021-11-10','2021-11-10','2021-10-15 00:00:00.000','2021-11-10 00:00:00.000','H321','QA','test',69,'M',878);`

**Comment by samkanga** [comment]
Closing this in favor of [this](https://github.com/onaio/canopy/issues/2523).
