### ISSUE TITLE
Plan missing Team assignments but is accessible from the android APK

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1541]
On Thailand production we have [this](https://mhealth.ddc.moph.go.th/plans/update/d08376ae-a1ca-504a-93d5-853ce345512e) plan that  does not have any team assignments on the WebUI. It is however accessible from the android apk v5.3.28. 
The plan is accessible through the user `test2021-2`
the plan ID is: `d08376ae-a1ca-504a-93d5-853ce345512e`

on checking further we note that the plan has active Team assignments on the DB see query result below:
```
 id   | organization_id | location_id | plan_id | from_date  | to_date |   duration    |  username  |    name    |          name           | status |              identifier              | planstatus 
-------+-----------------+-------------+---------+------------+---------+---------------+------------+------------+-------------------------+--------+--------------------------------------+------------
 61609 |             303 |       22384 |    9072 | 2021-11-19 |         | [2021-11-19,) | test2021-2 | test2021-2 | บ้านอบรมรุ่น2 (1206030018) | ACTIVE | d08376ae-a1ca-504a-93d5-853ce345512e | active
```

Also an API call done to [this](https://servermhealth.ddc.moph.go.th/opensrp/rest/organization/assignedLocationsAndPlans?pageNumber=1&pageSize=1000&plan=d08376ae-a1ca-504a-93d5-853ce345512e) endpoint shows that there is a team assignment returned. Why is the web UI not displaying the team assignment?

See screenshots below for the team assignment on UI and the android screenshot.
![image](https://user-images.githubusercontent.com/84722169/142838025-3d9096dc-cb4c-4844-b912-97cdb3c72f45.png)
![image](https://user-images.githubusercontent.com/84722169/142838070-7a1c5c87-4f29-43fa-ad2e-cc770125c824.png)

**Comment by samkanga** [comment]
Closing this in favor of [this](https://github.com/onaio/reveal-frontend/issues/1677) ticket.
