### ISSUE TITLE
Inconsistent Slow Sync Progress on Thailand Production APK

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1542]
CHAI has reported that users are experiencing a delay in sync with some instances recording above 8minutes from the time the android client starts to sync to the time sync is completed. One of the affected users `vbdu_5.2.2-1`. Could we check what may be causing the delay in sync?

**Comment by ndegwamartin** [comment]
@samkanga for the initial sync to the device from the server that can take a lot of time if the provider belongs to a location/team that has a lot of data. Subsequent syncs should be faster

**Comment by samkanga** [comment]
Closing as it has not recurred
