### ISSUE TITLE
Task generation issue on Thai preview.

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1545]
Case triggered plans are not generating tasks on Thai preview. 
This has been tested on  th-en prev apk v5.3.28rc8:
This has been tested on planID: `64ae21ed-e60f-4ab0-8060-335375f8482b`
noted issues on missing tasks are:
- Case confirmation tasks are not generating.
- BCC tasks are also not generating.
- Some existing structures do not have all tasks generated. 

see screenshots below:
![image](https://user-images.githubusercontent.com/84722169/145023724-492cc5c5-d865-46da-a653-d4f5abce446f.png)
![image](https://user-images.githubusercontent.com/84722169/145023786-856745f1-73e6-484e-a1ec-114fcf762309.png)

**Comment by Rkareko** [comment]
Here is the break down of the tasks that have been generated

```
select count(*), code from core.task_metadata where plan_identifier = '64ae21ed-e60f-4ab0-8060-335375f8482b' group by 2;
 count |         code         
-------+----------------------
    16 | RACD Register Family
     2 | Bednet Distribution
   357 | Blood Screening
(3 rows)

```

**Comment by Rkareko** [comment]
`Case Confirmation` tasks are not being generated since there are no corresponding `Case_Details` events i.e

```
select base_entity_id, event_type, location_id, plan_identifier from core.event_metadata where location_id = 'b49faa39-5e24-4de8-bf3f-cdda6f320179' and plan_identifier = '64ae21ed-e60f-4ab0-8060-335375f8482b';
            base_entity_id            |         event_type         |             location_id              |           plan_identifier            
--------------------------------------+----------------------------+--------------------------------------+--------------------------------------
 493efd63-2484-49ed-ae0c-4918380cdb74 | Register_Structure         | b49faa39-5e24-4de8-bf3f-cdda6f320179 | 64ae21ed-e60f-4ab0-8060-335375f8482b
 4de4a9c6-0f73-4c14-b058-c26421817d4b | Family_Registration        | b49faa39-5e24-4de8-bf3f-cdda6f320179 | 64ae21ed-e60f-4ab0-8060-335375f8482b
 439a47bb-845a-46db-8e48-4b9583a27f11 | Family_Member_Registration | b49faa39-5e24-4de8-bf3f-cdda6f320179 | 64ae21ed-e60f-4ab0-8060-335375f8482b
 8c3b6311-2cf7-4abf-b03f-7b001f71782f | Family_Registration        | b49faa39-5e24-4de8-bf3f-cdda6f320179 | 64ae21ed-e60f-4ab0-8060-335375f8482b
 7b4b2426-67e8-47ab-a233-9ebc0a43bf72 | Family_Member_Registration | b49faa39-5e24-4de8-bf3f-cdda6f320179 | 64ae21ed-e60f-4ab0-8060-335375f8482b
(5 rows)
```

**Comment by Rkareko** [comment]
The [event](https://reveal-th-preview.smartregister.org/opensrp/rest/event/findById?id=685f019c-01b7-4812-b80f-277321f6f8f3) referenced in the` plan useContext opensrpEventId` field has a different value in the `planIdentifier` value i.e `1bf9184e-6ac4-49d1-8a9d-fb6e5af68f99`

`{
  "type": "Event",
  "dateCreated": "2021-12-07T10:14:18.721Z",
  "serverVersion": 1607066372486,
  "identifiers": {},
  "baseEntityId": "b49faa39-5e24-4de8-bf3f-cdda6f320179",
  "locationId": "b49faa39-5e24-4de8-bf3f-cdda6f320179",
  "eventDate": "2021-12-07T00:00:00.000Z",
  "eventType": "Case_Details",
  "formSubmissionId": "5fecc570-dbfa-43cb-a7b5-60c54d5678ba",
  "providerId": "nifi-user",
  "duration": 0,
  "obs": [],
  "entityType": "Case_Details",
  "details": {
    "id": "3761",
    "age": "69",
    "bfid": "1206030007",
    "flag": "Site",
    "species": "M",
    "surname": "QA Test",
    "focus_id": "b49faa39-5e24-4de8-bf3f-cdda6f320179",
    "first_name": "Madrine",
    "focus_name": "เมืองทอง(Site)-4",
    "case_number": "2401224081141261323",
    "family_name": "Madrine",
    "focus_reason": "Investigation",
    "focus_status": "A1",
    "house_number": "H321",
    "planIdentifier": "1bf9184e-6ac4-49d1-8a9d-fb6e5af68f99",
    "ep1_create_date": "2021-12-07T00:00:00.000+0000",
    "ep3_create_date": "2021-12-07T00:00:00.000+0000",
    "investigtion_date": "2021-12-07T00:00:00.000+0000",
    "case_classification": "Bz"
  },
  "version": 1557860282617,
  "teamId": " ",
  "_id": "685f019c-01b7-4812-b80f-277321f6f8f3",
  "_rev": "v1"
}`

**Comment by Rkareko** [comment]
@ciremusyoka cc @samkanga concerning `Case Details` events
1. At what point is the `details.planIdentifier` value populated
2. Where is the `planIdentifier` retrieved from?

**Comment by ciremusyoka** [comment]
@Rkareko the `planIdentifier` is a UUID generated when creating an event on Nifi. 

Note: When plans were generated by Nifi, the `details.planIdentifier`  was picked and used as the plan id.

**Comment by samkanga** [comment]
Closing this ticket as this is now resolved.
