### ISSUE TITLE
App Crashing on clicking Detect Case for Case confirmation plan on Thai-Prev

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1547]
An issue has been noted on the Thailand preview instance, where the App is crashing on clicking "Detect case".
app V5.3.26 rc8
user : test77

Steps.

- install the app
- sync data.
- add a new structure
- add a new family member
- click on detect case.
- Observe how that app is crashing and one has to login again.

this has been tested on the structure below. 
![image](https://user-images.githubusercontent.com/84722169/145965682-b44e28f6-7e85-4d3d-badc-768193e43846.png)

**Comment by Rkareko** [comment]
@samkanga @madrinekariuki It appears that the `case_confirmation` json form has being updated by removing the `familyMember` json field. This drop-down field is populated by the list of family members and is used to select the family member that is the index. The form with the field can be found [here on github](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/case_confirmation.json)

 ```
     {
        "key": "familyMember",
        "openmrs_entity_parent": "",
        "openmrs_entity": "",
        "openmrs_entity_id": "",
        "type": "native_radio",
        "label": "Select Family Member that is the Index Case",
        "value": "Yes",
        "v_required": {
          "value": "true",
          "err": "Please choose family member who is the index case"
        }
      }
```

**Comment by madrinekariuki** [comment]
case_confirmation json  for config was updated and this resolved the issue
