### ISSUE TITLE
Restricting leading Zero on Thailand Android Client

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1554]
CHAI ave reached out asking if Form configuration can be used to restrict entry of leading zeros on the android client forms. See sample leading zero below:

![image](https://user-images.githubusercontent.com/5908630/153877288-4b1739d2-7e70-473e-a332-2c74109829ce.png)

**Comment by Rkareko** [comment]
@madrinekariuki cc @samkanga we need to test whether use of regex to restrict entry of leading zeros on the android client forms. This [question](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/bednet_distribution.json#L133-L158) can be used to test this.

**How to test**
1. Using the current forms verify that it's possible to enter `01` as an answer for `The total number of existing LLINs is required`
2. Download the [bednet form](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/thailand_en_bednet_distribution.json) and add the regex epression to the `The total number of existing LLINs is required` question. The field should now looak like  

```
      {
        "key": "existingLLINs",
        "openmrs_entity_parent": "",
        "openmrs_entity": "",
        "openmrs_entity_id": "",
        "type": "edit_text",
        "hint": "How many existing LLINs?",
        "edit_type": "number",
        "v_required": {
          "value": true,
          "err": "The total number of existing LLINs is required"
        },
        "v_numeric": {
          "value": "true",
          "err": "Must be a number"
        },
        "v_min": {
          "value": "0",
          "err": "Must be greater than or equal to 0"
        },
        "relevance": {
          "step1:eligibleForNet": {
            "type": "string",
            "ex": "equalTo(., \"1\")"
          }
        },
"v_regex": {
          "value": "^([1-9][0-9]{0,2}|0)$",
          "err": "Number must not start with a zero"
        }
      }
```

This is the regex used to restrict entry of zero's before integers

```
"v_regex": {
          "value": "^([1-9][0-9]{0,2}|0)$",
          "err": "Number must not start with a zero"
        }
```

4. Upload the bednet form via form config
5. Sync the android app and test whether the restriction takes effect

**Comment by madrinekariuki** [comment]
@Rkareko 
please confirm the expected results after the restriction. 
see current findings on the screenshot below:
- The error is not showing when I input a value the starts with zero.
- Also confirm, if the` The total number of existing LLINs` is required is actually zero will inputting `0` prompt the error message?

screenshot:
![image](https://user-images.githubusercontent.com/84722169/154049903-52f86448-c7cb-4fc8-a6fe-96eb92093188.png)

**Comment by madrinekariuki** [comment]
@Rkareko 
I have retested this and It has passed QA.
android apk used. v5.3.29 th-en
user: test77

steps:
Followed these highlighted steps.

Observation:
- After the changes and syncing data, when you open the form you get the message, `form has updates` as expected.
- On the Question `The total number of existing LLINs is required`, when you put a digit starting with zero e.g `01` one gets an error, `Number must not start with a zero`.
- when you input the digit 0 or any other number e.g 1,2,3 etc. there is no error message.

Screenshots:
![image](https://user-images.githubusercontent.com/84722169/154073429-6ee11421-9007-4555-a671-183e18edf5ad.png)
