### ISSUE TITLE
Investigate the FI outer circle radius size

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#204]

**Comment by Rkareko** [comment]
CURRENT SITUATION
The FI (Family Investigations) outer circle radius size appears to be approximately twice the number required.

ACTIONS TO TAKE
Investigate why the org.smartregister.reveal.util.Utils#calculateZoomLevelRadius() function returns an inaccurate value for the the radius at any zoom level.
Find an appropriate fix for this issue.

EXPECTED OUTCOME
The radius is calculated corrected and the FI outer circle is drawn corretly at all zoom levels.

**Comment by githengi** [comment]
Drawing outer circle for all zoom levels to be resolved in #207
