### ISSUE TITLE
Thai names aren't displaying correctly

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#213]
Adding new members shows up in Task List as "????????"
This is an issue with encoding thai characters in Reveal from the Android keyboard. Please check and figure out how to ensure Thai names are displaying correctly

**Comment by githengi** [comment]
This issues is now resolved after deploying [https://github.com/OpenSRP/opensrp-server-web/pull/59](https://github.com/OpenSRP/opensrp-server-web/pull/59).

Now the endpoints will return content already encoded in UTF8

Clear storage and sync again, the names should now show correctly
