### ISSUE TITLE
Modify Thailand Forms based on field feedback

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#216]
We need to modify the Thailand forms based on the feedback from the field testing last week. The changes are outlined in this sheet: https://docs.google.com/spreadsheets/d/1HJ-0vEWIFP0NA_XjSztvR3TSjfaf8KEWSjmKk-F3yZ4/edit#gid=1558656423

**Comment by craigappl** [comment]
@githengi , the fields have been updated in the data dictionary and they have been translated in Thai.

1) Updated Data Dictionary Sheets (All sheets in Red) https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=1900664504
2) Updated Thai Translations: https://docs.google.com/spreadsheets/d/1egdYB8MBk22s4SedEG6bnpBzwy8SOJ8g0yKoH1epFvQ/edit#gid=0

**Comment by githengi** [comment]
Update the error messages from the file [https://docs.google.com/spreadsheets/d/1iGuiF8p1aosnIRo8j_eVS084zUoV7QV4LlWVQ_PRSfo/edit#gid=0](https://docs.google.com/spreadsheets/d/1iGuiF8p1aosnIRo8j_eVS084zUoV7QV4LlWVQ_PRSfo/edit#gid=0)
