### ISSUE TITLE
Change Mosquito Breeding Site and Larval Dipping "Edit" buttons

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#235]
The Thai team would like us to change the button in the cards for mosquito breeding sites and mosquito collection points to say "Edit Data" in Thai instead of "Record larval dipping/mosquito collection"
Thai Translation: 
แก้ไขข้อมูล
English String: Edit Data

![image](https://user-images.githubusercontent.com/6067053/59468055-00fbb080-8de6-11e9-93ba-87bceeb4e9f6.png)

![image](https://user-images.githubusercontent.com/6067053/59468066-0658fb00-8de6-11e9-8618-d23927139496.png)

**Comment by githengi** [comment]
@craigappl we are only changing the thai  translation only ?

**Comment by craigappl** [comment]
@githengi , Yes
