### ISSUE TITLE
Build Thai API with different Mapbox API Key

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#242]
Thailand has a different Mapbox API key. We currently use the Ona Mapbox API Key. We need to have the ability to build the Thailand App using a new Mapbox API Key that's specific to Thailand.

**Comment by githengi** [comment]
@craigappl We are currently building APKs with the Thailand APK Mapbox key

**Comment by githengi** [comment]
Closing the Issue since we already build the APK with Thailand Key
