### ISSUE TITLE
RVL-310 Bednet Distribution Form Number of people living in structure not working

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#281]
In the bednet distribution form, the constraint for # people living in structure can’t be more than the # registered in family module is not working consistently.

**Comment by githengi** [comment]
@craigappl please provide specific cases when its not working.

**Comment by craigappl** [comment]
- It's likely a case of the bednet distribution task being opened from the list view, not the family view.
- We currently block save if this number is 0 or more than the number of family members who are currently registered.
- This causes a dependency between the tasks where you can't complete a bednet distribution task without registering family members

Fix options:
- Block entry of the bednet distribution task from the list view
- Pop-up a box when the form is opened stating that a family hasn't been registered and we can't complete this form. This is dependent on having a register family task.
- Don't block the save of the form. Instead, shift the feature to display info for the user instead using relevance. So, "There are a total of 0 members registered for this family and you entered 3. Please register the family members after this."

**Comment by githengi** [comment]
@craigappl has this been unblocked? Otherwise it should be moved to a future release

**Comment by craigappl** [comment]
It is not unblocked. We will move it to 2.2.3.

**Comment by craigappl** [comment]
@githengi I heard back from CHAI and Akros

We need to Block entry of the bednet distribution task from the list view.
