### ISSUE TITLE
Completing a Focus Investigation

### ISSUE THREAD

**Issue by mlberg** [OpenSRP/opensrp-client-reveal#283]
Support the ability to complete or close a focus investigation.

<img width="554" alt="Screen Shot 2019-07-03 at 11 54 13 PM" src="https://user-images.githubusercontent.com/42673455/60638867-13b64380-9dee-11e9-86e5-6e725158205e.png">

The form will provide the ability to:

- Suggest a reclassification for the focus
- Report driver of transmission

Upon completion the status of the focus needs to be changed to inactive.

@craigappl @githengi Can you help provide suggestions on the following

- What the classification status are
- How we should handle the submission to update the plan.

**Comment by githengi** [comment]
@mlberg the case classification should be eithe rof A1,A2,B1, or B2.

The plan can be updated by sending a PUT with plan JSON to [Plan Endpoint on OpenSRP](https://reveal-stage.smartregister.org/opensrp/rest/plans/)
