### ISSUE TITLE
Case Confirmation Form Save Crashes App

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#289]
The app crashes when you save the case confirmation form. When you login again, the case confirmation displays as complete. This is likely a crash in a post save action.

**Comment by githengi** [comment]
Closed by https://github.com/OpenSRP/opensrp-client-reveal/pull/258 
commit https://github.com/OpenSRP/opensrp-client-reveal/pull/258/commits/151173cc31b2833345c6c45ae5591584d50a8d1c
