### ISSUE TITLE
RVL-124, RVL-141 & RVL-142: View and Edit Forms in Family Module

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#306]
We need to add the ability to view completed forms and edit them in the family module. Currently, when we complete a task for bednet distribution, blood screening and case confirmation users are not able to view the information that was submitted. There is a working specification on confluence: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1148256307/Viewing+and+Editing%3A+Completed+Forms

**Comment by craigappl** [comment]
@rowo , this will need design starting next week.

**Comment by rowo** [comment]
@craigappl Is this based on how editing works for answer-once fields that are editable in the WHO ANC app or editing registration information? Check out https://github.com/OpenSRP/opensrp-client-anc/issues/149. What I'm seeing here (and correct me if I'm wrong) is this is like that except we render a view state of the full form. Then to see the form with active fields, the user has to hit an "Edit" button. Then the editable fields get active and you hit Save to resubmit the edited form.

**Comment by craigappl** [comment]
@rowo I haven't scoped it, but I don't think it's that complex. We currently don't have a way in the family task view to view forms and edit them. I think we need to add the ability to click on completed tasks, view them and edit the values that were submitted.

**Comment by rowo** [comment]
@craigappl For the actual editing flow, the editing registration info on CHW or any apps aren't complex either so was just wondering about if you saw them. I think here we are just adding that extra initial view step since maybe this interaction will be done more often than editing registration info so we want it to be nicer? Is that the thinking?

**Comment by rowo** [comment]
- Would all complete forms be clickable to view what was submitted? 
- What is the interaction to re-complete mosquito breeding site and mosquito collection site forms multiple times?
- Point is there's some sort of differentiation between uneditable forms, editable forms, editable forms that have been edited, and forms that can be re-completed numerous times and I'm just wondering how that happens.
- I don't get why a user would ever see an edit and save button together. Is that correct?

**Comment by rowo** [comment]
@craigappl 
1. We're proposing to have the completed task form state = to the edit state (the filled out form), like we are doing with registration info.
2. In OpenSRP we handle editable fields with an edit icon next to the field in question. So we should probably do the same in Reveal mobile. Below the rows show button states for "not done", "completed, editable and edited", "completed and uneditable", and "completed and editable":
  ![House-Edit](https://user-images.githubusercontent.com/1584163/62179057-23577800-b319-11e9-9c5f-ece32893af4e.png)

**Comment by rowo** [comment]
Following this up with more detail.

Home profile
<img src="https://user-images.githubusercontent.com/1584163/65400553-e3e55f00-dd90-11e9-872e-8a849a154830.png" width="300">
- Editable forms get an "edit" icon. If a form is edited, the date of edit is displayed, with most recent date shown.
- Viewable forms get an eyeball.
- Tapping anywhere on the icon or the status (i.e. "Complete") should open up the form.

Viewable-only form
<img src="https://user-images.githubusercontent.com/1584163/65400551-e3e55f00-dd90-11e9-95d8-f4051f5cb1e0.png" width="300">
- A viewable form opens up without a "Save" button

Editable form
<img src="https://user-images.githubusercontent.com/1584163/65400552-e3e55f00-dd90-11e9-8d8d-d8ee6655f1fe.png" width="300">
- An editable form opens up with a disabled "Save" button that gets enabled when a change is made. If this is complicated, just show an active "Save" button.
- If the X is closed, show a standard "lose your changes" confirmation i.e.
<img src="https://user-images.githubusercontent.com/1584163/65401046-a209e800-dd93-11e9-9e5b-52930665543b.png" width="300"> where the content is "Discard edits" and options are "Cancel" and "Discard"

**Comment by githengi** [comment]
@craigappl @mberg there are business rules defined when a task is not editable. Maybe we use plan end date or task end when its not possible to edit but one can only view
