### ISSUE TITLE
RVL-121: Show house number in list view

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#307]
Thailand has requested that we display the house number in the list view.

We need to decide how we implement this:
1. We could add a house number to the location.properties and update the location everytime we save the register family form
2. We could update the location entity in the Android client for each event that has been submitted and synced from the server to the client. (I expect this will be really challenging after a particular operational area has been active in Reveal for multiple years).

Updated View:
- [ ] Insert the house number to the left of the distance that's in grey with a label "House Number"
- [ ]  Do not display the label "House Number" if the location does not have a house number
- [ ] This should not impact unenumerated structures

**Comment by craigappl** [comment]
@githengi I recommend Option 1, what do you think?

@rowo , Does the updated view section make sense?

**Comment by armageddon** [comment]
@craigappl I dont think this is ready for dev - I will put together a scoping doc in confluence for this

**Comment by rowo** [comment]
@craigappl do you have a screenshot of what you are proposing?

**Comment by githengi** [comment]
> @githengi I recommend Option 1, what do you think?

Yes option 1 is better.

**Comment by githengi** [comment]
@craigappl please screenshot that @rowo is asking for so that we can schedule this issue

**Comment by craigappl** [comment]
@rowo please see the scoping document in confluence: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1150058501/Household+Number+and+IDs

The screenshot is on the right.

**Comment by rowo** [comment]
@craigappl 

Here's kind of what it looks like. I think this is okay, though the label "House Number" is pretty long. And also seems like you are already saying "[Name] House" so why repeat the word "House"? Would the # symbol work? Or just "Number"? Otherwise, if you feel strongly about that full term, I think it should be in sentence case, not title case.

<img src="https://user-images.githubusercontent.com/1584163/61924102-5cb47000-af34-11e9-925d-b7538659a71b.png" width="425">

**Comment by Rkareko** [comment]
@craigappl 
Could you please address @rowo 's concerns regarding the wording to use i.e 
- House Number 12
- #12
- House number 12
- Number 12

**Comment by craigappl** [comment]
@Rkareko and @rowo ,

- [ ] We need to use the British English abbreviation which is "No." The string would be "No. 12"
- [ ] We need to make sure that this string is translatable into Thai.
(I will get the Thai translation)
