### ISSUE TITLE
RVL-300 Make sure APKs release with the correct server URL

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#320]
The THAI APK released with an IP address as the server URL in the 2.2.1 release. Please verify that this doesn't happen in the 2.2.2 release

**Comment by githengi** [comment]
@craigappl not able to reproduce this the version 2.2.1 APK

**Comment by craigappl** [comment]
I have asked if they can provide us more information on the version of Android and how they chose to install the app.
