### ISSUE TITLE
Implement New IRS Status Color > Partially Sprayed Structure

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#364]
The Namibia team would like to implement a partially sprayed status for IRS work in the field. This partially sprayed status will be colored orange, the same as what we currently have for select a structure.

Definition:
'Partially Sprayed' = the total number of eligible rooms sprayed is 'more than 0' and 'less than the total number of eligible rooms' in that structure or household.

Form Changes
We need to add a value to the IRS spray forms that calculate the partially sprayed status and update the business_status of the task based on this value.

We need to make the following changes in the following forms:

- [ ] 

For Namibia, we have a dependency on the

**Comment by githengi** [comment]
@craigappl is this to implemented on on the Namibia spray form?

Can this be defined using the data dictionary fields

Can we use  `number_unsprayed` >0 or `number_unsprayed_mopup` > 0 from the Namibia Spray form

ie. Sprayable = number_sprayable
