### ISSUE TITLE
When user wants add a structure in their location, the structure is added to different cordinates

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#397]
When user wants add a structure in their location, the structure is added to different cordinates

**Comment by githengi** [comment]
Based on Jira Issue  https://smartregister.atlassian.net/browse/RVL-33

**Comment by anniecmartin** [comment]
FYI Sam, this issue persists in 2.3.2, as described in the linked Jira ticket.
https://smartregister.atlassian.net/browse/RVL-33

**Comment by githengi** [comment]
@anniecmartin if the locate me is active, i.e its blue the if you move the map, the locate me will be returning the map to your location until its disabled.

The locate me acts as a toggle, i.e you click once its enabled, you click again its disabled
