### ISSUE TITLE
Business status colors do not reflect mop-up activity

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#399]
Business status colors do not reflect mop-up activity. If i enter 2/4 structures sprayed on First visit and another 2/4 on a mop-up visit for 4/4 total, business status still displays as Partially Sprayed.

There was an error on business status calculation update to the one tagged on Jira issue  [https://smartregister.atlassian.net/browse/RVL-366](https://smartregister.atlassian.net/browse/RVL-366)

**Comment by derekpollard** [comment]
@githengi can't test as it won't allow me to save the form. It brings up a form error on access to household question however this can't be changed and shouldn't be changed. See slack #forms for screenshot.
