### ISSUE TITLE
Make fields Not editable when opening Spray form after previous submission

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#408]
Make below fields Not editable when opening Spray form after previous submission

- householdAccessible
- ableToSprayFirst
- mopUpVisit

This is per [Namibia data dictionary for spray form](https://docs.google.com/spreadsheets/d/1blcwQmcO1lFZlHPD8lrKWnQJ6rsOtDmLF6-VI405Juc/edit#gid=1201504545)

Based on https://smartregister.atlassian.net/browse/RVL-364

**Comment by derekpollard** [comment]
@githengi does this relate to the not save issue?

**Comment by githengi** [comment]
No
