### ISSUE TITLE
RVL-396 Namibia Spray Form Validation issue due to read only field

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#414]
When editing a spray form in Namibia, we removed the ability to edit the householdAccessible field. This caused a situation where the validation rules are still being applied, but they don't see the input on the field because it's read only.

Steps to reproduce:
- Create a structure
- Add a spray form with householdAccessible = yes, but ableToSprayFirstVisit = No
- Save the form
- Open the form again and fill out the mopup field
- Try to save the form and validation errors will show up that the householdAccessible field doesn't pass because it's now read only.

- [x] We need to check this for all read only fields and make a blanket fix.
(https://smartregister.atlassian.net/browse/RVL-396)

**Comment by githengi** [comment]
Closing the issues since the Jira issue has been closed. Resolved on version 2.4.2
