### ISSUE TITLE
RVL-33 (Reopened) - Needs to be reviewed and updated

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#416]
I'm marking this as needing to be complete because it was reopened in Reveal 2.4.2. I'm not able to follow the thread, but I hope @githengi knows what needs to be done: https://smartregister.atlassian.net/browse/RVL-33

**Comment by githengi** [comment]
Closing since the Jira ticket has also been closed.

Changes to be done on #418
