### ISSUE TITLE
How many active Plans  should be supported on the Android

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#434]
How many active Plans  should be supported on the Android.

The Tak1 has about 57 active plans

**Comment by githengi** [comment]
This is important so that we are able device a strategy for sync if a user can have more than 20 plans

**Comment by craigappl** [comment]
@githengi , let's put a cap at 20 right now and I will communicate this to the project partners.

**Comment by githengi** [comment]
Closing this. We shall migrate plans to use POST to sync so that as many parameters can be sent
