### ISSUE TITLE
Implement Offline map download

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#442]

**Comment by mberg** [comment]
I like the google maps approach.

Ideally, we can go to a page.  It'll take you to a list of the jurisdictions in your plan.  You can check the box for the ones you want to download.  We want to support batch downloads in advance.

We don't need to show a preview of the map.  It would be cool if we could calculate (can be a later phase issue) the estimated size of the download.

**Comment by rowo** [comment]
Slack from Matt: "I think just the areas that are in their plans is an ok starting point... since they can't load an area that's not in the plan. The plan generates a list of places they can visit right now" Meaning, only maps for the campaign areas are available for download.

**Comment by githengi** [comment]
@rowo @mberg that makes sense. However the locations on a plan can be very many for IRS.

Assuming the plan has all the locations in district, we would be downloading very tiles.

**Comment by rowo** [comment]
@githengi Just to clarify, the user isn't being forced to download all of the areas. Here, the question is about what areas are even available to download i.e. which areas show up in the list that you can click to download.

**Comment by rowo** [comment]
I wonder if we should prioritize multiple select or having single pages for each map (like Google Maps). Not having individual pages for the map is making things complicated. @mberg Is there any reason we need to have a multiple select vs. just going to each map and downloading them?

These screens might make it clearer:

![Menu - IRS](https://user-images.githubusercontent.com/1584163/65009608-4b0b9b00-d8db-11e9-86f1-1edb513a5e06.png)

![Offline Map Dialog - Available](https://user-images.githubusercontent.com/1584163/65009613-519a1280-d8db-11e9-9586-9c0dc82e88e4.png)
- Having checkboxes makes this screen like Get Blank Forms in ODK Collect (https://docs.opendatakit.org/_images/get-blank-form.png). Problem with this is you have to either build support for both downloading after select-multiple and after select-one. So either we find a way to handle that on this one view or we support two workflows.

![Offline Map Dialog - Downloaded](https://user-images.githubusercontent.com/1584163/65009611-4e9f2200-d8db-11e9-8d2a-84a2e87afa1e.png)

**Comment by rowo** [comment]
@githengi @ekigamba Hello. Seems right now the goal is trying to get something out fast and straightforward to build. To that end, I have a some questions that reference the below screens. 

1) Is it easier to separate out the downloaded from the not-downloaded (i.e. available)? In the first two images, there are tabs. In the third image, everything is on one page. Is one better than the other from an effort standpoint?
2) For the specific row styles, are checkboxes in he first two images easier where you check a row and a floating action button appears easy to do vs. in the third image where you have one action on the row (to download), then when something is downloaded, you can either update or delete (but if we don't want to do update right now that's okay too)

<img src="https://user-images.githubusercontent.com/1584163/65278900-0eb68580-dafb-11e9-9085-61f65c6c9c6e.png" width="300"> <img src="https://user-images.githubusercontent.com/1584163/65278898-0e1def00-dafb-11e9-8ebb-ac91a3404bdf.png" width="300">

<img src="https://user-images.githubusercontent.com/1584163/65278899-0eb68580-dafb-11e9-8ce8-6d6e6b30ed12.png" width="300">

**Comment by githengi** [comment]
@rowo the effort for both options are also most similar. However the 1st option a bit easier to implement

**Comment by ekigamba** [comment]
@rowo Yea, the first option seems easier.

However, the SDK can't tell how big a download will be in size (i.e. GB, MB). We can only tell the download size after the download is complete. However we can tell the download progress.

One question, the second option shows all the possible states of downloaded maps, downloading maps & available for download maps. Are these states shown in the first option? and how would that be shown especially for a downloading map? Or would we just make it unavailable for downloading?

**Comment by rowo** [comment]
@githengi @ekigamba so these screens aren't meant to represent independent options. They show two elements, one is navigation (tabs vs. single list) and second is map download interaction (download button on each row vs. checkbox with button that appears).

Sounds like it's easier to do tabs for separating out downloaded vs. not downloaded (i.e. available) maps and also checkboxes. @ekigamba I will show the state for in-progress download which is the only thing missing. Right now it shows the lists for available and downloaded. **Question: do you think the in progress downloads should stay in the available list or the downloaded list? And where would be the easiest place to put a "cancel/stop download" button in that case?**

**Comment by ekigamba** [comment]
@rowo 
Yea, its easier to do tabs

**Question: do you think the in-progress downloads should stay in the available list or move to the downloaded list?**  I am actually not sure where that would be

**Comment by rowo** [comment]
@ekigamba With focus on doing this feature quickly:
- If we can put the stop button in the row itself as seen on the third/bottom mockup, it should stay in the available list. 
- If the progress appears as a notification and the stop download button appears there like in https://github.com/OpenSRP/opensrp-client-reveal/issues/442#issuecomment-530727254, it should also stay in the available list. In that case the row checkbox would become disabled and the row might say "downloading"
- If the stop button needs to happen via the checkbox interaction, I guess I would move the row into the Downloaded tab and do something where a user can't select downloaded and in-progress maps at the same time. When in-progress maps are selected, it would show a "stop download" button. This is a bit awkward I think.

**Comment by rowo** [comment]
Here is a look at direction 1 in https://github.com/OpenSRP/opensrp-client-reveal/issues/442#issuecomment-533605824 with updates from previous comments:
<img src="https://user-images.githubusercontent.com/1584163/65348249-ad4fee80-dbae-11e9-8cd0-c91d9f00007a.png" width="300">
<img src="https://user-images.githubusercontent.com/1584163/65348259-b0e37580-dbae-11e9-8ae7-4652dfaaa662.png" width="300">
<img src="https://user-images.githubusercontent.com/1584163/65348260-b0e37580-dbae-11e9-9325-8bb296b5f00f.png" width="300">
<img src="https://user-images.githubusercontent.com/1584163/65348262-b0e37580-dbae-11e9-8325-fb2b84593c14.png" width="300">
<img src="https://user-images.githubusercontent.com/1584163/65348261-b0e37580-dbae-11e9-965a-b50db7af39cc.png" width="300">
<img src="https://user-images.githubusercontent.com/1584163/65348258-b0e37580-dbae-11e9-9b63-d45853f9fa9e.png" width="300">
<img src="https://user-images.githubusercontent.com/1584163/65348257-b0e37580-dbae-11e9-94e0-022a26027e22.png" width="300">

**Comment by ekigamba** [comment]
@rowo 

1. 
> If the stop button needs to happen via the checkbox interaction, I guess I would move the row into the Downloaded tab and do something where a user can't select downloaded and in-progress maps at the same time. When in-progress maps are selected, it would show a "stop download" button. This is a bit awkward I think.

I think for simplicity we can leave this out, use option2, and this can easily be added later on with the full implementation, @Rkareko ? What do you think about the stop download implementation at https://github.com/OpenSRP/opensrp-client-reveal/issues/442#issuecomment-533605824

2. On the updated design here https://github.com/OpenSRP/opensrp-client-reveal/issues/442#issuecomment-533653387
I also think that the above design is the most minimal, covers all the cases that we require & is a good initial implementation.

**Comment by rowo** [comment]
@Rkareko @ekigamba I updated my thinking around the stop in the comment after. I'm cool with no stop button in the rows right now. If it's already built already into the general Android notification, that works well enough.
