### ISSUE TITLE
MBTile support

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client-reveal#448]
Mbtiles support is required in Reveal client in the cases where download caching isn't an option. 

Mapbox SDK has support for this so it's just a matter of enabling the geowidget to allow us to select an mbtile as a basemap.

Proposed implementation

- Create a folder in the android media folder accessible to Reveal called mbtiles. This is where files will be loaded to the phone.  It will be ideal if this can be stored on an SD card.
- The person configuring Reveal would load on the user's device the mbtiles that are relevant for the user.   Eg. the mbtiles that cover the assigned locations where they are working.  These files will be named in a way that make sense to the end user.  Eg. Ruhiira Village (this may cover several spray areas)
- The reveal interface will provide a layer selector.  This will link to the mapbox/digital globe basemap in addition to the mbtile files in the folder.

The end user can then select which basemap they want.  It will be up to them to select the right basemap (powered by mbtiles) for the area they are in.

Design needs, the main thing is we need to add a layer selector in the UI.  @rowo can you please prioritize looking at this.

**Comment by rowo** [comment]
@mberg so would you consider this a different option for an [Offline map](https://github.com/OpenSRP/opensrp-client-reveal/issues/442#issuecomment-533653387) but serving the same purpose — meaning the likely scenario is, before you go out to the field, you have this set of files named in a way they are auto associated with areas, then you select which ones you want to "activate" in the app and when you tap those areas, they use the Mbtiles instead of trying to download?

I want to understand:
- How does a user would decide that download caching isn't an option ?
- Would you ever use Mbtiles if you have a connection? If so, is this something you would turn on and off a few times an hour (switching to the live map for some reason) and why would someone do that?

**Comment by mberg** [comment]
This is a different option to offline map.   This is a scenerio where i want to access an offline accessible basemap.

Caching would still apply and be accessible if you use the default basemap provided by digital globe / mapbox.

This would be one option always available it the layer selector.   Yes we want it in scenarios where we have connectivity.  The tiles can be generated from imagery (eg. Drone) that may not be accessible online in a map service.  So there are scenarios when you have connectivity that you'll want to do it.

**Comment by rowo** [comment]
So reading through it again, seems like it’s a layer selector on that map and the same files are available for every area. I guess they aren’t the default option when you initially choose an area, but the selection should be saved across areas and not reset.

**Comment by rowo** [comment]
@mberg @githengi 
Initially I was thinking this is related to offline maps in terms of not being changed too often so I thought it worked in the hamburger menu inside a sort of "map settings" item, but seems like it makes more sense to long term plans to be an actual layer selector on the map itself if we are going to explore adding other maps and layer types. 

For now the logic should be that if there is more than one map layer available, then the selector shows up. If not, it does not appear.

I don't quite know the relationship of this layer selector with offline maps yet. For example, if we are on Area A and there's an mbtile, an available offline map and the default mapbox layer, would the offline map only show when the default mapbox layer is selected?

**Comment by githengi** [comment]
@rowo I think the layer selector should only be used to switch the base layers on the map. E.g one can select between Mbtiles, Digital globe or Mapbox satellite for Reveal. 
When one selects one of these layers then the base layer is activated on the map.
Below is an example of the current functionality in Geowidget that demonstrates the ability to switch between mapbox  satellite and street layers
![image](https://user-images.githubusercontent.com/25123762/65667398-56cc2f80-e048-11e9-8a76-b255d375a1c3.png)

I would suggest we try to maintain the current look and feel as on GeoWidget for now

**Comment by rowo** [comment]
@githengi yes, I think we are on the same page as far as switching base layers. All of it looks good to me including the icon. Placement wise if we are using all four corners already I think stacking it near the "my location" icon is okay like shown in https://github.com/OpenSRP/opensrp-client-reveal/issues/448#issuecomment-535336436.

So as far as my question — I guess it's just verification that an offline map is tied only to the Mapbox layer, so will only show up when that basemap is selected.

**Comment by githengi** [comment]
Okay, I think the layers displayed will be the basemap layers only

**Comment by githengi** [comment]
@mberg The selector should display a name for each MBTile file on the device
