### ISSUE TITLE
RVL-303: Index Case Confirmation Issues

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#491]
There are a number of issues in RVL-303 that Christina has highlighted in her comments. @githengi can you pair program with Janette?

Here's her comment:
Still a problem - record screening task for that family member disappears. After going back to map view and opening the structure, the task comes back and shows complete

2. Still a problem - After confirming index case and then logging in from another device, the circle around index is not shown, the record screening task is not complete for that family member, and we can no longer detect the index case. Update - also same outcome when logging out on device and logging back in or selecting another plan.

3. Still a problem - After confirming index case, in List View, when “View Tasks” is clicked for that house, it shows the case classification details, instead of going to the tasks

4. Still a problem - structure name changed to Unenumerated Structure for the task (after a case is detected) - the ‘View Tasks’ goes pink. Verified that clicking this navigates to the case classification details.

5. NEW problem - the case classification details that are shown do not reflect the correct family details (i.e. ‘Christina Test’ was selected as the index case, but Jin20190909 Thomas 20190909 with case number 3339 is shown as the index case info). I assume this has to do with BIOPHICS integration info, but the information displayed under ‘Family Details’ & ‘Family Member Data’ should reflect the data entered in for that household (versus BIOPHICS info displayed under 'Case Classification Data')

**Comment by githengi** [comment]
also check https://smartregister.atlassian.net/browse/RVL-604

**Comment by githengi** [comment]
@craigappl #5 on the list above is not an issue on Reveal client it has got to do Nifi Integration or a user confirming a case on the person whose details dont match the index case details.

As per the current spec its not a requirement to validate that the index case details match with the person that is confirmed as the index case
