### ISSUE TITLE
Resize the card view for low resolution phones

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#51]
The card view for Showing the clicked structure details has a fixed height.

In phones with smaller screens or low resolution its bigger that half the screen. 

Whenever one clicks a structure the map focuses on the structure but its hidden by(beneath) card view 

To resolve this 

- [x] Resize the card view for low resolution phones or recalculating the focus so that  the clicked structure shows above the card view

**Comment by craigappl** [comment]
Passes QA
