### ISSUE TITLE
Populate Options for MDA forms

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#542]
Populate Options for MDA forms

- [x] Supervisor, Enumerator and CHW on Dispense form

- [x] Supervisor, Adherence officer on Adherence form

**Comment by derekpollard** [comment]
We are filtering:
1. District Managers on District
2. Akros Field Officers are not filtered
3. Coordinator, Enumerator, CHW and Adherence Officer on Catchment

**Comment by githengi** [comment]
@derekpollard thanks this is clear

**Comment by derekpollard** [comment]
@githengi I have complete the list. Please review and confirm all is ok. 

https://docs.google.com/spreadsheets/d/1RPokLRRndfVw_QkJHbrGhSmJ1ppKtZSuiZEDaiRs3gU/edit#gid=1326383009

**Comment by githengi** [comment]
closed by #547
