### ISSUE TITLE
Card doesn't wrap text appropriately when changing text size

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#55]
The card view doesn't adjust to changes in text size. Please update the card to adapt to changes in text size.

![whatsapp image 2019-01-08 at 16 13 28](https://user-images.githubusercontent.com/6067053/50835866-7b6c6400-1360-11e9-944d-47f7690b15f6.jpeg)

**Comment by craigappl** [comment]
@vincent-karuri or @githengi , I'm now getting an issue with the "Change Spray Status" button text at the largest font on my tablet.
![image](https://user-images.githubusercontent.com/6067053/51858191-f33b0800-22e8-11e9-913c-6286e6fe3849.png)

**Comment by vincent-karuri** [comment]
@craigappl will this be a requirement every time we have text fields?

To test that they appear ok when the font size is increased?

**Comment by craigappl** [comment]
Yes, we will need to test that.

**Comment by craigappl** [comment]
Passed QA
