### ISSUE TITLE
Thailand Production Server Cleaning Steps

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#554]
I want to document the steps we need to take to clean the Thailand Production server at the following URLs:

- reveal-th.smartregister.org
- nifi.reveal-th.smartregister.org
- superset.reveal-th.smartregister.org

Actions to be completed:
### OpenMRS
- [x] Delete all training users
- [x] Create all production users

### OpenSRP Server
- [x] Delete all tasks
- [x] Delete all events
- [x] Delete all clients
- [x] Delete all practitioners
- [x] Delete all practitionerRoles
- [x] Delete all assignedLocationsAndPlans
- [x] Delete all organizations
- [x] Delete all Plans
- [x] Delete all structures that were added during training (geometry Type = Point)

Verify
- [ ] Verify that the global_configurations in settings are appropriate

Create
- [x] Create all production organizations
- [x] Create all practitioners
- [x] Create all practitionerRoles

### Nifi
- [x] Update the practitioner table for automatic plan generation so that locations and teams are assigned correctly when a plan is generated from the UI
- [x] Clear out any queued items

### BIOPHICS MSSQL Server
- [x] Clear out all data

### Datawarehouse
- [x] Clear all data

### Superset
- [x] Remove all training users that have been created

### Web UI
- [x] Verify that all plans have been removed

**Comment by ukanga** [comment]
@craigappl @Wambere Where do we get information to help with loading:?

```
Create all production organizations
Create all practitioners
Create all practitionerRoles
```

**Comment by Wambere** [comment]
- Everything is defined here https://smartregister.atlassian.net/wiki/spaces/REV/pages/1195507713/Team+Management+Configuration#TeamManagementConfiguration-CreatelocationsinOpenMRSandUpdateRevealwithproperties.OpenMRS_Id

- https://nifi.reveal-th.smartregister.org/nifi/?processGroupId=d9757457-016d-1000-7f1a-fbb75d2b1da6&componentIds= might also be a nice place to check out. This is the processor group that I used for creation

**Comment by ukanga** [comment]
Done by @Wambere @craigappl @ukanga

**Comment by Wambere** [comment]
In this list of things to clean, also remember to clear the counters in nifi here https://nifi.reveal-th.smartregister.org/nifi/counters by clicking the little circle-ish arrow on the right. Reset everything to 0
