### ISSUE TITLE
OpenSRP User Account Session Store doesn't account for disabled accounts

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#57]
Administrators are able to disable accounts in the OpenMRS user interface. This makes an account unavailable for logging in.

The OpenSRP server seems to cache OpenMRS sessions once the user logs in through the OpenSRP server.

Due to this session caching, administrators are not able to disable an account in OpenMRS.

Steps to recreate:
- [ ] Login to the Reveal Android client as demoMTI2
- [ ] Logout
- [ ] OpenMRS and navigate to the user account for demoMTI2
- [ ] In the bottom of the screen, disable demoMTI2
- [ ] Open the Reveal app and login as demoMTI2 --> This currently logs in, but it shouldn't. The user should not be able to login at this point.

**Comment by githengi** [comment]
@craigappl Should we allow the data that may be on the device(collected offline) to be submitted to the opensrp server before logging off the user?

**Comment by craigappl** [comment]
Yes

**Comment by craigappl** [comment]
@githengi, Is this ready for QA?

**Comment by githengi** [comment]
yes this is ready for QA

**Comment by githengi** [comment]
We are validating the user authorizations whenever there is an internet connection just before sync.
 
So in the test script the device should still be able to login locally if there is no internet connection.

To allow local login to work seamlessly when the device is offline we do not enforce network connection during login.

However when the device has internet connection, it will login locally even if user account is disabled, it it will verify authorization and if user account is disabled the user will be logged off.

If the user is logged and has an internet connection, during sync they will still be logged out and the below error will be displayed

**Comment by craigappl** [comment]
Passed QA
