### ISSUE TITLE
Ref app feedback

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#573]
I tested the ref app v 2.6.0 and found the following issues

- [x] The register family form and add family member form asks if people sleep outdoors and are Thai. Check the data dictionary. I don't think they should be there.
- [x] Blood screening and bednet distribution forms aren't saving. Try to complete these forms and the task doesn't change.
- [x] Please assign this user to the MACEPA MDA Plan so that we can test it.

**Comment by Rkareko** [comment]
@craigappl concerning the issues pointed out on the register family and add family member forms please update the data dictionary on https://docs.google.com/spreadsheets/d/1WvVT2fnMaTzVEgF3VPTGfIesb7ZZagDsEtc7_TNPnGY/edit#gid=1825851549 from line 47 and https://docs.google.com/spreadsheets/d/1WvVT2fnMaTzVEgF3VPTGfIesb7ZZagDsEtc7_TNPnGY/edit#gid=789806025 from line 36
