### ISSUE TITLE
Filters, sort and search

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-reveal#597]
UI design issue for https://smartregister.atlassian.net/wiki/spaces/REV/pages/1229586435/Android+Task+List+View+Filter+Search+Sort

**Comment by rowo** [comment]
@craigappl @mberg I started the basic UI to handle filters, taking the ANC approach and adapting so it could function within Reveal.

<img width="1159" alt="Screen Shot 2019-12-04 at 11 52 56 PM" src="https://user-images.githubusercontent.com/1584163/70205183-4643cf80-16f1-11ea-9fd9-db2ec86fb2c0.png">

- The main update was removing the intervention bar (the dark bar that said whether it was a focus investigation or irs) because it would've been too many layers at the top. Instead, I put the intervention type in the top bar, replacing the Reveal logo. 
- The map view would move the search bar to the top bar and make the filter a floating button.

@craigappl I think we need to talk more about the intervention unit filter and how that impacts the list and the reasons why it's a requirement. It seems very rough and maybe not considerate of how complex something like that can make things (especially if we have filters work across list and map, which is a product goal).

**Comment by craigappl** [comment]
Roger, can you define the way a user would know that there's a filter active? Currently, the my location button turns blue.

**Comment by rowo** [comment]
Here's an update. Top is no filters selected. Bottom is filters and search selected.

<img width="1137" alt="Screen Shot 2019-12-05 at 11 09 18 PM" src="https://user-images.githubusercontent.com/1584163/70295258-58d30d00-17b4-11ea-8b52-4b19bf213074.png">

<img width="1137" alt="Screen Shot 2019-12-05 at 11 09 24 PM" src="https://user-images.githubusercontent.com/1584163/70295261-5c669400-17b4-11ea-9a14-f33ac0510ae2.png">

**Comment by rowo** [comment]
Updated screens w/ handoff: https://marvelapp.com/512i9g5/screen/64667563

**Comment by githengi** [comment]
@craigappl please confirm how the filter for Invention unit works in FI/MDA plans e.g if someone selects Person what color code should be used. 
Also what actions should be exucuted when selects this task or structure on the map.
