### ISSUE TITLE
Mark Family Member Ineligible for Blood Screening Task

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#601]
- The user enters the household and navigates to the tasks tab
- The user taps the button with the blood screening task next to the person
- The first question asks “Is this person eligible for blood screening?” with the default value = Yes
  - All other fields are automatically displayed as is the current behaviour
- The user changes the value to “No”, all fields hide.
- The user taps submit
- The button turns to black with white text labeled “Ineligible”
- (No changes to the color logic of the structure)

**Comment by githengi** [comment]
closed by #605
