### ISSUE TITLE
BUG: Record Spray Status - Not Sprayed Other Reason still present - prevents form save 

### ISSUE THREAD

**Issue by armageddon** [OpenSRP/opensrp-client-reveal#61]
@githengi @craigappl 
Device: Samsung Galaxy Prime Pro 
OS: Android 7.1.1

Steps to Reproduce:
Touch a yellow structure
Touch Sprayable, Not Sprayed
Touch  Other 
Touch Sprayable, Sprayed
Expected: 'Not Sprayed Other Reason' disappears
Actual: 'Not Sprayed Other Reason' field remains. As it is mandatory the form cannot be saved

**Comment by craigappl** [comment]
Passed QA
