### ISSUE TITLE
FUNCTIONALITY: Record Spray Status - Household details are still mandatory even if spray is refused

### ISSUE THREAD

**Issue by armageddon** [OpenSRP/opensrp-client-reveal#62]
If a structure is marked Sprayable, Not Sprayed, details about the house are still mandatory (number of beds, head of household, nets etc). 
While the user can enter 99, this is not a great user experience, especially if the reason is 'Locked', 'Refused' or ' No one home'

@craigappl @githengi 
To discuss skip logic here, or perhaps a flag for 'Unable to ascertain' instead of having to enter 99.

**Comment by craigappl** [comment]
@armageddon (FYI @githengi ),

We based this form off of mSpray and we can change it if needed. This is really a question for the data dictionary. Does DSME publish a form with this type of skip logic available?

The Reveal Data Dictionary can be found [at this link](https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=396087476).

**Comment by craigappl** [comment]
Passed QA
