### ISSUE TITLE
RVL-404 Ability to reset or delete task information

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#637]
**Affected Task Types**
-     Blood Screening
-     Case Confirmation
-     IRS
-     Bednet Distribution
-     Mosquito Collection
-     Larval Dipping
-     PAOT

Tasks/Events will only be eligible to be reset if they meet the following:

    Not a family registration task type
    Not a family member registration task type
    Completion of task does not generate other tasks. Includes:
        MDA Dispense
        Family Reg
        Family Member Reg
    Event data has not yet synced to server
    If the event cannot be edited, it cannot be reset/deleted

**Archive Event Logic flow:**

1. After completing a form/event, press the “reset/clear” button for an eligible task. The user will see a warning “Are you sure you want to clear all data associated with this event? You will not be able to recover this data and this task will be marked as incomplete

2. Post-Clear actions

- [ ] Remove any data from the fields in the task; when you reopen the task, all fields will be blank

- [ ] Reset the task status to “Ready”. and generate a new event?

- [ ] Reset the business status to ‘not visited’ and change the colour on the map and task list appropriately

- [ ] Rerun any on-app indicators calculations and remove archived tasks from the numerator and denominator and add newly generated event to denominator

- [ ] Archive the data

3. If the task is has code:"Case Confirmation" we may be dealing with a special case where the case confirmation was assigned to the wrong person.

- [ ] Remove the target from the household

**Client UI (Views)**
For tasks in the family module:
- [ ] Add an ‘undo’ button next to the pencil icon in the family task view

For location-based tasks not in the family module (PAOT, Larval Dipping, Mosquito Collection):
- [ ] add ‘undo’ button on list view, next to the task status button

For non location-based tasks (BCC):
- [ ] add ‘undo’ button on list view, next to the task status button

For those tasks that are not eligible for reset:
- [ ] The ‘undo’ icon or ‘clear’ button would be grayed out

**General Android Client Logic**
- These changes should sync from the Android client to the server
- Archived events should no longer be considered in any sync activities between the client and server

**Comment by Rkareko** [comment]
@rowo cc @craigappl  Could you help with designing the look and feel for the 'undo' button both for tasks in the family register (Bednet distribution and Blood Screening) and the task register view (PAOT, Larval Dipping, Mosquito Collection, BCC) as described in the **Client UI (Views)** section above.

**Comment by Rkareko** [comment]
Family Profile view

![family_profile_tasks](https://user-images.githubusercontent.com/47570855/74330002-ed07b480-4da1-11ea-8ef3-8f6c329e79be.png)

**Comment by Rkareko** [comment]
Task Register view

![task_register](https://user-images.githubusercontent.com/47570855/74330008-eed17800-4da1-11ea-9b13-1a497c06f517.png)

**Comment by rowo** [comment]
Update from 12 Feb: @Rkareko and I chatted about using the Edit icon to throw a simple dialog with options to either edit the task form or undo the task since two buttons in that space would be too crazy.

I think this can apply to the register view as well.

The icon would have to be smart in terms of showing a dialog if both options are available. If it's just edit, then it would go to an editable form. If it's just Undo, then there would need to be a confirmation or double confirmation to verify the undo (since no one wants to fill out a form twice).
