### ISSUE TITLE
FUNCTIONALITY: Clicking structures that do not have linked tasks

### ISSUE THREAD

**Issue by armageddon** [OpenSRP/opensrp-client-reveal#64]
Structures that do not have tasks assigned should be in a different colour

The error message should also be more user friendly - or these structures should not be clickable
e.g. 'There is a problem with this structure - your supervisor will be notified'

Although this should never happen in the field, what happens if it does? Does the house get skipped?

@githengi @craigappl

**Comment by githengi** [comment]
We can display the structures in a different color. @rowo any suggestions?

For now without a task its not possible to perform an intervention unless a task is created for that structure.

**Comment by rowo** [comment]
Sam and I talked it over and came up with this approach:
- Treat structures without tasks in a new color
- Allow the user to perform an intervention (just like if the user added a new structure). This would involve verifying the existing structure details (not sure if we can do edits, @githengi?), then going to the task form.
- Update the messaging to explain the situation and perhaps potential conflicts

The potential problem with this approach is that we might get duplicate tasks if a task ends up being synced to that structure. However in the field, if we don't allow the user to do a task on the untasked structure, the user will just just create a duplicate new structure and do the task, so we'll end up with a duplicate structure and duplicate task.

**Comment by githengi** [comment]
@rowo we cannot be able to do edits on the structures that are of type polygons. 

Also for now we don't have a use case for editing the existing points

**Comment by githengi** [comment]
@armageddon @craigappl @rowo what is the final position on this issue?

**Comment by craigappl** [comment]
This is a temporary state that we need to address in Reveal Release 2.

In the mean time, we should:
1) Add a new color for structures without a task
2) Update the error message to reflect that this structure does not have a task assigned to it.
3) Address the ability to edit a structure in Reveal Release 2, which will have drastic improvements in the way data inputs are collected on a location.

**Comment by githengi** [comment]
@rowo Kindly recommend the color to be used for such structures

**Comment by armageddon** [comment]
How about Purple?

**Comment by craigappl** [comment]
100% black outline (like any other structure) plus a 75% transparent fill of #C7C7C7 
![screen shot 2019-01-25 at 2 23 48 pm](https://user-images.githubusercontent.com/6067053/51836775-3b8d0280-22b6-11e9-8ec1-9c77a0c99f50.png)

**Comment by armageddon** [comment]
fine with what @craigappl says

**Comment by craigappl** [comment]
Passed QA
