### ISSUE TITLE
Create a NTD Point Distribution plan 

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-reveal#677]
The user can generate a plan with a new plan type of "NTD Point Distribution." In this case, a school will be the point that is tied to an operational area. There will be just one school per operational area. 

Task generation will involve generating tasks against entities (children) linked to the distribution-point level. 

**Tasks:** 
- register child (not automated) 
- drug distribution (automated, but dependent on eligibility in [data dictionary](https://docs.google.com/spreadsheets/d/1T0f-LQA4QuAv6dzoS9tieiiJAhv2uYe9NxB55pCtdT0/edit?pli=1#gid=1743712526)) 
- report an adverse reaction (not automated)

Mocks from Roger: 
![Add NTD plan](https://user-images.githubusercontent.com/12836913/81139010-00e23300-8f19-11ea-84d4-1bc26a5efabb.png)

**Comment by cKellyDesign** [comment]
From the frontend, the webapp will need to:
- [ ] Create a Plan Definition via the Plan Form (_to be scoped_)
- [ ] `POST` the Plan Definition to an OpenSRP endpoint (which triggers backend Task Generation) via the OpenSRP Service Connector

**Comment by isabelcshaw** [comment]
Note on the UI around selecting distribution points: for the pilot, there will only be one school per Inkundla (district), so it would be feasible for the user to just select the Inkundla, but I'm not positive this will hold true at scale. 

Geographies / schools can be found here: 
https://docs.google.com/spreadsheets/d/1N5FaEDV8dj247ZPAIm9Ebio-0oyRQ2UZ/edit#gid=2092832762

**Comment by moshthepitt** [comment]
Fixed by #896
