### ISSUE TITLE
Add ability to upload a csv rosters (multiple) + download csv rosters  

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-reveal#679]
Using the CSV template, the user can upload a school roster. The system will run validations against this upload and show the user error messages. 

Once successfully uploaded, show message: "x out of y individuals were successfully uploaded."

The user will be able to upload as many rosters as they want. And the system will show them some basic information on these rosters (see below).

Because the user cannot manage individual children's information via the web, the user can only edit information in bulk or add children via additional csv uploads. (They cannot delete children so that there are no issues with live plans or reporting). 

In order to do this with as few duplicates as possible, we are asking the user to download the existing roster (they will be able to select the geographic level that makes the most sense for their use case), make their changes / additions, and re-upload it. This csv will have the reveal IDs for the existing children, and when the new upload is processed, the system will check for these IDs so that duplicate entities are not created.    

**Validations:** 
- Required fields
- Check schools against OAs in Reveal 
- Check that fields with dropdown select type, boolean type, numeric type and Yes/No type have valid entries

**Error messages:** 
- "Upload failed. Check your CSV to make sure all required fields are filled in."
- "Upload failed. Check field (field name) in your CSV to make sure it is a valid entry type."

Mocks from Roger: 
![Admin-Points of Interest-Schools](https://user-images.githubusercontent.com/12836913/81139056-3be46680-8f19-11ea-92f8-fb1ab7877626.png)

**Comment by rkodev** [comment]
@isabelcshaw as discussed we can have this done via NIFI. I will tag this as a canopy issue although I'll be able to help with the implementation if need be.

**Comment by cKellyDesign** [comment]
## Upload
@isabelcshaw @rkodev Is there any validation that should / needs to happen on the frontend before uploading the CSV to OpenSRP Endpoint?

### API Requirements
- [ ] `GET` a list of all Rosters (to render the page)
- [ ] `POST` a new CSV for validation / processing
    - [ ] This call's response should indicated success or error for the WebAp

## Download
This seems simple enough, the download link will simply be an API endpoint structured to retrieve the CSV formatted Roster.
- [ ] `GET` a Roster as CSV

**Comment by kahummer** [comment]
@moshthepitt  @isabelcshaw based on discussions we've had with @rkodev uploading the csv's without team name and team id won't sync with the android app. 
Suggested implementation
Add a team select field and the upload field to ensure sync with the android app.

**Comment by moshthepitt** [comment]
@rkodev @isabelcshaw could you describe this requirement in more detail?

- What do we need to send when uploading the csv?
- How are teams assigned for NTD?

**Comment by rkodev** [comment]
@moshthepitt in this case, we just need 1 team for the client. My assumption is that the CSV file contains a list of students in 1 school/location e.t.c and therefore the team that accesses this data will be the same. I thought it would be nice to add this data via a dropdown parameter instead of duplicating the entire row inside the csv file

**Comment by moshthepitt** [comment]
@rkodev cool so this would result in CSV + team_id + jurisdiction_id sent to the OpenSRP server?

Will the OpenSRP server then assign this team to the jurisdiction in question?   I want to be sure that when we do this, then navigating to this page https://web.reveal-stage.smartregister.org/assign will have the team auto-assigned to the jurisdiction in question (because OpenSRP server already did it).  Is this correct?

**Comment by rkodev** [comment]
@moshthepitt no, the team information will only be used to tag the events created during the client's import. My thoughts were, other than simply importing the data and associating these clients with that team, any other administration task will remain the same

**Comment by kahummer** [comment]
@rkodev It doesn't seem very labourious but based on the deadline we can opt having the data kwa csv for now. I'll look into adding the select as the last issue once we have the core stuff working

**Comment by rkodev** [comment]
@kahummer sure, Let's have it on the csv

**Comment by moshthepitt** [comment]
> the team information will only be used to tag the events created during the client's import. My thoughts were, other than simply importing the data and associating these clients with that team, any other administration task will remain the same

@kahummer I am not feeling great about having this proposed approach.  Basically it would mean that this team dropdown field on this upload page is completely decoupled from the existing team assignment  page.  i.e. there would be nothing preventing you from assigning the jurisdiction to one team and then choosing a completely different team when uploading the CSV.  We need to find a way to prevent this.  Please discuss with me before starting work on this part.

cc: @rkodev

**Comment by rkodev** [comment]
@moshthepitt can we filter out the team information per jurisdiction. Only allow the drop-down to display team information for teams already associated with the jurisdiction?

**Comment by moshthepitt** [comment]
> @moshthepitt can we filter out the team information per jurisdiction. Only allow the drop-down to display team information for teams already associated with the jurisdiction?

We can, and we should imho :)
