### ISSUE TITLE
RVL-119 Modify application logo/branding

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#709]
Issue detailed on https://smartregister.atlassian.net/browse/RVL-119 and https://smartregister.atlassian.net/browse/RVL-936

Description
Add Thailand Thailand BVBD logo to 
- Bottom right corner of the Thailand apk
- Bottom right corner of the OpenSRP server's login (Updated - The OpenSRP server login will remain as it is)

The current OpenSRP server login page 

![opensrp-server-logo](https://user-images.githubusercontent.com/47570855/79958260-63542180-848b-11ea-8ac1-3eef8738cb0e.png)

 The current Reveal app login page 

![reveal-client-login-screen](https://user-images.githubusercontent.com/47570855/79958185-4fa8bb00-848b-11ea-9473-5f3f671c20ec.png)

The BVBD logo (They provided a .gif image)

![LOGO_DVBD](https://user-images.githubusercontent.com/47570855/79960544-31908a00-848e-11ea-8b82-59d97ac97cc7.gif)

**Comment by Rkareko** [comment]
@rowo , @githengi , @craigappl cc @samkanga Please advice on how best to achieve the request for adding the BVBD logo / branding on the client and server login pages.

**Comment by craigappl** [comment]
@Rkareko , I updated some views that weren't saved in the original ticket. I will paste them here:

![Reveal_Android_Login_Screen_BVBD_Logo](https://user-images.githubusercontent.com/6067053/79977315-ed33c880-8452-11ea-8c04-08c7bcd9e598.png)

![Reveal_Web_UI_Login_Screen_BVBD_Logo_Large_Viewport](https://user-images.githubusercontent.com/6067053/79977320-f15fe600-8452-11ea-9ee2-d5c893082d52.png)
![Reveal_Web_UI_Login_Screen_BVBD_Logo_Small_Viewport](https://user-images.githubusercontent.com/6067053/79977322-f1f87c80-8452-11ea-9556-bb7cd9fc5081.png)

**Comment by githengi** [comment]
@craigappl in terms of standardization where DSME have a vision of using one Reveal for all countries that is configured server side. 
Should the icon be hidden for non Thailand builds assuming all other APK builds will use the same placement for additional icons.

For OpenSRP server we should standardize the placement for additional icons as this its needed to be configurable for any OpenSRP server in a similar way.

**Comment by samkanga** [comment]
@githengi on the question _Should the icon be hidden for non Thailand builds assuming all other APK builds will use the same placement for additional icons._, its **Yes**.
cc: @Rkareko

**Comment by samkanga** [comment]
@rowo, @craigappl Please share your thoughts on the comment;

_For OpenSRP server we should standardize the placement for additional icons as this its needed to be configurable for any OpenSRP server in a similar way._

**Comment by craigappl** [comment]
@Rkareko Please hold on this task until these questions are answered.

**Comment by rowo** [comment]
@samkanga @githengi what does that mean additional icons? Like if there were 20 icons? 

Also, Does "Suggest org/country-specific log in bottom right corner" (from [RVL-119](https://smartregister.atlassian.net/browse/RVL-119 ) mean this icon is clickable?

I do think adding that second logo in a random place is kind of weird. And especially country emblems look kind of like buttons sometimes, so it could be confusing. Is there an option to do a co-branded thing where the logos are next to each other — or are we against that as a company? Alternatively, is there a way to use a grey version of any sub-level logo.

**Comment by githengi** [comment]
I think the co-branding would be work better. This is because the login page is kind of centered and may also be easier to implement as part of a standard.

**Comment by rowo** [comment]
@samkanga @craigappl any feedback on pursuing one of the options I made above, with preference for the co-brand like I think we have with some OpenSRP apps?

**Comment by samkanga** [comment]
@rowo there was a discussion scheduled for later today led by Akros. The meeting set to discuss what partners are comfortable with in regards to addition of country specific logos. Craig had shared his thoughts with the team last week as follows:

**Comment by rowo** [comment]
For 1, this is a different situation than white labeling, so I don't think it impacts the decision making here other than being a possible option. Also, if this were using that same approach, Reveal would go below and the emblem would be up top.

**Comment by samkanga** [comment]
@rowo I see your point. On the co-branding comment, can I float that to Akros or was that presently meant for internal audience?

**Comment by rowo** [comment]
@samkanga I'm not sure about the decision making chain here. All I would say is from the UI and tech perspectives the preference is co-branding which is more of the current existing standard. 

The bottom-center, bottom-right and upper-left use of logos we don't have control over (country emblems, for example) will be tougher since they might look like things we don't want them to look like (buttons, for example) or be too small (emblems aren't great at such a small size).

**Comment by Rkareko** [comment]
@rowo @samkanga a decision has been made to go with the first options as shown in [this document ](https://docs.google.com/document/d/1LOys2QYdUNL_vksvggBGyFGZAfVs4zmetRq1t1CChOc/edit)

**Comment by rowo** [comment]
@Rkareko nice, thanks. I can make a final logo to use if you need.

**Comment by Rkareko** [comment]
@rowo that would be great. @Craig or @samkanga could you confirm whether the image to be used is the one on this issue's description section which was downloaded from [RVL-119](https://smartregister.atlassian.net/browse/RVL-119) provided by Pedro or the image shown in [this document](https://docs.google.com/document/d/1LOys2QYdUNL_vksvggBGyFGZAfVs4zmetRq1t1CChOc/edit)

**Comment by craigappl** [comment]
Yes, the image in the issue RVL-119 is what we need to implement. I chopped off the text in the web UI mock-up so it wouldn't appear so small.

**Comment by Naima-Bashir** [comment]
Tested on android 
https://github.com/OpenSRP/opensrp-client-reveal/releases/download/v4.0.0/opensrp-reveal-release-4.0.0-th-en.apk

Updated mockup for Android login: Reveal bottom right corner -DONE

New Requirement: Remove "Reveal" Name and text. Add the BVBD logo - stripped down, no text. Replace "powered by Open SRP” with “Powered by Reveal”. Display only "Pin" Image. Remove "Built on mSpray" -DONE
