### ISSUE TITLE
RVL-804 Add sync logging to the android app and server and submit to greylog and graphite

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#712]
Description

Requirements:

In order to understand sync bottlenecks and tune the sync process, including setting appropriate timeouts, data on sync time per entity in both directions need to be recorded and made available

This could be solved by adding Grafana hooks to measure average sync time per single entity (total sync time for entity type divided by the number of entities synced) disaggregated by implementation location, direction, [wifi signal strength] and others. 

Questions:

How much raw data should be, could be or is stored in Grafana for these types of queries? 

Example Output:

![image-20200220-120951](https://user-images.githubusercontent.com/47570855/79971836-9acbc980-849d-11ea-96ec-e11e38acf81a.png)

**Comment by Rkareko** [comment]
A decision was made to use Firebase Performance Monitoring to collect the metrics from the ndroid client.

**Comment by Naima-Bashir** [comment]
Besides monitoring how the app is performing on Firebase, are there any other acceptance criteria that I need to test?
Kindly advise 
cc @samkanga , @craigappl 
![image](https://user-images.githubusercontent.com/61143692/85849198-31c14480-b7b3-11ea-8fa6-fcfaf968aaa0.png)
