### ISSUE TITLE
RVL-772 - Display how much of data from tablet has synced to server

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#735]
Documented on [Jira](https://smartregister.atlassian.net/browse/RVL-772)

Users should be aware of whether there is unsynced data on their device.

This is a simple and visible status showing whether unsynced data exists on the device so that users can know not to delete their databases or reinstall.

Requirements:

    There should be a flag on the device that shows green if all data on the device is synced with the server

    This should include data in other team databases on the device should they exist

    ASSUMPTION: If the syncStatus of every row in each of the relevant tables is ‘Synced’ then the flag should be green, else flag should be red

    Relevant tables are:

        event

        task

        structure

        client

        formSubmission

**Comment by Naima-Bashir** [comment]
Tested this. Raised this issue: https://github.com/OpenSRP/opensrp-client-reveal/issues/757
and https://github.com/OpenSRP/opensrp-client-reveal/issues/758
