### ISSUE TITLE
RVL-122 - Edit foci boundaries in Android Client

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#737]
Issue documented in [Jira](https://smartregister.atlassian.net/browse/RVL-122)
This [google doc](https://docs.google.com/document/d/1WmSQyOfAJUmpQQFkRm0AW9LNi4nzikmGqsY7ngPF2Lo/edit) provides further documentation.

Description

Description: I want to redraw/edit foci boundaries in the field in real-time so that I can include in the boundary the source of infection and to include houses or cases that are discovered outside // Use case impacted:  // Desired outcome:  // User Story:  // Actor(s):  // Notes:

Below are a list of tasks that need to take place in order to deliver this:

    Add the ability to redraw the boundaries as was delivered by Novel-T in the GeoWidget

    Add the ability to sync locations up from the Android device to the OpenSRP server making sure all versions are stored in the OpenSRP server so they can be referenced independently through the API.

        Only the latest version needs to be stored in the Android client once synced.

    Add auto-incrementing versioning support to locations.

        This is built into the data model, but not implemented in logic

    Add support for inactive, pending and active location statuses.

        Do not sync inactive, display pending and active.

        This is built into the data model, but not implemented in logic in the solution

    Add support for tracking the username, version, and timestamp for changes in the location data model so we can see who made the change when.

    Ensure changes are populated in the data warehouse and BIOPHICS system

    (stretch) add support to the OpenSRP server to query by location version so you can see a history of changes over time.

Acceptance Criteria:

    A user can change a boundary through the Android client UI

        Ensure this works both online and offline.

    Once synced, the change is reflected in the OpenSRP server

    Another user assigned to the same plan/location syncs their device and the change is reflected in the second device.

    The change is confirmed to be made in the data warehouse by viewing the plan in the OpenSRP web UI

    The change is confirmed to be made in the IRS planning module in the OpenSRP web UI

    The change is reflected in BIOPHICS, confirmed by the Thai team querying the BIOPHICS database.

**Comment by Rkareko** [comment]
@rowo the following are steps for editing a foci boundary
1. Navigate to the map view, then long press on the operational area bounday
2. The following edit foci boundary screen appears as seen below
![edit-foci-initial-page](https://user-images.githubusercontent.com/47570855/82573892-01bccb00-9b8f-11ea-95a4-3c9f1007c7c6.png)

3. Click on the `Start Drawing`  button. Black dots appear along the border of the boundary. You can either :
a. Click on the map to add new points.
b. Click on an existing dot which turns red and can be deleted
![edit-foci-start-drawing](https://user-images.githubusercontent.com/47570855/82574378-ab9c5780-9b8f-11ea-87fb-74d8d064349d.png)

4. After editing is complete click on the `Stop Drawing` button.
![edit-foci-stop-drawing](https://user-images.githubusercontent.com/47570855/82574461-d9819c00-9b8f-11ea-843a-0e010a7a22a8.png)

5. After editing is complete click on `Save` to apply the changes

**Comment by rowo** [comment]
@Rkareko A few questions:
- In step 3, why are the black dots different sizes? 
- Is there a selected state of a point?
- Are you able to save while in the "drawing" state?
- How do you exit without saving changes ie cancel?
- No one has a problem with long press? This is pretty advanced for the type of users I thought this app needs to work for, especially since the boundary area does not have a clear hit area. 
- Does tapping on a foci (short press) do anything? 
- If there's a structure on the boundary, would that live "above" the boundary so the user isn't able to tap the boundary on that point?
- Are you able to zoom in/out while in editing mode?
- Would this be accessible in any map view?

**Comment by Rkareko** [comment]
@rowo cc @samkanga 

1. This is the way the implementation in the geowidget is. My assumption is that the bigger dots are used to indicate vertices(corners).
2. A selected point turns Red.
3. In the current implementation yes one is able to save in "Drawing state". This can be changed for UX purposes if need be.
4. Currently using the phones' back button. Suggestions are welcome on how to do this on the UI.
5. @craig made this suggestion. @samkanga can provide a better answer for this.
6. Short tapping on a foci does not do anything
7. Yes the structure would live above the foci boundary
8. Yes it's possible to zoom in/out in edit mode.
9. It's only available in the main map view. Not available in the map view that is displayed when adding a point/structure

Here is an image showing the selected state of a point 
![selected_point](https://user-images.githubusercontent.com/47570855/83048695-ad17c500-a052-11ea-9a65-5f6f651bedc6.png)

**Comment by samkanga** [comment]
@rowo cc @Rkareko 
On #5 above, we passed the suggestion to the client, and they agreed to the long press. We could implement it, and work with the client gather feedback on the user experience once in operation.

**Comment by rowo** [comment]
In step 3 in https://github.com/OpenSRP/opensrp-client-reveal/issues/737#issuecomment-632148931, you can also move any point right? Also, when you add a point, does that then automatically become a corner? I think this might need some fine tuning but I suspect it's not in scope.

**Comment by rowo** [comment]
@Rkareko @samkanga what's the thinking behind the start/stop drawing? Why not jump straight into a drawing mode?

**Comment by Rkareko** [comment]
> @Rkareko @samkanga In step 3 in [#737 (comment)](https://github.com/OpenSRP/opensrp-client-reveal/issues/737#issuecomment-632148931), you can also move any point right? Also, when you add a point, does that then automatically become a corner? After you move a point, does it become selected? If not, then do you select a point by tapping it but not moving it? How do you "exit" a selected point?

@rowo cc @samkanga 
Yes it's possible to move a point.
After adding a point it only becomes a corner is it is not between 2 corners
A point is selected by tapping on it. After which it turns red and you can either drag or delete it.
You exit a selected point by clicking anywhere else on the map.

**Comment by Rkareko** [comment]
> @Rkareko @samkanga what's the thinking behind the start/stop drawing? Why not jump straight into a drawing mode?
> 
> Would something like the below work (3 is a snackbar)?
> 
> <img alt="Screen Shot 2020-05-28 at 11 07 26 PM" width="802" src="https://user-images.githubusercontent.com/1584163/83216776-10c7ee00-a138-11ea-9bf8-2876b51fd420.png">

@rowo cc @samkanga 
This would work. However the changing of the boundary and point color as well as adding a mask outside the area whose boundary is being edited would require  quite a lot of work which would not be possible within the timelines we have. Could we use the black color for the points, boundary and the fill layer that covers the area that is being edited as seen in the image below 

![edit-foci-start-drawing](https://user-images.githubusercontent.com/47570855/83270516-41a83180-a1d1-11ea-8b61-7955b063253c.png)

**Comment by rowo** [comment]
@Rkareko understood. Let me update the screens. I don't really like the highlighted point being red though since it implies deletion (and the delete button should be red) whereas this is just to show an editable state. But let me draw it up and see.

**Comment by craig** [comment]
@craig made this suggestion. @samkanga can provide a better answer for this.

I think it's a good suggestion. We should do it!

**Comment by rowo** [comment]
Wrong @craigappl !

**Comment by rowo** [comment]
@Rkareko @samkanga here's a flow where the boundary editor is opened (temporary snackbar displayed), the lower right point is tapped (temporary snackbar displayed), delete point is tapped with a dialog, then user cancels and a dialog appears the confirm discarding the unsaved edits.

<img src="https://user-images.githubusercontent.com/1584163/83416642-fa978780-a3ee-11ea-82f6-6a9a1018f540.png" width="200"> <img src="https://user-images.githubusercontent.com/1584163/83416653-fd927800-a3ee-11ea-8593-939ac8c90a9f.png" width="200"> <img src="https://user-images.githubusercontent.com/1584163/83416660-0125ff00-a3ef-11ea-950e-81973c105df4.png" width="200"> <img src="https://user-images.githubusercontent.com/1584163/83416672-0420ef80-a3ef-11ea-9499-2fd7eca36f2b.png" width="200"> <img src="https://user-images.githubusercontent.com/1584163/83416675-05521c80-a3ef-11ea-94db-36c79cb3b7f8.png" width="200"> <img src="https://user-images.githubusercontent.com/1584163/83416681-071be000-a3ef-11ea-83bf-7872301dcb2a.png" width="200">
