### ISSUE TITLE
After one applies a filter; all the list of students disappear

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#743]
1. Login to the NTD reveal app
2. Click on Akros_1 for example
3. Select a filter and click apply
4. Observe the page
5. Click filter again and clear your search.
6. Observe if the list of students is shown or not.

EXPECTED RESULTS: The filter applied should show in the list of students.
ACTUAL RESULTS: Applying a filter clears the list of students and does not show even after the filter has been cleared. It only appears when one closes the app and relogs in
![Screenshot_20200519_173624_org smartregister reveal](https://user-images.githubusercontent.com/61143692/82342009-c89f2200-99f9-11ea-975c-c57537164ba1.jpg)

**Comment by rkodev** [comment]
Resolved
