### ISSUE TITLE
RVL-592 - Enrich 'Sync Complete' information with more detail

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#759]
Add detail on percentage of items synced to and from the server (e.g. 20% complete) and give more detail on the types on entities that are synced. 

**Issue:**

The Android client presents the "Sync complete" message when there is more information that needs to be synchronized from the server to the client. Users don't have a clear picture of whether all information has been synced. 

**Requirements:**

1. ‘Sync complete’ should only be displayed when all data are definitely synced in both directions
2. Messaging should be split into sync down and sync up

- For Sync up to the server, a simple progress bar should be sufficient indicating percentage of records that still need to sync up 
- For Sync down, there should be discrete messages on each entity type being synced. A progress bar should show detailing overall completion of sync down (this may get simplified if the sync down mechanism changes to package related entities (e.g. sync is at a structure level - a structure and all related entities are synced in a batch, then the next structure is synced).
   Syncing events
   Syncing tasks
   Syncing client etc

**Development**:
1. The API will need to be able to indicate the number of items that need to be downloaded for each entity
2. An initial sync call will need to respond with this information
3. Could consider a manifest file containing ids of each entity and the entity type to download
4. The device will then download items that are listed in the manifest, reporting on progress

**Mock-up:**
![image](https://user-images.githubusercontent.com/5908630/83135743-fb7aa180-a0ee-11ea-8cb2-bab8a95cdf72.png)

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/84140975-1936f780-aa5b-11ea-8cb5-ce622f59523b.png)
This has passed QA
