### ISSUE TITLE
Add the apk Version on the Hamburger Menu

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#760]
- [ ] The apk version for the android client should be added to the hamburger menu below the **Powered by Reveal** section at the bottom of the page.

**Comment by Rkareko** [comment]
Resolved by #736

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/84138874-a8daa700-aa57-11ea-88c6-fa261eb75816.png)
This has passed QA
