### ISSUE TITLE
 One can record ADR as much as they want

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#775]
Login to the app
Select one of the students
Click on the 3 dots on the top right corner 
Record a dose
After try to record another dose
The record ADR section does not save the previously filled record.
 One can record ADR as much as they want
![image](https://user-images.githubusercontent.com/61143692/83852893-27181000-a71d-11ea-8b24-0b8075b0617c.png)

**Comment by rkodev** [comment]
@Naima-Bashir There is no requirement for the form to have any history or have a limit on the number of submissions. see this issue #711 
The design/purpose for the form is to allow you to fill in the adverse effect when noticed. @isabelcshaw can confirm this

**Comment by Naima-Bashir** [comment]
noted!

**Comment by isabelcshaw** [comment]
@rkodev @Naima-Bashir confirmed - thanks!
