### ISSUE TITLE
Editing the Sync Status Progress Bar

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#791]
- [ ] We need to update the sync status progress bar on the android client so it fits in the screen. Let's remove the word complete so that it reads: **Syncing Tasks: 63%** Below is a sample of the overflowing text.

![image](https://user-images.githubusercontent.com/5908630/85502315-b9f6ec80-b5ef-11ea-851d-7a42166da2b9.png)

**Comment by Naima-Bashir** [comment]
https://github.com/OpenSRP/opensrp-client-reveal/issues/799
same issue. closing the other one
