### ISSUE TITLE
RVL-973b - All partially sprayed structure should be recorded as Sprayed ( appear green on mobile client)

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#814]
**Present Behaviour**

1. Login to the app,
2. select operation area and IRS plan.
3. Tap on a structure, select residential and eligible
4. Enter the rest of the information, ensure to select yet on "where any of the rooms in this structure sprayed?"
5. Enter number of eligible rooms
6. Enter number of rooms sprayed in total (make sure this is lower than the number of eligible rooms )
7. Select reason why some rooms where not sprayed, complete the rest of the form and save.
8.  Partially sprayed structure is considered appears orange in color on the mobile client.

![image](https://user-images.githubusercontent.com/5908630/86864230-7a430100-c0d5-11ea-8448-c0dcaea05153.png)

**Desired Behaviour**

1. Structures that are  partially sprayed should be assigned business status of sprayed, and assigned green color on android

To update the color coding on the Task Register do the following
- [ ] Remove `Partially Sprayed` case statement from [here](https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/java/org/smartregister/reveal/util/CardDetailsUtil.java#L68)
- [ ] Add `Partially Sprayed` business status to the case statement [here](https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/java/org/smartregister/reveal/util/CardDetailsUtil.java#L57)

**Comment by Naima-Bashir** [comment]
Tested this. It has passed QA. See images below.
![image](https://user-images.githubusercontent.com/61143692/88388787-e011d700-cdbd-11ea-9d78-8b37f348ce4c.png)
![image](https://user-images.githubusercontent.com/61143692/88388798-e3a55e00-cdbd-11ea-9ae7-9e58eae28cac.png)
