### ISSUE TITLE
RVL-584 - Spray coverage should be the most prominent indicator on the on-app indicators

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#815]
**Present Behaviour**

1. Add: plan data, android build version info
2. User: onatest
3. Plan: IRS 2019-11-05 Ona Company Retreat Demo
4. OA: Akros_1
5. Note the screenshot. We want the **spray coverage** stat to be in the place of the spray success rate stat, taking up more space and more notable to the user. The **spray success rate** stat can take up just a small space.

![image](https://user-images.githubusercontent.com/5908630/86866145-0efb2e00-c0d9-11ea-8861-8c7e0c13c504.png)

**Desired Outlook**
![image](https://user-images.githubusercontent.com/5908630/86866197-26d2b200-c0d9-11ea-8ac6-6822af603397.png)

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/88388296-ea7fa100-cdbc-11ea-98bd-42c8e95f8a19.png)
This has passed QA.
