### ISSUE TITLE
RVL-949 - Be able to view and edit completed form data on the mobile client

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#816]
**Current Behaviour**
Login to the app tap on a structure to enter data (mark it as sprayed). 
![image](https://user-images.githubusercontent.com/5908630/86877488-a9ff0280-c0ef-11ea-8f27-790317189bea.png)

After completing navigate to the list view.

![image](https://user-images.githubusercontent.com/5908630/86877520-ba16e200-c0ef-11ea-8e8c-a300784ad59f.png)

Tap on a structure marked as complete to view the available actions.

![image](https://user-images.githubusercontent.com/5908630/86877607-e3d00900-c0ef-11ea-8867-dfec7699382e.png)

The pop us comes with the undo and view details options. When the view details is clicked, it opens a new form instead of returning the captured data for edits. See screenshot below.
![image](https://user-images.githubusercontent.com/5908630/86877811-46c1a000-c0f0-11ea-9a42-6d6a0abd92cb.png)

**Desired Behaviour**
The card view (pop-up) should only display “VIEW FORM”. Clicking on view form should display  “UNDO”   and “VIEW FORM”. Clicking on view form  should open the completed form with all the completed form data, and presented with the options: “Edit Form”; “Undo” (i.e. this clears the form); and “Close From” (i.e. no changes made).

Attached is a mock up of the proposed changes.
![image](https://user-images.githubusercontent.com/5908630/86878048-d0716d80-c0f0-11ea-8c66-46d3e014a7fa.png)

![image](https://user-images.githubusercontent.com/5908630/86878058-d7987b80-c0f0-11ea-840f-bd41509fd1b6.png)

![image](https://user-images.githubusercontent.com/5908630/86878090-e1ba7a00-c0f0-11ea-9d27-7b3511d08c37.png)

**Comment by Naima-Bashir** [comment]
Tested this. It has failed QA. See here: 
Desired Behaviour
The card view (pop-up) should only display “VIEW FORM”. Clicking on view form should display “UNDO” and “VIEW FORM”. Clicking on view form should open the completed form with all the completed form data, and presented with the options: “Edit Form”; “Undo” (i.e. this clears the form); and “Close From” (i.e. no changes made).

Attached is a mock up of the proposed changes.
![image](https://user-images.githubusercontent.com/61143692/88389091-76de9380-cdbe-11ea-9074-71ceb28191f1.png)

ACTUAL RESULTS:

![image](https://user-images.githubusercontent.com/61143692/88389106-7e05a180-cdbe-11ea-9d84-337bf323d048.png)
CC @samkanga @Rkareko
