### ISSUE TITLE
RVL- 609 - Enforce access to MBTiles Folder even when data is cleared

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#826]
The Akros team uses the MBtiles folder on the android device to provide offline access to additional maps in different operational areas. The additional maps are cleared using a third party application and the reveal android client is able to show that on the maps. An example of these is `nchelenge_19_w `and `Nchelenge_2019_all` on the screenshot below next to Digital Globe and Mapbox satelitte: 
![image](https://user-images.githubusercontent.com/5908630/87281930-67c52f00-c4fc-11ea-8ba3-b77b2f650f7a.png)

However, whenever a user clears the reveal app data and logs-in again, access to the maps is affected. The client is not sure what happens but they have observed that the first time reveal accesses the MBTiles folder, an additional file named  .mbtiles-journal is created. When the app data is cleared the  `.mbtiles-journal` file is also removed. 

**Desired Behavior**
Akros would like a fix to be made on reveal android client so that clearing of data does not affect the access to the additional offline maps.

**Comment by craigappl** [comment]
@samkanga , have we confirmed with Akros whether we need to develop this?

**Comment by samkanga** [comment]
@craigappl, Yes. I checked with Reuben and he confirmed that the capability is still needed.

**Comment by samkanga** [comment]
I am closing this ticket as it was delivered.
