### ISSUE TITLE
RVL-755 - Inactive versus ineligible structure colours

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#827]
**Current state:**

1. Structures marked as ineligible (ie they are not eligible during this plan) are black
2. Inactive structures (ie they are not structures that will ever be eligible, maybe were enumerated accidentally or entered in error) are grey. 

**Desired Operation**
1. Ineligible - Black (determined based on current in-field data collection) - retain current functionality (ability to view & edit the status of the black structure)
2. Inactive - Grey (this only applies to NON-residential structures that were determined to be non-residential and ineligible in the previous campaign) - need to be able to update ‘inactive’ to ‘not-visited’ (yellow structure) and then proceed as normal. 

See the acceptance Criteria [here](https://smartregister.atlassian.net/browse/RVL-755):

**Comment by Rkareko** [comment]
@craigappl  @samkanga Work on this functionality has been deprioritized as per the conversation [here](https://opensrp.slack.com/archives/G01ADSTGRLM/p1599813285001800)
