### ISSUE TITLE
Error processing Locations hierarchy

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#839]
Login to the zm apk: 
opensrp-reveal-4.2.1-rc1-zm.apk
Login using : dctester1s4 Password1
After the sync is complete, click on the Operational area and observe the error shown.
 
![image](https://user-images.githubusercontent.com/61143692/87666177-d1e60a00-c770-11ea-830f-2f3fe67354d1.png)

**Comment by Naima-Bashir** [comment]
STEPS: 
1. Login to the app 
2. Logout and login with another user 
3. Observe the error

**Comment by Naima-Bashir** [comment]
Just tested this on: 
opensrp-reveal-5.3.13-rc1-prod.apk
I logged in at first using: klm1 then loggedout and logged back in using: nltlatrain29
I then clicked the plan (Lui) then switched to another plan (Nkenga)
I started getting the error above.
cc @samkanga @Rkareko

**Comment by armageddon** [comment]
@Rkareko Hi - any updates on this?
