### ISSUE TITLE
RVL-519 - Mobile client map view at all location levels

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#850]
1. Create a Navigation/Field Guidance Mode for a user to view anything above an individual spray area; 
2. Users should be able to view all spray area borders simultaneously within a health facility catchment. In the picture below the selected spray area is Nabu_22, the user should be able to zoom out and see other surrounding sprays areas
3. ![image](https://user-images.githubusercontent.com/5908630/88661480-3bef9f00-d0e1-11ea-8da1-31e2a284f410.png)
4. Users should be able to view all health facility catchment boundaries within a district. Further zooming out from the spray area view the user should be able to view the district level boundary map view.
5. ![image](https://user-images.githubusercontent.com/5908630/88661811-ce903e00-d0e1-11ea-9642-58b9674da291.png)
6. Ideally in this mode, the user should be able to zoom in from district boundary level map view to Catchment boundary level map view to spray area map view and down to structures. The user can ideally view structure status but with no structure level tasks available (similar to the web). 
7. The user should be able to pan around to view extra features at each level (District, catchment, spray area and structure levels).

**Comment by githengi** [comment]
@samkanga is zoom out upto District level?

Downloading the geojson for all jurisictions in a district will increase size the locations being downloaded considerably.

We need to assess if we can use vector tiles for the other jurisidtions besides the operational areas that a user is assigned to avoid downloading geojson which is bulky.

We need to expore Onaio tile server if it can be used to server the vector tiles
