### ISSUE TITLE
RVL-950 - Mobile client  indicators should be using geo-referenced jurisdictions not user selected jurisdiction

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#852]
**Use Cases**
1. Users drop a point outside of the operational area boundary that should be associated with that operational area boundary

- In this use case a user purposefully drops a point just outside an operational area and believes it should be considered as part of that operational area. The user needs a way to state that this is part of that operational area.

2. Users drop a point outside of the operational area boundary that falls within an adjacent operational area boundary

- In this use case a user purposefully drops a point outside of the operational area boundary, but it actually falls within another known operational area. The user needs to be informed that this point should be considered as part of another operational area and make a decision on whether they want to associate this dropped point with that operational area.

3. Users drop a cluster of points that are outside of any operational area boundaries that are in the system

- In this use case, a user has purposefully found a cluster of points that they need to drop that they know are not part of an existing operational area boundary. The user chooses to associate this with a specific operational area at this time, however, it may be valuable to support an “other” type operational area that can catch all areas within the zone 

4. System administrators need to be able to cross reference the map view and indicators on the Android app and the map view on the web UI.

**Acceptance Criteria:**
See the acceptance criteria [here](https://smartregister.atlassian.net/browse/RVL-950).

**Comment by githengi** [comment]
@samkanga we may have to perform the Geo-refencing on the server side since points could be added to operational area that a user does not have access to

**Comment by samkanga** [comment]
@githengi does this mean that the user will need to have connectivity for points added to an OA that they are not assigned to, or would this be resolved when they sync data from their devices?

**Comment by githengi** [comment]
@samkanga this would mean the server would verify again the points added and try to place to other Operational areas if they are not in the correct operational area

**Comment by githengi** [comment]
The android add will perform the same logic, however because its accuracy is limited to downloaded Operational areas on the device, the server will conduct a second verification since it has all the operational ares

**Comment by githengi** [comment]
@samkanga @craigappl  we need a way for the app to identify the other Operational area

I suggest we add below properties 

"type": "Other Operational Area"
"for": "RHC id or ZoneId id or the highest id that this Operational area is valid"

This will be useful for 2 reasons

- If we want other to not be selectable for default on the hamburger menu
- When adding points can be able to identify which "Other" will be used 

Also the "Other" Jurisdiction should be a leaf location( no children) so that it can be downloaded on the android devices and also needs to be assigned access on the plan and team assignments
