### ISSUE TITLE
Inability to load plan on Nigeria APK on version 5.0.0

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#859]
The login to the the above apk is successful. The operational area is loading but the plans are not. I have checked the plan assignment on stage and it looks OK. It shows the message on the screenshot below. The plans however never load.
![image](https://user-images.githubusercontent.com/5908630/88902300-b3950980-d25a-11ea-85ca-90226af7cc4f.png)

**Comment by githengi** [comment]
Operational area `tantarkwai` is not assigned to the plan `Nigeria-MDA-Demo-Plan-2020-07-21`. Assigning it to fix the issue
