### ISSUE TITLE
Inability to log-in with Account created in Keycloak 

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#860]
- [ ] I have created an account in keycloak and added it to the Reveal WebUI through the API. I created a team and assigned the account to the team. In addition, I created a plan under the Zambia hierarchy and assigned the created team to the plan. However, I am unable to log-into the version 5.0.0 pf the Zambia apk with the username created in Keycloak. The android client returns the error below.

![image](https://user-images.githubusercontent.com/5908630/88910271-e3490f00-d264-11ea-9a15-79745787d455.png)

**Comment by githengi** [comment]
![image](https://user-images.githubusercontent.com/25123762/88932448-c3c2de00-d286-11ea-9574-8a1710ce94cf.png)

Users with action Update password will not be able to login via Oauth2 tokens as they first need to update passwords

**Comment by samkanga** [comment]
Thanks Sam. This is now resolved.
