### ISSUE TITLE
RVL-172 - In app indicators for Namibia

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#873]
Development of the In-App dashboards for Namibia

The indicators are as listed below. The indicators definitions are [here](https://smartregister.atlassian.net/browse/RVL-172):
![image](https://user-images.githubusercontent.com/5908630/89889074-c0f6b000-dbd9-11ea-85fa-87598158badd.png)

- [x] Spray Coverage - sprayedStruct/totStruct 
- [x] Structures Remaining 90% - (totalStruct*90%)-sprayedStruct
- [x] Total Structures - count of all structures in operational area
- [x] Structures Not visited - countif no data against structure
- [x] Structures Visited/Found - countif IRS HH Form is complete & eligibility ="Eligible"
- [x] Sprayed - countif structure_sprayed="Yes"
- [x] Structures Not Sprayed - countif structure_sprayed="No"
- [x] Found Coverage -  structuresSprayed/structuresFound
- [x] Spray Success Rate -

**Comment by githengi** [comment]
@samkanga what values will be displayed on the progress dialog ?

**Comment by samkanga** [comment]
@githengi the 3 indicators at the bottom of the image, see the second last 2 indicators above. These should be presented as percentages:

1. Structures Not Sprayed - countif structure_sprayed="No"
2. Found Coverage - structuresSprayed/structuresFound

I am waiting for information on the third one from @craigappl

**Comment by githengi** [comment]
@craigappl  @samkanga I suggest we have rooomCov as the 3rd progress bar so that same look and feel as Zambia
3. Room coverage of sprayed structures

**Comment by githengi** [comment]
@samkanga the requirements contains the below fields that does exist on the Namibia spray form

>  Structures Visited/Found - countif IRS HH Form is complete & eligibility ="Eligible"
>  Sprayed - countif structure_sprayed="Yes"
>  Structures Not Sprayed - countif structure_sprayed="No"

This I how I implemented

- Structures Visited/Found- count if spray_status is filled and structure is residential
- Sprayed - ableToSprayFirst ='yes'
- Structures Not Sprayed - ableToSprayFirst ='no' or householdAccessible='no' 

Please confirm this is correct

**Comment by samkanga** [comment]
@githengi the edits made sense to me. I will share these with the Namibia team for confirmation.

**Comment by samkanga** [comment]
@githengi we got some updates on your earlier question as follows:

- Structures Visited/Found - count if spray_status is filled and structure is residential. **Comment: We don’t need this**
- Sprayed - countif ableToSprayFirst ='yes' **Comment: If they spray on a follow-up visit, this should be counted too, not just first visit**
- Structures Not Sprayed - countif ableToSprayFirst ='no' or householdAccessible='no' **Comment: Should also take into account follow-up visits where they sprayed**

The following edits were also recommended:
The 3 indicators at the bottom of the page should be two named as follows:
- Target coverage: # of structures sprayed / # structures targeted
- Found coverage: # of structures sprayed / # of structures found

The following 2 indicators should be re-labelled:
- Total structures _should read_ Total structures targeted (because this is fixed and not based on enumeration)
- Structures not visited _should read_ registered households not visited

**Comment by githengi** [comment]
@samkanga the progress indicators will not display correctly with the labels 

> # of structures sprayed / # structures targeted
> # of structures sprayed / # of structures found

As per current design we have to wrap the labels or make the text smaller. Wrapping will mean the component takes more space. Can these be added as info icons which will take more time to be implemented

**Comment by samkanga** [comment]
@githengi the part after the colon is the formula for generating the indicator and does not need to be included. I hope I got your question right.

**Comment by githengi** [comment]
Yes thanks, let me change right away

**Comment by samkanga** [comment]
@githengi Sameen have sent additional feedback for the in-app dashboards as follows:

1. Have only 3 indicators on the text section of the in-app indicators. These are:
Structures targetedtructures found, structures sprayed

**Comment by githengi** [comment]
@samkanga noted.

**Comment by craigappl** [comment]
they should default to zero and we should handle the case where we aren't dividing by zero in the app.
