### ISSUE TITLE
Clicking on the downloaded maps gives a server error 

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#878]
Click on the offline maps on the hamburger menu
Download the maps available 
After the download is finished, click on the downloaded maps section 
Observe the error shown. 
See image below 
![Screenshot_20200812_161247_org smartregister reveal](https://user-images.githubusercontent.com/61143692/90019439-1654bf00-dcb7-11ea-8fd4-2a7ee2485d65.jpg)

**Comment by Naima-Bashir** [comment]
Just tested this on version 5.2 android reveal apk. 
The offline map still gives an error. This time 404. See image below.
![image](https://user-images.githubusercontent.com/61143692/90506405-e39a4300-e15c-11ea-80fd-556e6253f15b.png)

**Comment by samkanga** [comment]
This ticket has also been marked as resolved. Going ahead to close it.
