### ISSUE TITLE
Update the Add location form to include new location types and add iconography

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#89]
I have made a change to the Reveal Data dictionary to include different types of locations.

https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit?ts=5c4ef1e2#gid=0

Types to be added:
"Residential Structure", "Non-Residential Structure", "Facility", "Mosquito Collection Point", "Larval Breeding Site", "Community Meeting/Distribution Point"

**Comment by craigappl** [comment]
@rowo , can you recommend icons for the point location types?

**Comment by rowo** [comment]
@craigappl what kinds of forms will be associated with a non-residential structure?

**Comment by rowo** [comment]
Discussed on slack with Craig: only should include for Reveal r2: "Residential Structure", "Mosquito Collection Point", "Larval Breeding Site" because you wouldn't add a point in the field you aren't doing an action on (a black point).
