### ISSUE TITLE
In app indicators don't appear to be calculating correctly

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#892]
App v5.2.0 Namibia Released Friday 14 Aug
User: onatest
Reveal-stage environment

I created a plan called Dynamic-IRS Namibia Test OA 2020-08-17 (id: 4080863a-e443-54a8-bac6-3fa5cb09bf9e)

Task Sync Returns 0 tasks: https://{{base_url}}/opensrp/rest/task/sync?serverVersion=0&plan=4080863a-e443-54a8-bac6-3fa5cb09bf9e&group=e3a1eac5-61e3-4e6d-b8b2-cbe9417a6ebd

The In app indicators display 55% found coverage. The found coverage should be 0 percent
![image](https://user-images.githubusercontent.com/6067053/90462849-6b7d4000-e0be-11ea-94cf-c6b603192b89.png)

**Comment by craigappl** [comment]
I think there might be a bigger issue here around syncing events that aren't related to the plan we currently have assigned to the user. This suggests to me that the 2019 spray events are being downloaded to the Android client.

**Comment by githengi** [comment]
@craigappl events download is not linked to plans

**Comment by githengi** [comment]
@craigappl this issue was fixed on version 5.2.1 of the APK, retry test in same version
