### ISSUE TITLE
Issue 17: Enable the Edit Boundaries Feature

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#907]
Long press on the jurisdiction boundary not responding
- Login to mobile client
- select OA and Plan
- Long press on the jurisdiction boundary to open the edit screen

**Comment by Naima-Bashir** [comment]
Just tested this on 5.2.0(0.0.5)
I was able to edit and save the foci boundaries. See images below.
![image](https://user-images.githubusercontent.com/61143692/90607160-84463c80-e209-11ea-9a1a-6317d1bf667d.png)
![image](https://user-images.githubusercontent.com/61143692/90607173-890af080-e209-11ea-9edf-c91f633b8a58.png)
![Uploading image.png…]()

**Comment by Naima-Bashir** [comment]
Tested this, closing it
