### ISSUE TITLE
RVL-1053: Hide Ineligibility questions from Thai Forms

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#909]
The following activities have the ineligibility question in the form and should be hidden before roll out:
- [ ] Net Distribution Form
- [ ] RACD form
- [ ] Larvae Dipping
- [ ] Mosquito Collection

**Comment by Naima-Bashir** [comment]
Tested these forms:
Net Distribution Form
Larvae Dipping
Mosquito Collection
They don't have the Eligibility status on them
I have also tested:
Potential Area of Transmission- It has the status(image below)



![IMG_20200826_112143](https://user-images.githubusercontent.com/61143692/91279854-b407be00-e78e-11ea-8f8c-9fab1ac9a042.jpg)
