### ISSUE TITLE
RVL-1068 - IRS House Hold Form Edits

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#912]
Proposed changes after review between Akros & VL:

- [x] Under ‘Why is this structure not eligible?’, Add “Structure does not exist” to the options.
- [x] Remove zone/location question
- [x] Remove data collector question (already a part of metadata from login) - the idea is to get rid of the data collector select question, and associate the logged in user to the name of data collect. which should then be used to populate the drop down list of SOP on the next question. _Basically the TLAs/Data Collectors are being converted to be android users. Hence the mapping that existed between them and the SOPs will remain and this will be referenced from the logged in user as opposed to from the the drop down question._
- [x] Edit HH name field: “Name of structure household head”
- [x] Add back in IRS Number (can’t accept empty values; 8 digits long) above rooms sprayed question.
- [x] Change ‘Were any rooms sprayed’ to ‘Was this structure sprayed?’.
- [x] Reasons why not sprayed: change the order to match the paper HH form 
- [x] Remove 'reasons for not spraying the other rooms'
- [x] Remove population error message for ‘Not Sprayed’ structure.
- [x] Gender logic: Force non-zero value entry for any gender that was marked as House hold head gender. _i.e. if I mark 'male' as the gender for the HH, then later in the form, when it asks how many males, the user should not be able to input 0 given that the HH is male (& same for females)._ 
- [x] Remove number of nets available; retain ‘nets in use’ (able to enter 0).
- [x] Remove number of residents sleeping under nets.
- [x] Add ‘Number of insecticide sachets mixed’ if yes to ‘Was a new insecticide sachet mixed’.
- [x] Add additional serial number fields for each additional sachet mixed.

**Comment by Rkareko** [comment]
@samkanga can we have a better more detailed description for `Gender logic: Force non-zero value entry for any gender that was marked as House hold head gender.`
