### ISSUE TITLE
RVL-1070 - Edit Enter Team Leader DOS form

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#913]
Proposed changes:
- [x] Change from “please write the name of the zone/location” to ‘Name of location’, with drop-down of locations assigned to TLA that day (select one)
- [x] Remove District Manager name field
- [x] Remove Supervisor field
- [x] Remove: “Did the SO triple rinse the bottle”
- [x] Remove “(Hudson Ony) is SO spraying with a pump fitted with a CFV?”
- [x] Edit answer choices (remove 2nd ‘No’) for Is SO using torch?

**Comment by githengi** [comment]
Update from @samkanga this only shows Zones
