### ISSUE TITLE
RVL-1067 - Change ‘Zone’ in android to read ‘Location’ for VL (2020) hierarchy level 4

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#914]
- [x] The naming of the hierarchy level 4 should change from Zone to Location.
- For example, Cahndiwe zone on the image below should read Chandiwe Location.
![image](https://user-images.githubusercontent.com/5908630/90630329-84eecb00-e229-11ea-85e0-df99d6937aba.png)

**Comment by Rkareko** [comment]
@samkanga Those names should be edited on the locations themselves.

**Comment by githengi** [comment]
@samkanga update locations on stage please confirm this has been done correctly

Query used
```
update core."location" l set "json" =jsonb_set("json",'{properties,name}',to_jsonb(replace(lower(name),'zone','Location')),true )
from core.location_metadata lm  where l.id =lm.location_id  and name ilike '%zone';


update core.location_metadata set name =replace(lower(name),'zone','Location'),server_version =0 where  name ilike '%zone';

```

**Comment by samkanga** [comment]
@githengi this has picked for some locations. Some location have dropped the term "zone" and not picked the new term "location" see sample screenshot below:
![image](https://user-images.githubusercontent.com/5908630/91585484-cc2d3800-e95c-11ea-851f-854283cd518a.png)
 
Could we also maintain the capitalized first letter on the location name. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/91585675-0b5b8900-e95d-11ea-8ab2-8b8313591aaf.png)

**Comment by githengi** [comment]
@samkanga this would imply that the locations did not have the word `Zone` were this part of the issue?

**Comment by samkanga** [comment]
You are right. The issue mainly mentioned the locations that had the zone name. We can wait for QA to take place and see if we get additional feedback
