### ISSUE TITLE
RVL-1058 - The 25m circle of selection was prompting the password even when within 25m 

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#915]
The 25m circle of selection was prompting the password even when within 25m (i.e. the user was within the blue GPS radius of 25m) in the northern part of ksh_8 (near the hospital).

However when a user closes the app (press home button to minimize the app),  and opens it up again. user is able to enter data for the same structure which requested for a password initially. 

**Current behavior:** Added structures selected within the 25m circle of selection are not prompting the user to enter the password (tested in Lusaka).

**Behavior when reported:** User was being prompted to enter the password when the structures being selected were withing the circle of selection.

**Expected behavior:** Any structure selected within the 25m circle of selection should not prompt the user to enter a password.

**Comment by samkanga** [comment]
@githengi you had mentioned that we have a fix for this issue. I added a ticket here based on the feedback from the client for tracing purposes.

**Comment by githengi** [comment]
@samkanga The feature for requesting passwords uses the client used by the map. The Update by Kujaku should be able to resolve the issue.
