### ISSUE TITLE
RVL-1049 - Only events completed by the logged in user must be visible on the Filled Forms View by default

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#916]
User logs in to mobile client,
Taps on Filled Forms.
Filled Forms view open.

- [x] The user should only see events that they completed by default. All events completed by other users must not be visible.
- [x] There should be a provision for a user (supervisor) to view all events by entering a password on the same tablet.

**Comment by githengi** [comment]
closed by #863
