### ISSUE TITLE
RVL-1014 - Not possible to mark households as inactive

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#921]
Server: Thailand Production
User: bvbd_test
App: Thai/English version 4.1.1
1. Login to the app ( thailand/English Version )
2. Select operation area and plan
3. Once the app loads fully. Long hold a structure.

**Current behavior:**
In Thai version 4.1.1 (and english version too), when long pressing a household, nothing happens.

**Expected behavior:**
Pop up requesting to confirm the marking of structure as inactive.

**Comment by Naima-Bashir** [comment]
Just tested this on https://github.com/OpenSRP/opensrp-client-reveal/releases/download/v5.2.2-thai/opensrp-reveal-release-5.2.2-th.apk
I was able to hold on to a structure and make it as inactive. cc @samkanga @Rkareko 
![image](https://user-images.githubusercontent.com/61143692/91155256-45adf780-e6cb-11ea-8260-84f23bb650f6.png)
![image](https://user-images.githubusercontent.com/61143692/91155273-49da1500-e6cb-11ea-9f75-7f2ee3dda904.png)
