### ISSUE TITLE
DOWNLOAD button is unresponsive when trying to download a second map

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#924]
Version: 5.2.0
Android Version: 7.1.1
DOWNLOAD button is unresponsive when trying to download a map
1. Download one map
2. Attempt to download a second map
3. the download button is unresponsive

**Comment by samkanga** [comment]
This has been marked as resolved on the tracking sheet and I will go ahead and close it.

**Comment by Naima-Bashir** [comment]
This has passed QA. Tested it on https://github.com/OpenSRP/opensrp-client-reveal/releases/tag/v5.2.4-namibia
