### ISSUE TITLE
Some Operational Areas are not showing on the Operational Area Drop Down

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#928]
- [ ] Some Operational Areas are not showing on the Operational Area Drop Down but appear under the offline maps download.

Here is the drop down for user Namibia1
![image](https://user-images.githubusercontent.com/5908630/90860248-56d8ca80-e392-11ea-83b7-bb00ee26ca9b.png)

Here is the list of maps on the offline download section. Note that while Iitananga is on the download section, its not on the operational area drop down. NB The Iiya map is not listed as it was being downloaded.
![image](https://user-images.githubusercontent.com/5908630/90860384-92739480-e392-11ea-8153-f465df2c4316.png)

**Comment by samkanga** [comment]
@Rkareko this is now working. I will go ahead and close the issue.

**Comment by Naima-Bashir** [comment]
This has passed QA
