### ISSUE TITLE
Add structure form not fully loading

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#929]
- [ ] The add structure form allows one to only capture the village name and the other details are hidden. See screeshot below.
![image](https://user-images.githubusercontent.com/5908630/90860669-16c61780-e393-11ea-9970-977c8221c052.png)

**Comment by Rkareko** [comment]
@samkanga The missing fields are hidden and populated with default values as documented on [this issue](https://github.com/OpenSRP/opensrp-client-reveal/issues/386)

**Comment by samkanga** [comment]
@Rkareko thank you for the additional information. Let me retest and share additional feedback.

**Comment by samkanga** [comment]
@Rkareko I confirm this works. Thank you.
