### ISSUE TITLE
THAI- Some sections are in english, some in Thai -RVL 1137

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#942]
APK- 5.2.2 thai
Login to the app
Register a family and fill in their details.
Observe the family details section, it has mixed languages.
See image below.
![image](https://user-images.githubusercontent.com/61143692/91279071-bae20100-e78d-11ea-978a-e7a1a90c118d.png)

**Comment by Naima-Bashir** [comment]
update on: 5.2.4
There are some sections that are still in english in the th apk
![image](https://user-images.githubusercontent.com/61143692/92095510-70403480-edde-11ea-916c-7b90ff80c455.png)

**Comment by Rkareko** [comment]
@Naima-Bashir cc @craigappl , @samkanga for the Record Screening and Record Distribution these are the translations that had been provided as seen [here](https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/res/values-th/strings.xml#L141-L143)
