### ISSUE TITLE
Error After Cancelling Log in by user from a Different Team

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#945]
- [ ] Assume you have user1_nam being part of team A and user3_nam being part of team B. 

- Login to the App with user1_nam then log out of the App
- Attempt to log in with user3_nam but at the point where the app asks for confirmation to clear data, choose the cancel option.
- Try and log in with user1_nam. The login with user1_nam will now not be possible.

**Comment by Naima-Bashir** [comment]
Tested this on afew users. It has passed QA
