### ISSUE TITLE
Locate me Icon on the Android Client is hidden by In-App indicators

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#946]
- [ ] The locate me button on the Namibia APK is presently hidden under the in-app indicators. Let us move this up to be slightly above the in-app indicators at the same level with the add structure button. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/91296426-3f8c4980-e7a5-11ea-8454-0f33255488d3.png)

**Comment by Naima-Bashir** [comment]
This has passed QA
