### ISSUE TITLE
The sync button is not working--it says failed RVL-1167

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#959]
Login using Nambia1
Click on the sync button
Observe the sync fail error
![Screenshot_20200828_152512_org smartregister reveal](https://user-images.githubusercontent.com/61143692/91560865-3cc75b00-e943-11ea-8205-b1a117e8b15a.jpg)

**Comment by Naima-Bashir** [comment]
this is still happening  
thaiuser2

**Comment by samkanga** [comment]
@Naima-Bashir please retest this with bvbd_test account and share an update.

**Comment by Naima-Bashir** [comment]
@Rkareko @samkanga just tested on 5.2.9 using bvbd_mhealth  - The sync is complete, no sync failed bug. I'll also update it on jira
![image](https://user-images.githubusercontent.com/61143692/93866509-6b311f80-fcd0-11ea-887a-1c856ecf4c34.png)
