### ISSUE TITLE
RVL-1119 - Reveal app crashes after a user has synced a structure registered offline

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#979]
Version: 5.2.4

Steps to reproduce:
1. Turn internet connection off
2. Add a new structure in Map view
3. Turn internet connection on
4. Open hamburger menu
5. Click sync
6. Wait for sync to be completed
7. Click list view

App crashes and user has to restart the app.

**Comment by Rkareko** [comment]
Resolved: removing battery optimisation on a Huawei device solves this bug! see comments on the jira ticket https://smartregister.atlassian.net/browse/RVL-1119
