### ISSUE TITLE
Spray Form not Editable when Selected from List View

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#985]
- [ ] When the spray form is selected from the list view either for a partially sprayed structure or fully sprayed structure, the question on "Were you able to access this household?" appears disabled and cannot be edited.

**Comment by samkanga** [comment]
@Rkareko see the updates made to ticket RVl-1125 below:

**Comment by faith-mutua** [comment]
@samkanga @Rkareko the question `Were you able to access this household?` is still not editable for Partially and fully sprayed structures in v5.3.4-rc2. The responses are greyed out. This happens when the user answers yes to the question AND saves/submits the form.

**Comment by samkanga** [comment]
@faith-mutua my earlier comment was additional information on what was expected to happen. That is the first 2 questions should not be editable once the user answers Yes to the questions and saves/submits form. cc: @Rkareko , @Naima-Bashir

**Comment by faith-mutua** [comment]
@samkanga I get it now. I had misunderstood your comment. We can mark this as resolved.
