### ISSUE TITLE
Filter Does not Work the first time it is used

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#986]
- [ ] Resolve Filter Does not Work the first time it is used

Steps to reproduce;

1. Log into the app
2. Select the filter option and choose one of the options
3. Click on apply filters. Nothing happens.
4. Go back to the filter menu and click apply filters again.
5. This time the filter applies.

**Comment by faith-mutua** [comment]
@samkanga @Rkareko This issue is now fixed in v5.3.4-rc2. Filters are working as soon as the user applies them and `Type` has also been removed from the `Sort by` menu.
