### ISSUE TITLE
THAI- One can't create new family members  RVL-1131

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#992]
Login to the app
Register a new residential structure.
After you click save.
Try to add new family members- it's not possible.
When one clicks on the structure, the only two options are View details(which lead the user to esit spray status) or UNDO
![image](https://user-images.githubusercontent.com/61143692/92086762-4df4e980-edd3-11ea-8923-9be610dd0491.png)

**Comment by samkanga** [comment]
@Naima-Bashir can we close this ticket?

**Comment by Naima-Bashir** [comment]
yes @samkanga
