### ISSUE TITLE
[THAI] Thai and English apk have different number of structures(13 and 10) RVL-1138

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-reveal#995]
Login to the app with the same credentials: 5.2.4 in two devices; thai english and thai 
Click on list view
Observe the number of structures with 25m
One says 10 in total  one says 13

![image](https://user-images.githubusercontent.com/61143692/92096755-ebeeb100-eddf-11ea-8659-9db1f4774946.png)

**Comment by Rkareko** [comment]
Covered by #996
