### ISSUE TITLE
RVL-1138 Thai and English APK show different structure counts

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#996]
Naima found that the English and Thai APK has different structure counts:
https://smartregister.atlassian.net/browse/RVL-1138
Steps to recreate:

1. Login to the app with the same credentials: 5.2.4 in two devices; thai english and thai
2. Click on list view
3. Observe the number of structures with 25m
4. One says 10 in total one says 13

![image](https://user-images.githubusercontent.com/61143692/92208320-9c69bd00-ee93-11ea-847e-e723b677b4bb.png)

![image](https://user-images.githubusercontent.com/61143692/92208484-f7031900-ee93-11ea-8444-a85182442be9.png)

**Comment by craigappl** [comment]
@Naima-Bashir , can you add steps to recreate this?

**Comment by Naima-Bashir** [comment]
@craigappl I had raised an issue already with the steps here:
https://github.com/OpenSRP/opensrp-client-reveal/issues/995
The steps are 
Login to the app with the same credentials: 5.2.4 in two devices; thai english and thai
Click on list view
Observe the number of structures with 25m
One says 10 in total one says 13
