### ISSUE TITLE
RVL-1013 Fix Thai Translations

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#997]
Please see the attached powerpoints on this issue in Jira: https://smartregister.atlassian.net/browse/RVL-1013

**Comment by samkanga** [comment]
RVL-1013 has been set to under review today. This ticket will be updated with more information once the review process is completed.

**Comment by samkanga** [comment]
@Rkareko and @craigappl Pedro confirmed that the fixes requested on RVL-1013 are all in. I will go ahead and close this ticket.
